### ISSUE TITLE
[BUG] Graphical error on campaign selection screen (post login)

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#1002]
**Describe the bug**
Drawn suare behind the circular play button shows
![image](https://user-images.githubusercontent.com/2258333/179366092-063b912c-b52b-4637-a9f9-ee6dabf97fca.png)

**Desktop (please complete the following information):**
 - OS: Void linux
 - Browser Firefox 102.0
 - Version 2022.2.2

**Additional context**

**Comment by Kruptein** [comment]
I'm going to close this as the design will change with the next release.
