### ISSUE TITLE
[BUG] When using a subpath setup, the asset manager redirects to an incorrect, nonexistant page

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1006]
**Describe the bug**
As the title states.
When a subpath is enabled, entering the asset manager will go to 'https://host/subpath/assets' for a split second before redirecting to 'https://host/subpath/subpath/assets' which is a blank page.

**To Reproduce**
1. Build PlanarAlly with subpath enabled in the client.
2. Launch the server with subpath environment variable set.
3. Login and click on Assets -> Manage.
4. Get redirected to blank page.

**Expected behavior**
The asset manager should not redirect from 'https://host/subpath/assets'.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 2022.2.3

**Additional context**
This is without using any reverse proxy. Connecting straight to the server on the same machine causes this issue too.

**Comment by Kruptein** [comment]
It's been fixed on the dev branch, so normally you would have to wait until a next release.

The fix itself is however only a 1 line change, so you should be able to manually change the line and rebuild the client. (See [the PR changes](https://github.com/Kruptein/PlanarAlly/pull/1007/files) for the details)
