### ISSUE TITLE
[BUG] Assets not snapping in a hex grid

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#1010]
**Describe the bug**
Assets not snapping in a hex grid like they would be expected to do when using a square grid.

**To Reproduce**
Enable hex grid in DM Options, issue is with pointy and flat hexagons, drag an asset around drop it and see it not snap into a hex.

**Expected behavior**
Assets should snap into a hexagon, just like how they do for a square grid.

**Screenshots**
https://youtu.be/HK4kPcd1YIg

**Desktop (please complete the following information):**
 - OS: OpenSUSE MicroOS
 -  Firefox and Chromium (latest flatpak versions from flathub)

**Additional context**

**Comment by Kruptein** [comment]
Yeah it's something I've been aware of basically since the introduction of the hex grid :D

I never got to implementing the snapping for hex grids and it just has been lingering for a while.

**Comment by 10leej** [comment]
I figured you would be, but I just thought I'd post the bug for someone not
aware. Usually when I find the need for a hex grid I just disable the grid
entirely. Which works fine. But this is mostly being reported for UX
reasons.

**Comment by Kruptein** [comment]
Oh no I absolutely appreciate you making an issue for it.
It helps with tracking things I otherwise tend to forget :D

**Comment by Kruptein** [comment]
This has now been implemented on dev!
