### ISSUE TITLE
[BUG] [GAMEBOARD] No ability to delete, move or rename assets

### ISSUE THREAD

**Issue by FuzzySadist** [Kruptein/PlanarAlly#1016]
**Describe the bug**
No ability to delete, move or rename assets

**To Reproduce**
1. Create new asset or folder
2. Click on asset or folder
3. No options to delete, move or rename

**Expected behavior**
Should be able to delete move and rename assets and folders

**Comment by Kruptein** [comment]
Fixed in gameboard server version 1.16
