### ISSUE TITLE
[FEAT] Click map to autozoom it to fit the window

### ISSUE THREAD

**Issue by FuzzySadist** [Kruptein/PlanarAlly#1018]
Click map to autozoom it to fit the window.  Its always a pain to 'find my map' with all the real estate on the grid, when all I really want is my map.  It would be nice if I could find a way to just show my map, and zoom it in as needed, or at least center on the map.

**Comment by FuzzySadist** [comment]
NVM, its firefox, its not showing me the menu's I need.  The right click menu is covering it.

**Comment by Kruptein** [comment]
I can close this then?
