### ISSUE TITLE
[FEAT] Asset manager multiselect

### ISSUE THREAD

**Issue by FuzzySadist** [Kruptein/PlanarAlly#1031]
I recently uploaded a large set of tokens by mistake.  Currently I had to select each one to remove it.  I'd love the ability to select more then one at a time before removing.  I assume the modal would have to change rom Rename/Remove to just Remove.

**Comment by Kruptein** [comment]
I'll be pushing an update to the gameboard version soon (one of the coming days) that supports exactly that, along with some general UI/UX improvements to the asset manager!

The main codebase will have to wait a bit until I'm done porting the new asset manager over
