### ISSUE TITLE
[BUG] Dice Roller doesn't work when using subpath

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1044]
**Describe the bug**
The dice menuing works up until clicking 'GO'. Then nothing happens, no dice and no popup saying the result.

**To Reproduce**
1. Click the 'Dice' button on the toolbar.
2. Select any combination of dice to roll.
3. Click 'GO'
4. Nothing happens.

**Expected behavior**
A 3D dice should show up on screen and after it settles a popup should appear showing the result.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser Firefox 104.0
 - Version 2022.2.3

**Additional context**
The dice rolling works perfectly fine when not using a subpath, so I suspect that's the issue.

**Comment by Kruptein** [comment]
Sorry for the delay, but it has been fixed on the dev branch!
