### ISSUE TITLE
Strange Desync Between DM and Player of Token Aura's

### ISSUE THREAD

**Issue by lmd2** [Kruptein/PlanarAlly#106]
When creating an aura for a token as a player/dm the other cannot view the aura unless the token is being moved by the side that created it. If the opposing side at any point selects the token the aura vanishes for both sides. I have attached a small gif displaying this problem, the left screen is the DM session and the right is the player session. In this example the Aura was created by the DM and is only viable by the player during movement, but its worth noting that the exact same behavior happens when the player creates an aura on a token.
![aura bug](https://user-images.githubusercontent.com/44935466/48308348-5c478680-e517-11e8-8dd5-d691b1ec75a5.gif)

I am running windows 10, Python 3.7.1, and Planar Ally 0.11.5 (https://github.com/Kruptein/PlanarAlly/releases/tag/0.11.5).

Any help is greatly appreciated!

**Comment by Kruptein** [comment]
I'm able to reproduce this, this should definitely not happen!

**Comment by Kruptein** [comment]
ok I found the root issue, I'm gonna test a couple of things to make sure it behaves as I want and then I'll release 0.11.6 and close this issue
