### ISSUE TITLE
Automatically opening each new map on the map layer makes it very easy to accidentally place tokens on the map layer.

### ISSUE THREAD

**Issue by poltergeisha** [Kruptein/PlanarAlly#109]
When you open an already created map, you expect to immediately start on the token layer But it's on the map layer, and you forget, so you start creating tokens, then realize you fucked up, then have to manually move them all to the token layer....

**Comment by Kruptein** [comment]
This alao odten leads to moving the map by accident in my experience.

This is indeed something that should have been implemented sooner, sorry

**Comment by Kruptein** [comment]
The latest dev branch has been updated with functionality to remember which layer you had active last time.

**Comment by poltergeisha** [comment]
You are amazing!
