### ISSUE TITLE
[FEAT] We need editable "Characters" or "Crafts", with tokens, bars, trackers and everything so they can be easily dropped on a map.

### ISSUE THREAD

**Issue by ApriamAsh** [Kruptein/PlanarAlly#1126]
The problem with the current status of things is simply accessibility. In order to create a new Character/NPC, I have to upload the token, resize it, add all of my bars and trackers (I use a custom system that I made), fix the vision, etc. This makes creating encounters very tedious, and I can only circumvent it by creating a "Repository" map with all of the premade characters in it which I spent a ton of time making, and then copying and pasting them into the map that I want.

The solution would be to create "Characters" or "Crafts" for all sorts of objects, NPCs, PCs, mobs, Invisible lighting, etc, in a repo to the right side of the screen, which can be duplicated, copied, their tokens edited, etc.. This would make things much easier and a lot more accessible.

A half-measure Alternative could be allowing the GM to set "Defaults" for bars and trackers and variables for all tokens, so that each one character does not have to be individually created, or to be able to Copy the properties and variables of a token to another token, but this leaves the light issue unhandled.

It would be nice to add the possibility of custom character sheets to these "Crafts" like lets role, and the possibility of "Anchoring" the bars and trackers to the variables of these character sheets specifically for player characters or unique NPCs, so that when the "Anchored" token is dropped (Not all tokens must be anchored to a sheet), it carries over the variables of the sheet to the bars and trackers of the token (Like player character's health being the same across all maps and all tokens because their token is "Anchored" to their Character Sheet.

**Comment by develroo** [comment]
I think you are unaware you can select and copy groups of  tokens.

Typically, when I am doing a group of monsters with all the same characteristics, I drop one asset and resize add trackers, names, light auras etc. Then I select is Cntrl-C Cntrl-V and a copy is made. You can draw around both copies and copy and past again making 4, in few clicks I have made 20 tokens and I then only need to identify any particular ones with special abilities.  

Also, as I think has already been mentioned, tokens can have variants and so what can be done is making, say, an orc token but then added a variety of variants to it. That way you can copy as before but then have those unique bosses or foes be a different variant. 

In addition, when you add variants you can have templates of tokens you can use. Here is an example.

[Screencast from 2022-12-17 10-07-09.webm](https://user-images.githubusercontent.com/7777993/208236757-bc375f70-f5dd-4093-b209-38d0148d6816.webm)



Not sure if this is what you want, but it seems less complicated than what you describe.

**Comment by ApriamAsh** [comment]
A character sheet will help store characters conveniently into a repository independent of tokens, allows us to store info on them like stats and whatnot, like in roll20, it will be very convenient.

**Comment by Kruptein** [comment]
This issue is a bit of a mix of different requests.

> I have to upload the token, resize it, add all of my bars and trackers (I use a custom system that I made), fix the vision, etc

This can, like develroo mentioned, completely be resolved with Templates, See https://www.planarally.io/docs/dm/assets/#templates.

The rest of your issue (i.e. variables and character sheets) is complexer stuff that I don't intend to fully implement myself.
Instead I'm opening up some things to allow experimental mod support where it's up to others to create character sheets etc that interact with the internal PA APIs. The first part of which is #1287.

I'm going to close this issue as it describes multiple separate issues and I feel like I'm addressing at least some parts of it already.
