### ISSUE TITLE
Check out FabricJS

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#115]
I saw this and noticed that it's the framework Roll20 is using as well.
I really got no clue about JavaScript, but maybe this helps?

https://github.com/fabricjs/fabric.js

**Comment by Kruptein** [comment]
Hi, yeah it's a common canvas api.

When I started this project I made the decision to try and learn how the canvas works and thus create my own canvas api.

This also allows me to have complete ownership over the entire render stage, which with the lighting algorithm and different layers comes in handy.

I have no current plans to migrate to fabricjs, but maybe somewhere in the future it might happen.
