### ISSUE TITLE
[BUG] Fake Player quick toggle accessible by non-GM players

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1152]
**Describe the bug**
The Fake Player toggle is visible to non-GM players, giving them the ability to gain some amount of GM privileges including:
- Full vision of the map
- Access to the map and fov layers
- Ability to locally edit assets they should not have access to
- Access to locations drop down menu
- Access to DM settings

The server does not seem to accept any changes made to GM only assets or settings.

**To Reproduce**
1. Open a map as a non-GM player.
2. Click on 'FP' quick toggle twice

**Expected behavior**
The FP quick toggle should not be visible to non-GM players.

**Screenshots**

What the player can normally see:
![image](https://user-images.githubusercontent.com/2442544/216705374-0e27799c-bddc-492b-b4c9-bfc2f487e8c7.png)

What the player gains access to with this bug:
![image](https://user-images.githubusercontent.com/2442544/216705515-973cddf5-7d01-4379-8582-73729f0d55d2.png)

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 108.0.2
 - Version: dev branch commit [2a708dd](https://github.com/Kruptein/PlanarAlly/commit/2a708dd367801fb6cacfffd481300bb475aa2a81)

**Comment by Kruptein** [comment]
Thanks for the report, the issue is a bit deeper in that some value got wrongly replaced with a recent refactor.

**Comment by rexy712** [comment]
No problem. I just removed the button for the time being to prevent my players from peeking through the fov :)
