### ISSUE TITLE
[BUG] 'Save Template' no longer functions

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1156]
**Describe the bug**
I recently updated from release 2022.3 to using the dev branch, and now the 'Save Template' button in the right click menu no longer saves. A popup appears asking what to name the template as expected, but that's all. No popup asking which template to use when adding a new shape, and when hitting 'Save Template' again the only one in the list is 'default'.

**To Reproduce**
1. Create a shape on a map from an asset
2. Change settings on token how you like
3. Right click the token and hit 'Save Template', name it anything
4. Add another shape from the same asset to the map
5. No popup to ask what template to use

**Expected behavior**
Saving a template should add it to a list one can select from when adding the asset as it did previously.

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 108.0.2, ungoogled-chromium 109.0.5414.119
 - Version: dev branch commit [2a708dd](https://github.com/Kruptein/PlanarAlly/commit/2a708dd367801fb6cacfffd481300bb475aa2a81)

**Additional context**
I should also note, previously the templates would work. However the name of the template would only ever include the first letter of the name I tried to save it under. I should have reported this at the time, but it was only a slight inconvenience and I forgot.

**Comment by Kruptein** [comment]
I actually noticed that 'first letter' only thing as well recently, forgot to log that, so thanks again.

**Comment by develroo** [comment]
Hmmm never noticed this broke.  Existing templates still work as far as I can see though.
