### ISSUE TITLE
DNDBox Planar Ally needs to be rolled back or pushed to the dev branch

### ISSUE THREAD

**Issue by poltergeisha** [Kruptein/PlanarAlly#116]
@schemen There are some serious bugs (see my other recent issues) in the current release of PA. Would it be possible to roll back planarally.dndbox.com to a previous release, or to move it to follow the dev branch where the bugs are fixed?

**Comment by schemen** [comment]
Currently it is not possible to roll back without verifying the database first as I see  - We'd  need to help get the bugs fixed :)

What are you experiencing?

**Comment by Kruptein** [comment]
I've created a new release,

Keep in mind at all times, that this codebase has not reached a stable version yet, so make sure you have backups in case the new release breaks things.
