### ISSUE TITLE
[BUG] Asset Manager right click is vertically offset when the page is scrolled down.

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1169]
**Describe the bug**
When right clicking in the Asset Manager, a small dialog opens to rename or remove the asset. This works fine unless the page is scrolled down at all. Then the dialog is offset down the page proportional to the amount scrolled. This can make renaming assets low on the list very difficult if not impossible on some window managers.

**To Reproduce**
1. Open asset manager folder with a lot of assets (enough to allow scrolling down the page)
2. Scroll down by any amount.
3. Right click on any asset
4. Dialog is vertically offset

**Expected behavior**
The dialog should be under the cursor no matter the scroll position of the page.

**Screenshots**

Video showing the normal behavior at first, then the bug after scrolling.

https://user-images.githubusercontent.com/2442544/218191769-e5157b67-3f2d-44fe-9835-65448a92ab95.mp4

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 109.0.1, ungoogled-chromium 109.0.5414.119
 - Version: dev branch commit [06b7124](https://github.com/Kruptein/PlanarAlly/commit/06b712440ad38bec4fb32e514acfcbeeb3a45216)

**Comment by Kruptein** [comment]
Making it scroll along is kind of a pain to accomplish smoothly in the way it's structured now.

I'm going to resolve it for now by closing the context menu when scrolling instead. In most cases you're not going to scroll when you want to interact with the context menu in the first place.

**Comment by rexy712** [comment]
I've updated my instance to include #1184 and tested. The issue is still there.

I don't think I was clear in the wording of my original issue. The problem isn't about the context menu moving with the contents of the page as the user scrolls. The issue is that if you're already scrolled down by any amount, the context menu doesn't open at the position of the cursor.

In the video from my original post in this thread, you can see this demonstrated. *After* I scroll down, I right click and the menu opens at a vertical offset. When scrolled by more than a certain amount, the context menu is positioned offscreen making it impossible to rename some assets.

**Comment by Kruptein** [comment]
Ah I see, well the thing I did fix was also bothering me, but yes I can confirm that what you're describing is still happening.
