### ISSUE TITLE
[BUG] Specifying no access to a shape for a specific player allows them to see name and trackers

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1187]
**Describe the bug**
I will denote access to a shape as RWX (read, write, execute) for vision, edit, and movement access respectively. A hyphen meaning they lack that permission (eg R-X has vision and movement rights to the shape)
When the Access setting of a shape is set to '---' for the default case, no one can see the name of the shape or trackers. This is how it should behave. If you add an access entry for a specific player and set that permission to '---', it still behaves as if that player has 'R--' access to the shape. Meaning they can see the name and trackers of the shape. Giving 'RW-' permssions works as intended, as does 'RWX'.

**To Reproduce**
1. Create a token, set name and trackers.
2. Add access control to the token for a specific player to '---'
3. Have the player select the token.
4. The player is able to see the token's trackers and name.

**Expected behavior**
Access of '---' for a specific player should behave the same as for the default case where name and trackers are hidden.

**Screenshots**

GM is on the left, Player is on the right.
I first show the intended behavior via the Default access control. Then show that 'R--' access works. Then I show that changing to '---' permissions does the same thing as 'R--'. I refresh the page at the end to show that it is persistent.

https://user-images.githubusercontent.com/2442544/218589496-cfb97dec-76fd-42be-9b9c-9b4cf59e9f63.mp4

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 109.0.1, ungoogled-chromium 109.0.5414.119
 - Version: dev branch commit [1e7e22b](https://github.com/Kruptein/PlanarAlly/commit/1e7e22b6aa2ae1fd6f2c48e77d682362f784d9ea)

**Comment by Kruptein** [comment]
This is indeed bugged.

I do want to talk about the different access tiers though, as your mapping of r,w,x does not fully map to what they actually imply.  Vision access just does that, give access to the vision that token has. It does not give you read access to the shape's other properties in general.
Similarly the movement access only adds that extra ability

This means that (in regards to fixing this bug) for now the ability to see the private auras and trackers will be locked behind the 'edit' access right.

**Comment by rexy712** [comment]
Hm, I never realized that was meant to be vision access only. It always gave access to view the trackers and names when I used it, so I assumed that was the way it was meant to work. And yeah the rwx permission analogy is flawed, but it was meant to just make it easier to write up. It seemed close enough to work for that purpose.

I agree it would be nice to have vision and read access as separate permissions. Could be pretty useful for things like DMPCs, or PCs that aren't fully trusting of with each other.
