### ISSUE TITLE
use interfaces

### ISSUE THREAD

**Issue by championswimmer** [Kruptein/PlanarAlly#119]
https://github.com/Kruptein/PlanarAlly/blob/bae0f01683e17623d510003bd0df52c035b4e6db/client/src/core/store.ts#L11

You may want to do 

```ts
interface ICoreState {
  authenticated: boolean
}

@Module({...})
class CoreState extends VuexModule implements ICoreState {
   authenticated = false
}
```

**Comment by Kruptein** [comment]
Good catch, thanks for the vuex-module-decorator lib btw ;)
