### ISSUE TITLE
Dice rolls too slow

### ISSUE THREAD

**Issue by notklaatu** [Kruptein/PlanarAlly#1190]
In Planar Ally, a dice roll can take 6 to 10 seconds to complete. It's fun to watch the die bounce around the first few times you do it, but 6 seconds for a dice roll can really slow a game down.

Is it possible to get a fast version of a dice roll? Like, click a button → get a number. Dice animation optional, to be honest. It should only take a second at the most.

**Comment by Kruptein** [comment]
The plan is to offer text-based rolls as well.

The animation is using a physics-based approach to simulate real world dice rolls, and tweaking the parameters on how these behave has turned out to be more work than I expected, hence why they currently can take some time to settle in some cases.

**Comment by notklaatu** [comment]
Great to hear that it's a planned feature. I'll close this feature request, knowing that it's on the roadmap already.

Thanks again for an amazing app.
