### ISSUE TITLE
Unable to create new session

### ISSUE THREAD

**Issue by poltergeisha** [Kruptein/PlanarAlly#120]
As of the latest release, I am unable to create a new session as a new user.

**Comment by poltergeisha** [comment]
It seems that if you log out and then back in it will work.

**Comment by Kruptein** [comment]
Is this something you can reproduce?

**Comment by AJAnderson** [comment]
I experienced exactly the same thing with the same action fixing it.

**Comment by Kruptein** [comment]
thanks for the feedback, I'll look into it.

**Comment by Kruptein** [comment]
I can indeed also reproduce this issue, expect a fix later today.

**Comment by Kruptein** [comment]
This is fixed in 0.14.2

**Comment by poltergeisha** [comment]
Sorry for making an issue and then ghosting, had some family issues come up.

**Comment by Kruptein** [comment]
Hey absolutely no problem at all, I'm glad you reported the issue and I hope all is well with your family.
