### ISSUE TITLE
[BUG] Adding shapes to the map does not successfully submit to the server

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1200]
**Describe the bug**
I am unable to add tokens to any map as GM. The server outputs this as error
```
2023-02-20 09:19:51,926 - CRITICAL - Uncaught async exception "ApiAssetRectShape" object has no field "index" (logs.py:38)
Task exception was never retrieved
future: <Task finished name='Task-5932' coro=<AsyncServer._handle_event_internal() done, defined at .../server/venv/lib/python3.11/site-packages/socketio/asyncio_server.py:522> exception=ValueError('"ApiAssetRectShape" object has no field "index"')>
Traceback (most recent call last):
  File ".../server/venv/lib/python3.11/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../server/venv/lib/python3.11/site-packages/socketio/asyncio_server.py", line 558, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File ".../server/src/auth.py", line 49, in wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../server/src/api/socket/shape/__init__.py", line 69, in add_shape
    data.shape.index = layer.shapes.count()
    ^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 358, in pydantic.main.BaseModel.__setattr__
ValueError: "ApiAssetRectShape" object has no field "index"
```

**To Reproduce**
1. Open a map and add a shape
2. Check the server logs for error

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 109.0.1, ungoogled-chromium 109.0.5414.119
 - Version: dev branch commit [1f5d574](https://github.com/Kruptein/PlanarAlly/commit/1f5d5740f1bb9b6d463ad224828b1f35e040e0a4)

**Additional context**
The shapes appear to behave as normal on the client. It's only after refreshing my changes that I noticed nothing persisted.

**Comment by Kruptein** [comment]
Thanks for the report!

You might be seeing some more errors in the coming days due to a big PR I did that changed some internals. Your input is very helpful, but if you need something stable for an actual session, you might have to revert to an earlier commit.

**Comment by rexy712** [comment]
Yeah I'm switching back to the new release for the time being. Wanted to make sure this was known since it makes things unusable currently. I'll wait a bit before returning to dev branch.

**Comment by Kruptein** [comment]
Makes sense, sorry for the inconvenience 🙏
