### ISSUE TITLE
[BUG] Labels cannot be deleted

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1202]
**Describe the bug**
When attempting to delete a label from within the Edit Shape>Extra>Labels menu, the client shows that the label is removed. But on the server, an error comes up in the logs:  
`WARNING - <user> tried to delete a non-existing label. (label.py:50)`  
Refreshing the webpage shows the label is indeed still there.

**To Reproduce**
1. Create a Label via Edit Shapes>Extra>Labels menu
2. Delete the label
3. Refresh the page, navigate back to the menu.
4. Label has reappeared.
5. Server logs show the label failed to delete.

**Expected behavior**
The label should be deleted.

**Screenshots**

https://user-images.githubusercontent.com/2442544/220191325-beb510c2-5cdd-44f4-82a7-7d6b207f6873.mp4

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 109.0.1, ungoogled-chromium 109.0.5414.119
 - Version: 2023.1

**Additional context**
This also makes the filter button show up which is what clued me in to the issue existing. I was testing out what labels did, then deleted them. I was expecting the filter button would disappear after deleting them and it still remained.

**Comment by Kruptein** [comment]
This is actually fixed on dev by the API rework.
