### ISSUE TITLE
[BUG] Templates do not include 'Display on Token' state for trackers

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1204]
**Describe the bug**
When adding an asset to the map using a template, the resulting shape does not include the 'Display on token' state for any tracker if it was checked when saving the template. This is also true of the toggled state of auras. Not sure if this is intentional or not, but I feel like it would be good to include at least the 'Display on Token' state so that DMs don't have to enable health bars manually each time they add a token.

**To Reproduce**
1. Create a shape with an asset.
2. Add a tracker with 'Display on token' checked
3. Save Template
4. Add a new shape via the same asset, select the template when prompted
5. The new shape does not have the tracker set to 'Display on token'

**Expected behavior**
I expected that the trackers would inherit the 'Display on token' state from the template.

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 109.0.1, ungoogled-chromium 109.0.5414.119
 - Version: 2023.1

**Comment by Kruptein** [comment]
It's not intentionally missing, these features (aura toggle, display on token) are new compared to the introduction of templates and I hadn't thought about adding them to the templates at that time.
