### ISSUE TITLE
Unable to select anything

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#121]
I created a session, uploaded some assets (map backgrounds), then added them to the grid. I can't select them at all.

I also don't get a drag select box when using the select tool.

**Comment by Kruptein** [comment]
That's not good, can you see if there are any errors in the server log or in the brower's developer console ? (You can see this when pressing F12 and there should be a console tab).

Can you also tell me which version you are using ?
I assume a refresh does not help.

**Comment by schemen** [comment]
@Kruptein planarally.dndbox.com is running on the latest tag (0.14.0). I've noticed this as well. Server side, there are no errors in the logs. I have not yet checked client side.

Other than that, this has greatly improved performance.

**Comment by Kruptein** [comment]
I've just checked myself, and I can confirm this behaviour.  I'm currently at work, but I'll try to fix this in my lunch break.

**Comment by Kruptein** [comment]
I've release 0.14.1 which should fix this problem.

**Comment by schemen** [comment]
I can confirm this fixed the problem.
