### ISSUE TITLE
[FEAT] When teleport trigger changes floors, move the player's view to the new floor

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1213]
**Is your feature request related to a problem? Please describe.**
There is a setting in DM settings>Varia and Location settings>Varia called 'Move player(s) when a token they own changes location'. This moves players automatically to a new location as expected, including by a teleport zone. It also moves player's viewports when a teleport zone takes their token to a different floor in the same location. However it doesn't change which floor their view is looking at, resulting in them often losing all vision until they manually change the floor to where the teleport zone leads.

The checkbox in the settings specifically says 'when... they change **location**', so it could be that it isn't meant to work between floors. In which case this is more of a bug that the viewport moves when teleporting between floors.

**Describe the solution you'd like**
I think that it would be good to automatically change the floor the player is on under these circumstances. If the 'Move player' checkbox is not active for a location, then of course it would leave their view as is.

**Comment by Kruptein** [comment]
I actually see this as a bug, as you'll see in my description of the fix PR, that this behaviour was actually intended from the start.
