### ISSUE TITLE
Dropping an asset onto the map redirects me to "static.com"

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#122]
Not sure if this is something funky on my computer, but I've re-created this 3 times. If I upload a file to use as an asset, and then drop it onto the map, the server redirects me to static.com which is some kind of advertising page.

**Comment by Kruptein** [comment]
Hey which browser is this behavior on, this was caused on Firefox in the
past and may have slipped in again

**Comment by AJAnderson** [comment]
Yep, it was in Firefox

**Comment by Kruptein** [comment]
This is fixed in the dev branch
