### ISSUE TITLE
Drawing tool improvements

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#124]
Drawing tools are a little non-intuitive

- There's no way to draw a simple line (square) without snapping to grid, without also disabling the whole grid.
- Something similar to the polygon tool (chained line segments) that doesn't fill in between the line segments would be ideal for quickly tracing walls.
- Related to the above, it would be good to provide a way to draw in things that are set to block light and vision automatically.

**Comment by Kruptein** [comment]
Hey, this is possible but just poorly documented i suppose.

Regarding draw tools, you can change border and fill colour as well as
opacity for every shape. So you can set the full colour to be transparent

The fow layer automatically applies the vision and movement blocking
settings to drawn shapes.as that layer is dedicated to shadows and vision

**Comment by AJAnderson** [comment]
Thanks for the tip on the FoW layer, I thought I had tried that. Did you mean from your previous message that it was possible to do a multiline shape that's not filled?

I experimented with the polygon tool opacity, but the auto complete type behaviour results in unhelpful occlusion shapes being created

**Comment by AJAnderson** [comment]
Related: Even when free drawing, occlusion is happening in a weird way, if I draw two sides of a square without taking my mouse off, the whole area enclosed by the rest of the uncompleted square occludes light. The more intuitive result is that the drawn lines themselves block light.

**Comment by Kruptein** [comment]
And yes it' possible to have a multiline shape not being filled, as can be seen below.

![image](https://user-images.githubusercontent.com/1814713/52041500-e7468480-253a-11e9-8d78-cb06799cf0e0.png)

Something you're probably having issues with is that the defaukt vision/lighting system does not support lines that are not axis aligned.  I have however recently introduced a new vision system that supports any type of polygon and that's also the reason I've added the polygon tool.
You can use this new vision mode by changing the vision mode to triangle in the dm options menu.

Does that solve your autocomplete occlusion issue?

**Comment by Kruptein** [comment]
Also the free draw tool has not been propely tested with vision/lighting, so it might behave funky on the fow layer.

**Comment by Kruptein** [comment]
I'm gonna close this for now, feel free to reopen if it's not solved.
