### ISSUE TITLE
Hide shapes with enabled invisibility  in fake-player mode

### ISSUE THREAD

**Issue by netdem** [Kruptein/PlanarAlly#1240]
I share my screen with others in fake player mode. And they all see hidden tokens. Maybe make some option for the admin that hides them?
![image](https://user-images.githubusercontent.com/11818965/226121970-d1f7f252-fa62-4eeb-8abd-321612b6f3ec.png)

**Comment by Kruptein** [comment]
I have a fix for something related, that I think will also address this, locally. I'll see if I can get around to it today and otherwise it will be out tomorrow
