### ISSUE TITLE
Rulers drawn by players get stuck on DM scrren

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#125]
As per issue title, drawing rulers in the player view results in them being rendered in the DM view and stuck there. They don't appear to be selectable on any layer.

Checking server log shows an error in line 198 of shape.py, a keyerror for the check "if user.name not in shape["owners"]:"

**Comment by Kruptein** [comment]
Got a similar bug report from a friend in person yesterday, seems like I broke the ruler in a recent commit.

**Comment by Kruptein** [comment]
I think I've solved the issue, I'm going to merge it into develop in about an hour.
