### ISSUE TITLE
[BUG] Bold text in annotations is not bolded in firefox

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1255]
**Describe the bug**
When using markdown bold tag in the annotation text, firefox does not render the result as bolded. The text is bolded in chromium browsers.

**To Reproduce**
1. Create a shape
2. Add an annotation with content `**Bold**`
3. Hover mouse over the shape to see the annotation
4. Text is not bolded.

**Expected behavior**
Text in the annotation should be bolded as in chromium browsers.

**Screenshots**

firefox:
![firefox](https://user-images.githubusercontent.com/2442544/227796158-be4ce033-5b8e-4b3b-aa23-6f8fd26624ed.png)

<br/>
<br/>

ungoogled-chromium:
![ungoogled-chromium](https://user-images.githubusercontent.com/2442544/227796163-2107d3bc-c0a0-4035-ad02-872ff817eff2.png)

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 111.0
 - Version: dev branch commit [5a88106](https://github.com/Kruptein/PlanarAlly/commit/5a88106143265c4c05cd27f6f0be6bbd7574b96e)

**Comment by Kruptein** [comment]
The markdown rendering is done by another library, so this one I can't fix directly myself.
The markdown lib we're using has been archived by now in favor of another one, which does not support the feature PA uses (dynamic md rendering), which makes the entire thing a bit messy.

I probably need to set aside some time to look into how I want to address this. One option is to bring in `markdown-it` myself directly.

**Comment by develroo** [comment]
Seems to be a repeat of [my issue](https://github.com/Kruptein/PlanarAlly/issues/793) which we thought was fixed. But guess not. 

Subscript and Superscript would be a nice addition, though.

**Comment by Kruptein** [comment]
Turns out it wasn't a fault in the library
