### ISSUE TITLE
FoW walls appear to have a hole when the token approaches from the left

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#126]
Example image shown, the view going from the token through the wall to the right tracks vertically with the token as it moves. I.e. the token seems to have some kind of god view looking towards the right.

**Comment by Kruptein** [comment]
Hey all the issues are absolutely welcome.

Can you show me the fow elements without the token piercing through them?

Most client code is written in typescript and can be found in the client/ folder, the server code is python and can be found in the server/ folder, but is mostly related to communication/authentication/authorization and saving the data, so it does not contain much game logic.

**Comment by Kruptein** [comment]
Oh yeah most definitely, if you need something that does not fit a rectangle or circle, use the multiline/polygon tool instead (but you do need the triangle vision mode active in the dm options in that case)
