### ISSUE TITLE
[BUG] Is Invisible toggle does not function until players reload the page

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1262]
**Describe the bug**
The 'Is invisible' toggle for shapes only makes the shape invisible after reloading the page. It also does not make things become visible when unchecking the box until a page reload.

**To Reproduce**
1. Create a Basic Token
2. Check the box in shape properties > Is invisible
4. Players can still see the shape.
5. Have players reload the page. They can not see the shape anymore.

**Expected behavior**
The Is invisible toggle should take effect when enabling/disabling rather than after a reload.

**Screenshots**

GM on left, normal player on right.

https://user-images.githubusercontent.com/2442544/232551878-7fa247ae-98bd-40e8-904d-3d485f51bf3b.mp4

**Desktop:**
 - OS: gentoo linux
 - Browser: firefox 111.0.1, ungoogled-chromium 112.0.5615.49
 - Version: dev branch commit [90fb740](https://github.com/Kruptein/PlanarAlly/commit/90fb740c0a5fc5a56d16390d8a88a5712b7fa6b2)

**Comment by Kruptein** [comment]
This is very funny timing wise, because this exact bug happened in a game session I played in this weekend as well.

We also "resolved" it by refreshing, but I hadn't looked into what caused it.
So thanks for logging this, seems like the message is not getting passed along to active connections.

**Comment by Kruptein** [comment]
Also sorry if it ruined something :C given that it relates to invisible stuff
