### ISSUE TITLE
"Record" token's movement in the FoW layer

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#127]
It would be amazing if the movement of a token could be "recorded" in the FoW layer so that the maps fills in just via the actions of the players.

**Comment by Kruptein** [comment]
Hm interesting use case, I'll need to look into how easy it is to implement this.

**Comment by Kruptein** [comment]
Closing this in favour of #317 as it has some more interesting discussion ongoing.
