### ISSUE TITLE
[FEAT] Allow sharing assets between DMs

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1298]
I've been the long term GM for my group but another member has recently started to host a game for us. I had set up a bunch of reusable assets with templates all set up that I figured they could use (eg goblins, kobolds, merchants, etc). We discovered that they can't see any of the assets I've uploaded and I can't see any they upload.

Not being able to see some assets makes sense, like hiding the appearance of a boss token for example. But common enemies or townsfolk would be nice to share.

**Describe the solution you'd like**
Allow assets to be shared amongst multiple people, much like how tokens can be shared when in-game. Have edit and read permissions perhaps. It'd be a rather complex solution, but it would be really nice for the GMs to be able to share and not reduplicate work.

**Comment by 10leej** [comment]
#1287 might be a solution for this

**Comment by rexy712** [comment]
Ah I forgot to update before making this issue, apologies. I'll try it out with the newest dev branch tomorrow and see if this is still applicable

**Comment by Kruptein** [comment]
It should still be applicable. Characters don't address sharing assets between players, they are about specific shapes (i.e. instances of some asset).

Sharing assets with fellow players makes sense. The actual logic implementation shouldn't be a lot of work, I'm mostly thinking about how I want to approach it from the UI side of things.

**Comment by 10leej** [comment]
> It should still be applicable. Characters don't address sharing assets between users, they are about specific shapes (i.e. instances of some asset). A character should eventually allow a player to make their character with the correct art and provide that to the DM so they no longer have to upload it, but this issue talks about more general sharing of assets that are campaign agnostic.
> 
> Sharing assets with fellow players makes sense. The actual logic implementation shouldn't be a lot of work, I'm mostly thinking about how I want to approach it from the UI side of things.

Give players access to the campaign's Asset Manager and have a basic ACL system?

**Comment by Kruptein** [comment]
> Give players access to the campaign's Asset Manager and have a basic ACL system?

The thing is that it's not related to a specific campaign, there is not even a concept of a campaign's asset manager. Assets belong to a User and you always see _all_ your own assets when you're in a campaign. [^1]

What they want is to share some of the assets they use with someone else, whether they are both members of the campaign the assets are going to be used in or not.

[^1]: It might be an interesting side discussion to have a distinction between campaign related assets and all assets, but that's ultimately for a different issue/ticket

**Comment by dthv** [comment]
> Assets belong to a User and you always see _all_ your own assets when you're in a campaign.

What about ability to "share" Assets? User could want to share their assets with (1) specific users, (2) all users of a specific campaign, (3) all DMs, (4) all DMs for a specific campaign.

Slightly related, but maybe an issue for another, well, issue: Sharing with yourself, i.e. ability to configure assets to only be shown in specific campaigns. Could reduce clutter. I *love* reducing clutter. :)

**Comment by dthv** [comment]
In addition: Users could want to share assets also with (5) public.

Mirroring the choices for filtering own assets, users could have the same matrix to configure seeing assets of (a) specific users (all applicable of (1-5)), (b) shared to them (mirroring (1)), (c) shared to a specific campaign (mirroring (2) and (4)), (d) shared to DMs (mirroring (3)), and (e) all (esp. mirroring (5)).

Thats already pretty complex. /o\
