### ISSUE TITLE
[FEAT] Show who rolled what in the log

### ISSUE THREAD

**Issue by Oreolek** [Kruptein/PlanarAlly#1328]
The dice log is too terse and doesn't show who rolled what without hovering over each roll. I constantly need this info

Example: `[user]: 1d6`

**Comment by Oreolek** [comment]
i'm using the docker image so can't just use code patches or mods

**Comment by Kruptein** [comment]
I do have some things planned for the dice roller, but they are not progressing fast.

That said, @SuikaXhq why don't you submit a PR with your changes? It would be a nice help for some people.
