### ISSUE TITLE
Grant DM access to session

### ISSUE THREAD

**Issue by sdaugherty** [Kruptein/PlanarAlly#133]
I have a co-dm - it would be nice to be able to grant them access to my session/maps/assets, or to even to have a helper managing things behind the scenes

**Comment by Goury** [comment]
I'd like to propose to implement an access management system for that.

**Comment by ZachMyers3** [comment]
Similar to #197, closable?

**Comment by Kruptein** [comment]
This can indeed be closed, given that #197 properly tackles the concept of having multiple DMs, but that should be feasible.
