### ISSUE TITLE
[BUG] It is possible to guess the monster location in the dark by the public description

### ISSUE THREAD

**Issue by Oreolek** [Kruptein/PlanarAlly#1330]
If you set the description to an asset, place it out of DM layer and make it public, the players can guess where it is and what it is by hovering over the mouse and reading the description, even if the asset is in fog of war.

(Version: 2023.3.0)

I understand why but it's still not that obvious.

**Comment by develroo** [comment]
Don't make it public then. There is a check box for it. 

![pa-example-1](https://github.com/Kruptein/PlanarAlly/assets/7777993/0f09eb9c-ecb6-43a5-8598-1248598b6ff9)
