### ISSUE TITLE
view as player toggle

### ISSUE THREAD

**Issue by sdaugherty** [Kruptein/PlanarAlly#135]
As a DM, I should be able to view my map as if I'm the player, in order to quickly check that line of sight, dynamic lighting, and fog of war are working as intended.

**Comment by Kruptein** [comment]
This is something I've started work on earlier, but had to postpone for some other features.

So this one should be implemented soon-ish

**Comment by Kruptein** [comment]
Finally had some time to tackle this.

I've added a Fake Player option to the DM Settings, which when selected will make the game assume for most intents that you're no longer a DM.  With the 'vision' tool in the bottom right side you can select which token(s) you want to represent if you use the token based vision system.

If you have time and still are interested in this project, feel free to try it out :) It's on the dev branch.

**Comment by Kruptein** [comment]
It has been merged into the latest release.
