### ISSUE TITLE
hex grid mode

### ISSUE THREAD

**Issue by sdaugherty** [Kruptein/PlanarAlly#136]
Hex grid maps would be useful, especially for overland travel

**Comment by aronwk-aaron** [comment]
any update to this?
would love to use this tool for lancer, which requires a hex grid

**Comment by Kruptein** [comment]
The main problem is that I believe there are some areas that depend on a rectangular grid (e.g. snapping and movement).

I could probably very easily add a hex grid purely render wise, but there might be some functionality lacking or even broken.  So if that's something you find worth I can probably whip that out pretty quick, otherwise I'm gonna need to take some more time for this.

**Comment by 10leej** [comment]
disable grid snapping when enabling hesex in the short term?

**Comment by dthv** [comment]
I actually do think that grid snapping is, in principle, possible with hex-grids. A "snap center to center" should be computable comparably easy with offsets.

On a sidenote: https://www.redblobgames.com/grids/hexagons/ This is the best resource on implementing hexagonal grids in games that I know – hope it's useful for someone here.

**Comment by Kruptein** [comment]
oh I wasn't claiming it's impossible, it just takes some time to make sure it all works.

**Comment by Kruptein** [comment]
To gather some insight in people using hex grids.  Is there a common preference between the two ways of rendering hexagons (flat vs point) ? or do most systems offering hex grids offer both?

**Comment by dthv** [comment]
I'd say that rendering flat vs. point is primarily a visual choice. It does not matter, technically, as the map is simply rotated, as a whole, by 30°. It's also hard to say whether there's a common preference. Traveller, one of the most famous systems that uses hex-grids, seems to use flat-top hex-grids most of the time (though I could *swear* I've seen some point-top maps…), as does Battletech to my knowledge, while e.g. the Unearthed Arcana Supplement for D&D 3.5 uses point-tops, as did the Forgotten Realms Campaign Setting Boxed Set of AD&D (indicating that this would probably the preference of D&D; I have no idea about any D&D system later than 3.5).

It would actually be preferable to being able to switch between the grids. It will involve doing som math a bit differently, but not impossible to achieve.

**Comment by CalebKoch** [comment]
If the grid size is set to 5 ft, should that be distance from the center of one hex to the center of an adjacent hex, or the length of one side? 

#549  seems to be assuming it will be the length of a side, unless I am misunderstanding the math there.

**Comment by Kruptein** [comment]
good question, I don't know what the most common interpretation is in hex based systems (or dnd for that matter). I feel like both can be argued for.

**Comment by dthv** [comment]
As the numbers differ by factor 2, one could implement one and simply document it with the comment that one needs to halve/double the grid size to get the effect of the desired interpretation.

Yet, I want to argue for the distance from the center of one hex to the center of an adjacent hex. With typical square grids, we count the *diameter* and not the radius. The length of a side of a hexagon is equal to its *radius*, not the *diameter*.

This is consistent with the D&D interpretation at least in 3.5e (cf. *Unearthed Arcana*, p. 128):
> The primary advantage of this variant is that it eliminates the “every other square counts double” rule for diagonal movement, because it eliminates diagonal movement. Characters simply move from hex to adjacent hex, changing direction as they like. To determine the distance between two hexagons, just count hexes by the shortest path (in most cases, there will be a number of equally short paths).

There is no change in the interpretation of "one field = 5ft", meaning one has to move 5ft from one hex to another. Regardless whether one moves from center to center or from one side to the opposite side of an adjacent hex, this would mean that one moves 2x the radius or 1x the diameter (both equal) to get from one hex to another.

**Comment by Kruptein** [comment]
makes sense, I would personally also rule in favor of the center to center distance being 5ft.

**Comment by dthv** [comment]
Actually, it doesn't, 'cause I misread the graphic I quickly looked up. In my defense: Me and geometry has been a while. (No. That's not a valid excuse.)

I argued with the wrong `r`. ;)

With a hexagon, the *excircle*'s radius equals the side of a hexagon, while the distance from one center to an adjacent hexagon's center would be two times the *incircle*'s radius (as you move over the sides, so to say). Thus, it's not a factor of 2 between the two measurements, but one of sqrt(3)/2 (or about 0.866).

Sorry. :-/

**Comment by Kruptein** [comment]
Hey no need to feel sorry, but the point still stands that the center to center is the most favorable distance then right
