### ISSUE TITLE
Submit Docker Image to Docker Hub

### ISSUE THREAD

**Issue by ThatCarterMcBride** [Kruptein/PlanarAlly#139]
This would allow users to pull the Docker image from the official Docker registry without having to clone the repo and build it locally. 
I would do it myself, but it's better if @Kruptein does it, so that he has ownership over it and links the repo officially. That enables automatic builds on release and thus less maintenance for a side project.
I'm happy to help out however necessary to get this done. The place to start is [here](https://cloud.docker.com/repository/list).
In the meantime, I've forked this repo and [submitted it to the Docker Hub](https://hub.docker.com/r/thatcartermcbride/planarally), which I will happily deprecate when the official repo is added. The goal is to be more up-to-date than [the other Docker image, which hasn't been updated in 6 months](https://hub.docker.com/r/zerologic/planarally).

**Comment by Kruptein** [comment]
Hey thanks for doing this, I wasn't aware there even was an image on dockerhub!

I'll try to look at this myself and provide both master and develop images in the near future.

**Comment by Kruptein** [comment]
I believe I've configured it now to automatically build on https://cloud.docker.com/repository/docker/kruptein/planarally

**Comment by ThatCarterMcBride** [comment]
Yep that looks good. Thank you!
I'll submit a PR later to update the documentation to include instructions. This should make it a lot easier for some people to run it. I personally run a home server on Docker, where I just define all the services in a 'docker-compose.yml' file to keep management simple.

**Comment by Kruptein** [comment]
Nice, yeah I haven't made the move to docker for my personal stuff yet, but I should consider it ;)

Thanks for looking at the docs, they are still pretty lacking in general sadly.
