### ISSUE TITLE
[BUG] Note icon on shape can be drawn over by its parent shape

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1406]
**Describe the bug**
Looking into the code to improve my implementation of the invisibility marker, I saw that note icons are currently drawn as unique shapes on the same layer as the base shape they attach to. So I thought that they could be drawn over by using the base shape's  'Move to front' and 'Move to back' context menu items, and sure enough they can.

The note icon can also be drawn over other shapes that are in the foreground compared to the base shape, but behind the note icon's shape. I believe that if a shape is in the foreground compared to the base shape, it should also always be in front of the note icon.

**To Reproduce**
1. Create a rectangle.
2. Add a note and mark the note to show icon on shapes.
3. Move the rectangle to front using the context menu.
4. Note icon is covered by the rectangle.

**Expected behavior**
The note icon should always be in the foreground compared to the shape it is attached to.

**Screenshots**

https://github.com/Kruptein/PlanarAlly/assets/2442544/72891b40-8370-40ed-89a2-24b000501390

**Desktop:**
 - OS: gentoo linux
 - Browser: ungoogled-chromium 121.0.6167.160, firefox 122.0.1
 - Version: dev branch commit [a44fd4d](https://github.com/Kruptein/PlanarAlly/commit/a44fd4d95920a5b98146a58cd1ddaf916d7a4ad0)

**Comment by Kruptein** [comment]
Ah good catch, this one I wasn't aware of yet, but makes sense.
