### ISSUE TITLE
Support uploading and adding a new asset by dropping into layer

### ISSUE THREAD

**Issue by PigheadedGnu** [Kruptein/PlanarAlly#142]
Dragging an image from your local machine onto a map layer should upload it as an asset and add it to the layer

**Comment by Kruptein** [comment]
It's been somewhat deliberately not possible for now.  Reason being that there is a dedicated assets tool in which you can freely manage your assets in folders etc (you can also drag and drop here)

These assets are then available in the in-game tool using the sidebar.

That said I can understand if this is a bit too involved if you just want an image on your board.

If a new image were to be dropped on a map, should it appear somewhere in your library? or would you always assume it's a one off thing.

**Comment by PigheadedGnu** [comment]
I would probably expect it to be added to a `Dropped Assets` folder or something similar. Can always be rearranged or removed from there.

**Comment by Kruptein** [comment]
Seems fine for me, It's on my roadmap anyway!

**Comment by Kruptein** [comment]
It's been ages, but this is now resolved with #1275
