### ISSUE TITLE
[FEAT] Make pop out modal so they can be dragged outside of the browser window. 

### ISSUE THREAD

**Issue by develroo** [Kruptein/PlanarAlly#1426]
The title really says it all, because dragging notes onto another desktop is quite common so they are not cluttering the game screen.

I am pretty sure it is doable because of this [Stackoverflow post](https://stackoverflow.com/questions/65022204/make-a-popup-modal-dialog-movable-draggable-once-it-has-appeared) but unsure how much effort it woudl take ?

As it stands, dragging a note outside of the browser window does sorta pin it to the side but it is still no great. 

[Screencast from 2024-04-05.webm](https://github.com/Kruptein/PlanarAlly/assets/7777993/b540a581-f7f5-4e20-a87e-1d656f610981)

Anyway, just a thought.

**Comment by Kruptein** [comment]
> I am pretty sure it is doable because of this [Stackoverflow post](https://stackoverflow.com/questions/65022204/make-a-popup-modal-dialog-movable-draggable-once-it-has-appeared) but unsure how much effort it woudl take ?

I don't immediately see anything in that so post that actually offers drag out of the window support :D

That aside, my original vision did include the ability to fully popout notes from the page in a separate window as well as offering an option to have the note manager open in a separate window or even phone.

I do also see that the action bar gets funky when only half the screen is used, that's also something I need to clean up.

**Comment by develroo** [comment]
Oh they gave javascript and html examples?


```
//Make the DIV element draggagle:
dragElement(document.getElementById("mydiv"));

function dragElement(elmnt) {
  var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
  if (document.getElementById(elmnt.id + "header")) {
    /* if present, the header is where you move the DIV from:*/
    document.getElementById(elmnt.id + "header").onmousedown = dragMouseDown;
  } else {
    /* otherwise, move the DIV from anywhere inside the DIV:*/
    elmnt.onmousedown = dragMouseDown;
  }

  function dragMouseDown(e) {
    e = e || window.event;
    e.preventDefault();
    // get the mouse cursor position at startup:
    pos3 = e.clientX;
    pos4 = e.clientY;
    document.onmouseup = closeDragElement;
    // call a function whenever the cursor moves:
    document.onmousemove = elementDrag;
  }

  function elementDrag(e) {
    e = e || window.event;
    e.preventDefault();
    // calculate the new cursor position:
    pos1 = pos3 - e.clientX;
    pos2 = pos4 - e.clientY;
    pos3 = e.clientX;
    pos4 = e.clientY;
    // set the element's new position:
    elmnt.style.top = (elmnt.offsetTop - pos2) + "px";
    elmnt.style.left = (elmnt.offsetLeft - pos1) + "px";
  }

  function closeDragElement() {
    /* stop moving when mouse button is released:*/
    document.onmouseup = null;
    document.onmousemove = null;
  }
}
```
```
#mydiv {
  position: absolute;
  z-index: 9;
  background-color: #f1f1f1;
  text-align: center;
  border: 1px solid #d3d3d3;
}

#mydivheader {
  padding: 10px;
  cursor: move;
  z-index: 10;
  background-color: #2196F3;
  color: #fff;
}
```
```
<h1>Draggable DIV Element</h1>

<p>Click and hold the mouse button down while moving the DIV element</p>

<div id="mydiv">
  <div id="mydivheader">Click here to</div>
  <p>Move</p>
  <p>this</p>
  <p>DIV</p>
</div>
```


I thought they might help figure it out?

**Comment by Kruptein** [comment]
that's just dragging within the page. You can do that already.

What you want is dragging to another page/monitor.

**Comment by develroo** [comment]
> that's just dragging within the page. You can do that already.
> 
> What you want is dragging to another page/monitor.

Yeah. Basically, it makes it easier on a multi-monitor setup.

**Comment by develroo** [comment]
Sorry to come back to this, but I just checked out Fvtt's popout module and that manages to open a separate browser window which can be moved to any desktop or screen I want. It uses javascript and seems pretty short. 

Repo is here

https://github.com/League-of-Foundry-Developers/fvtt-module-popout

popout.js is less than 1000 lines. Maybe you can take a look at how they do it?

**Comment by Kruptein** [comment]
I never said I didn't want to do the popout, it just takes more time.

Also 1000 lines is a lot of code, that's not "pretty short"

**Comment by develroo** [comment]
> I never said I didn't want to do the popout, it just takes more time.
> 
> Also 1000 lines is a lot of code, that's not "pretty short"

Hehe.. well I am from the Linux world, so 1000 lines seems small to me. But no matter. 


FWIW, it seems the heart of the module is this. 

```
  createDocument() {
    // Create the new document.
    // Currently using raw js apis, since I need to ensure
    // jquery isn't doing something sneaky underneath.
    // In particular it makes some assumptions about there
    // being a single document.
    // We do this before opening the window because technically writing
    // to the new window is race condition with the page load.
    // But since we are directing to a placeholder file, it doesn't matter other than for UX purposes.
    const html = document.createElement("html");
    // We copy any manually set styles on the root element to ensure that css variables are preserved.
    html.style.cssText = document.documentElement.style.cssText;
    const head = document.importNode(
      document.getElementsByTagName("head")[0],
      true
    );
    const body = document.importNode(
      document.getElementsByTagName("body")[0],
      false
    );

    for (const child of [...head.children]) {
      if (child.nodeName === "SCRIPT" && child.src) {
        const src = child.src.replace(window.location.origin, "");
        if (!src.match(/tinymce|jquery|webfont|pdfjs|prosemirror|common/)) {
          child.remove();
        }
      }
    }
```


Dunno is that helps or not. As I said, not really a js developer.
