### ISSUE TITLE
new to github and i don't know how to open this, wouldn't mind some help.

### ISSUE THREAD

**Issue by IllegalMobster** [Kruptein/PlanarAlly#145]
the title says it all.

**Comment by Kruptein** [comment]
Hi, no problem, I've got a lot of work still in regards to documentation.

I've a general documentation site [here](https://planarally.readthedocs.io/en/dev/getting_started.html) and there is some information regarding installation [here](https://planarally.readthedocs.io/en/dev/installation.html).

If that's still unclear feel free to comment again

**Comment by Kruptein** [comment]
Hi again,

I noticed there was an issue with the windows builds.
I've fixed that in the latest release.

You can find these [here](https://github.com/Kruptein/PlanarAlly/releases)
