### ISSUE TITLE
[BUG] Change color of new campaign creation selection highlight to help visibility

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#1466]
I have "Import a game" highlighted, however this could be technically difficult to see due to coloring. Can we change that pinkish red to a more contrasting color? Maybe white to match with the standard font.

![image](https://github.com/user-attachments/assets/dcfacde9-5798-44c0-9f2c-70b04b1fab36)

**Comment by develroo** [comment]
Hmmm is not having a lighter border distinct enough ? I mean, I guess the border could be a different colour like yellow or something. 

The code seems to be in `CreateSwitcher.vue` line 115 in `client/src/dashboard/games`

```
            &.selected {
                border-color: rgba(219, 0, 59, 1);
            }
```

You could change it to  yellow with `rgba(241, 251, 3, 1)` and see if that appeals to you?


![image](https://github.com/user-attachments/assets/937ef9ff-479c-4fa8-80a7-93e36247ab89)

**Comment by 10leej** [comment]
> Hmmm is not having a lighter border distinct enough ? I mean, I guess the border could be a different colour like yellow or something.
> 
> The code seems to be in `CreateSwitcher.vue` line 115 in `client/src/dashboard/games`
> 
> ```
>             &.selected {
>                 border-color: rgba(219, 0, 59, 1);
>             }
> ```
> 
> You could change it to yellow with `rgba(241, 251, 3, 1)` and see if that appeals to you?
> 
> ![image](https://private-user-images.githubusercontent.com/7777993/376607926-937ef9ff-479c-4fa8-80a7-93e36247ab89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjM4MTAsIm5iZiI6MTcyOTAyMzUxMCwicGF0aCI6Ii83Nzc3OTkzLzM3NjYwNzkyNi05MzdlZjlmZi00NzljLTRmYTgtODBhNy05M2UzNjI0N2FiODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMjAxODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWEzMzliY2E3OTU5NmU4YzczMDI1ZTY2ZDA2OWNkNjY4N2U5ZDNmNDg3MmYzMWMxZTkxY2ZiNGRkY2FiMjRhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KCHv_V3QQs2KurcRqIBYTlMdSIc-oC0HMGzDZ29fXVE)

Personally I'd stick with the current colors for uniformity which is why I recommended white
