### ISSUE TITLE
Upgrading to 0.17.0 removes all users/logins

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#147]
Heya!

I just built and upgraded to 0.17.0 (From 0.15.1) and I was not able to log in anymore. I was able to create the same user and the account appeared empty. Do I need to upgrade to 0.16.0 first?

Any change in the DB schema?

No Errors have appeared anywhere.

**Comment by schemen** [comment]
Ah, building 0.16.0 and trying to launch leads to the following error:

```
Save format 16 does not match the required version 14!
Attempting upgrade
Backing up old save as /usr/src/app/data/planar.sqlite.16
Starting upgrade to 17
No upgrade code for save format 16 was found.
Traceback (most recent call last):
  File "/usr/src/app/save.py", line 188, in check_save
    upgrade(constants.save_version)
  File "/usr/src/app/save.py", line 156, in upgrade
    raise Exception(f"No upgrade code for save format {version} was found.")
Exception: No upgrade code for save format 16 was found.
ERROR: Could not start server

```

**Comment by Kruptein** [comment]
Very strange, I managed to update just fine on my home server which also had to upgrade from 0.15.X.
The first line of your paste is also completely wrong. It claims to need version 14 which is older instead of newer.
I'm investigating

**Comment by Kruptein** [comment]
Be sure to save your original save file somewhere safe!

**Comment by Kruptein** [comment]
In version 16 the filename of the save changed from planar.save to planar.sqlite perhaps ?
Modify your save filename in your server config.
That would explain why the first run gave no errors, as it just created a new save file with the new naming scheme and the revert errors because the new save is a newer version

**Comment by schemen** [comment]
I also noticed this. I will check if renaming the file to planar.sqlite helps!

**Comment by Kruptein** [comment]
I expect this to be the cause, it was a change in the docker server config.
As a matter of fact docker images are automatically built nowadays in case you were interested and can be found at [docker hub](https://hub.docker.com/r/kruptein/planarally)

**Comment by schemen** [comment]
Ah beautiful! That was it. I was not aware of the db file name change. Renaming it helped :)

Ah very nice! I have been building them myself for now. I will move to your image now.
Yeah, this resolves this issue - https://planarally.dndbox.com is up and running on the latest version :)

Thank you!

**Comment by Kruptein** [comment]
Sorry for the panic, totally my bad for not having it in the release notes. Glad it got resolved :)
