### ISSUE TITLE
Help Accessing App/Server without Dev Mode

### ISSUE THREAD

**Issue by trashxking** [Kruptein/PlanarAlly#148]
Hello, I'm hoping someone can help me out.

I am essentially having the same issue as described in [this reddit thread](https://www.reddit.com/r/DnD/comments/9j3vzp/tool_planarally_v09_a_selfhosted_virtual_tabletop/ef5z17w/?utm_source=share&utm_medium=web2x). Essentially, I downloaded and installed PlanarAlly manually per the instructions [here](https://planarally.readthedocs.io/en/dev/installation.html#self-hosting) using Visual Studio Code and I have Python 3.7.3 (downloaded directly from the official website) installed in my program files. Installation was smooth and I downloaded the necessary requirements through pip, but once I launched the server and opened up localhost:8000, all I could see was the background. The server obviously loaded, as the tab title had the PlanarAlly slogan in it, but there was nothing on the page besides the background. Using the Chrome developer tools, I found an error in the console tab:
`Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

This error applied once to `app.786ad160.js:1` and once to `chunk-vendors.026de90a.js:1`

I tried a number of different solutions, but nothing seemed to work. Finally, I ended up opening the entire PlanarAlly folder in VSC and noticed the client folder. I saw that the readme mentioned that the client was only necessary for developing the app, but I decided to try it anyway. I ran through the instructions, opened up a dev server, and ran the build. I'm new to programming that isn't css/html, so I wasn't sure exactly what a "production build" was, but I didn't see any kind of new file to execute after going through the client instructions. So, I decided to just launch the server in dev mode and to my delight there was suddenly a login screen! I was able to login, play with the app, as well as get my partner to join through our local network. Everything worked just fine.

I guess my confusion comes from the fact that the client readme mentions that the client is only necessary for if you want to help develop PlanarAlly. I don't believe I actually ran the client, but that statement would lead me to assume that launching the server in dev mode shouldn't be required. However, that was the only way I was able to get past the MIME type errors mentioned earlier. This error, specifically in the reddit thread linked above, seemed to have been resolved by putting the mimetype code higher within the server code, but I've downloaded the most recent version of PlanarAlly and the mimetype code is already at the 5th line, so I wouldn't think that would be the issue.

IS launching the server in dev mode required every time? Or am I possibly doing something incorrectly? Any assistance would be greatly appreciated.

PS. I often program in css/html and launch localhost in order to test out code, but I am otherwise extremely new to Python and, to a lesser extent, Javascript, so I apologize in advance if I've just overlooked something simple!

**Comment by Kruptein** [comment]
Hey thanks for opening the issue.

It's definitely meant to work without dev mode.  The client is written in typescript which means that to be useful it has to be transpiled to javascript.  In the dev mode this is done with a monitor that actively detects changes and transpiles them as they are changed.  This is however not ideal for a production version and thus for the production version I already build the actual javascript files and place them in the correct place in the server.  That's why I mention the client only for dev purposes.

There clearly is something going wrong.

It's an issue that has cropped up in the past and I thought was solved, but alas. What confuses me most is the fact that it does work in dev mode.

I'm working on it, will respond when I've got a fix.

**Comment by Kruptein** [comment]
Which release/version of PA are you using btw? The files with the errors you provided don't exist in the latest version of the codebase so I'm suspecting something else is going awry.

**Comment by Kruptein** [comment]
Ok I managed to find the commit in which those files where used.  That should be version 0.14.X which did not yet have the mimetype fix.  Could you try again with a more recent version ?  (You can find official releases [here](https://github.com/Kruptein/PlanarAlly/releases) or just pull the latest dev branch if you're comfortable with git

**Comment by trashxking** [comment]
Hi there, thanks for your quick response. Unfortunately the version file in the server folder indicates that I'm on version 0.17.0, the latest version that was released yesterday.

The file names may have been incorrect as I was a bit hasty and copy-pasted them from the reddit thread, completely forgetting that they likely changed between versions. Sorry about that! The actual file names from my version are:
`app.42053706.js` and `chunk-vendors.c4cd3f40.js`

![image](https://user-images.githubusercontent.com/51835651/59621176-555ba480-90f4-11e9-9870-8d351b887024.png)

![image](https://user-images.githubusercontent.com/51835651/59621341-b6837800-90f4-11e9-9d9c-5209de53d8e3.png)

**Comment by Kruptein** [comment]
Dammit, here I thought it was an easy mistake :D

**Comment by Kruptein** [comment]
In which folder did you find those files btw?  Because if I go to the [static folder](https://github.com/Kruptein/PlanarAlly/tree/master/server/static/js) the numbers are different.

**Comment by Kruptein** [comment]
Oh you did run with dev mode, that might explain the different file names. The sizes seem right either way.

Could you perhaps open python and run:

```python
import mimetypes

mimetypes.guess_type(".js")
```

**Comment by trashxking** [comment]
I was hoping it was easy, for your sake! :)

I think you're right in that it's because I ran in dev mode, as those finals are definitely in the server/static folder for me:
![image](https://user-images.githubusercontent.com/51835651/59622161-732a0900-90f6-11e9-8c3f-4d230a6726c0.png)

The ones in the downloaded zip folder, however, are different: 
![image](https://user-images.githubusercontent.com/51835651/59622283-bdab8580-90f6-11e9-9994-3ea7559efdd6.png)

**From Python I got this:**
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mimetypes
>>> mimetypes.guess_type(".js")
(None, None)
>>>

I made sure to download the latest Python version and use it when dealing with PA, but I do have Python 2 downloaded somewhere. Could this be causing an issue?

Additionally, I feel I should specify that running `python server/planarserver.py dev` or `python planarserver.py dev` (depending on which folder I've opened) on its own gives me a 500 Internal Server Error. I'm only able to access the app when I run `python server/planarserver.py dev` AND `npm run serve` in the client folder.

**Here are some of the messages I get from the terminal. First, trying to access localhost without running the client folder:**
PS C:\Users\Tyberius\Desktop\PlanarAlly\PlanarAlly-0.17.0> python server/planarserver.py dev
2019-06-17 11:46:47,509 - WARNING -  RUNNING IN NON SSL CONTEXT  (planarserver.py:62)
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\base_events.py", line 959, in create_connection
    raise exceptions[0]
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\selector_events.py", line 464, in sock_connect
    return await fut
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
    return await handler(request)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp_session\__init__.py", line 152, in factory
    response = await handler(request)
  File "C:\Users\Tyberius\Desktop\PlanarAlly\PlanarAlly-0.17.0\server\routes.py", line 24, in root_dev
    "get", target_url, headers=request.headers, params=get_data, data=data
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:None [Connect call failed ('127.0.0.1', 8080)]
Error handling request
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\base_events.py", line 959, in create_connection
    raise exceptions[0]
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\selector_events.py", line 464, in sock_connect
    return await fut
  File "C:\Program Files (x86)\Python 3.7.3\lib\asyncio\selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
    return await handler(request)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp_session\__init__.py", line 152, in factory
    response = await handler(request)
  File "C:\Users\Tyberius\Desktop\PlanarAlly\PlanarAlly-0.17.0\server\routes.py", line 24, in root_dev
    "get", target_url, headers=request.headers, params=get_data, data=data
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Program Files (x86)\Python 3.7.3\lib\site-packages\aiohttp\connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:None [Connect call failed ('127.0.0.1', 8080)]

**Then, running alongside client folder:**
PS C:\Users\Tyberius\Desktop\PlanarAlly\PlanarAlly-0.17.0> python server/planarserver.py dev
2019-06-17 12:03:35,660 - WARNING -  RUNNING IN NON SSL CONTEXT  (planarserver.py:62)
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)

**In a second terminal:**
PS C:\Users\Tyberius\Desktop\PlanarAlly\PlanarAlly-0.17.0\client> npm run serve

> planarally-client@0.17.0 serve C:\Users\Tyberius\Desktop\PlanarAlly\PlanarAlly-0.17.0\client
> vue-cli-service serve

 INFO  Starting development server...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
 98% after emitting CopyPlugin

 DONE  Compiled successfully in 5313ms                                                                                                                         12:04:11 PM                                                                                                                                            Type checking and linting in progress...

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.105:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

No type errors found
No lint errors found
Version: typescript 3.5.2, tslint 5.17.0
Time: 7722ms

Hopefully this is helpful in some way and not just a wall of useless text.

**Comment by Kruptein** [comment]
Yes the dev server will only work if the npm run serve command is also running, that's by design and has to do with the transpiling I mentioned earlier.

The cause is the mimetype stuff that returns (None, None) on your system.  I've had a user in the past that had a slightly different return type that was still incorrect and I have no idea why this happens to you.

Could you try this fix: Replace the server/planarserver.py file with [this file](https://gist.github.com/Kruptein/012eda4813b2985da05f648b0edcc968) and run again (without dev mode)

**Comment by trashxking** [comment]
It didn't seem to help at first but I suspected that might have something to do with the files being named differently because of originally running in dev mode, so I unzipped a clean copy of PA and pasted in the new code.

Looks like it did something, at least! The page is still only the background, but now there's only one error! `chunk-vendors.c4cd3f40.js`

![image](https://user-images.githubusercontent.com/51835651/59625020-e420ef00-90fd-11e9-86d5-4f52d7aa3468.png)

**Comment by Kruptein** [comment]
That makes even less sense :D.

So to explain a bit what's happening:  the mimetypes stuff tells the python server what kind of file it is serving,  so when the browser receives a ".js" file it expects to get notified that it is a 'text/javascript' file.  For some reason however the server is sending the file as "text/plain" which is wrong.  So what I changed in the file I gave was simply if your computer does not know what ".js" means, tell it that it should be 'text/javascript'.

So I'm rather confused that only 1 of the 2 files got fixed.  Well attempt 2 to this fix, replace it again but with [this file](https://gist.github.com/Kruptein/db82f3278d89691921d3432754eebbb0)

**Comment by trashxking** [comment]
That is puzzling... Unfortunately attempt 2 still produced the same error as in my previous comment, with just the chunk-vendors file. :(

**Comment by Kruptein** [comment]
Also if you force reload the page? (Ctrl+R or Ctrl+F5) :(

**Comment by trashxking** [comment]
Actually, after restarting the server and forcing a reload, it seems that both of the errors are back.

I decided to try a different browser (Firefox) and the console there shows this:
`Loading module from “http://localhost:8000/static/js/app.3ba691e3.js” was blocked because of a disallowed MIME type (“text/plain”).
localhost:8000`
`Loading failed for the module with source “http://localhost:8000/static/js/app.3ba691e3.js”. localhost:8000:1:1`
`Loading module from “http://localhost:8000/static/js/chunk-vendors.c4cd3f40.js” was blocked because of a disallowed MIME type (“text/plain”).
localhost:8000`
`Loading failed for the module with source “http://localhost:8000/static/js/chunk-vendors.c4cd3f40.js”. localhost:8000:1:1`
`The script from “http://localhost:8000/static/extern/js/fontawesome-5.6.3.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type.`

**Comment by Kruptein** [comment]
Oh I just noticed a stupid typo. I updated the previous file, could you try again :angel: (remember to force the cache reload).

**Comment by trashxking** [comment]
That fixed it! I can log in and access everything, and it looks like others on my local network can as well!

Thank you so much! I'm looking forward to updates and getting to play around with it. 😊

**Comment by Kruptein** [comment]
Great to hear! I still have no idea why it fails at all in the first place, but you're not the first with the problem although it is pretty rare.

Thanks for sticking around for some back and forth!
