### ISSUE TITLE
Line of Sight and Light Sources

### ISSUE THREAD

**Issue by freddyyeddy** [Kruptein/PlanarAlly#155]
When I check the Show Light Sources In Line of Sight it does not matter where the player token is if the "Light Source" (I assume a Light Aura) is within a straight line ( if not obstructed by the Fog of War Lines Drawn) of the token the Aura area is fully visible to players.

**Comment by Kruptein** [comment]
Only those parts of the aura that the player can see should be visible, if that's not the case either something is configured wrong or there is a bug.

Can you check whether 'cover the entire screen in FOW' is also checked ?
Otherwise could you provide some screenshot(s)?
