### ISSUE TITLE
Add option to change resource for a shape

### ISSUE THREAD

**Issue by Daniferrito** [Kruptein/PlanarAlly#163]
Explicitly, i mean changing the graphic of any shape to a image from assets, or to a new image generated from the "Create basic token" menu (and maybe to a plain square/circle)

This is useful if for example to change the color or text from a basic token, or to update a character to use a new image after a session of using a basic token.

**Comment by Daniferrito** [comment]
Also add the option to rotate the existing image (maybe only in increments of 90º), as the user might want to have the character facing certain ways.

Also, as a bonus, add a list of images for the token, for quick swapping. Useful for druid shapeshifting, and injured characters.

**Comment by dthv** [comment]
> Also add the option to rotate the existing image (maybe only in increments of 90º), as the user might want to have the character facing certain ways.

Implemented with #443
