### ISSUE TITLE
Add a way to edit the locations

### ISSUE THREAD

**Issue by Daniferrito** [Kruptein/PlanarAlly#164]
What is needed:
- Rename location
- Reorder locations
- Delete locations

This can be acomplished by a cog icon in the top-right of each location box to open the modal to change the name or delete the location, and two arrow buttons at the botom to swap that location with the one in the left/right. To make it cleaner, only show the buttons if the mouse is over the location box (and add some other way of doing this when touch input is suported)

Edit: Also, probably add location-based settings for some of the DM options, like grid and vision tabs (so the DM options are the default and some locations can override them). This allows for some neat features, like an overworld map, where distance can be measured in kilometers, or some day and night locations.

**Comment by Kruptein** [comment]
In addition to what you describe I also want to have a display showing names/icons of the user tokens per location, giving you the option to drag them between locations and have players on different locations.

Also currently a bunch of settings already are location based (e.g. grid, vision settings)

**Comment by Daniferrito** [comment]
Take into account that at least, ast it is currently designed, players can own tokens in multiple locations simultaneously, so it would have to be separated from owned tokens.

On the other hand, the players could be allowed to freely swap between all the locations where they own at least a token. Maybe even let the DM swap between those two modes.

However, I see that as much more contrived than necesary, for very small gain. 

Finally (althrough it does not fit here I want to bring it up), the option to "bring players here" will need to be reworked to some degree once players can be in diferent locations at the same time.

**Comment by Kruptein** [comment]
Fair remarks, I don't mind people being able to swap between locations at will, but I do agree that the added gain is very small and it does add quite some complexity.

I do think there is merit to at least having player names per location, so that you can move around as a DM without your players following you as well.  This can in a first instance be a general 'players' token that moves all players along with it, but it might be interesting to have the ability to split players up later on.

**Comment by Daniferrito** [comment]
Oh, you mean token as a shape in the locations bar that indicates that the player/players are there. I tough you meant linking where the player is to what tokens they have control over.

Yes, copying what roll20 or similar tools have would probably work.
