### ISSUE TITLE
Default tokens draw issue

### ISSUE THREAD

**Issue by Daniferrito** [Kruptein/PlanarAlly#167]
Multiple issues exist with the tokens created by the create default token tool.

The letter inside has inconsistent size. Some letters are noticeably bigger than others. See screenshot for example between letters M, X and L. The right one is one on top of another (with transparent background so all letters can be seen at once). I assume the font used is not monospace, so diferent letter widths make the autoscale behave weirdly

Other than that, the border of the token is bigger than the tile the token is in. This is exclusivelly the border problem, as the fill circle fits exactly in the tile. Just moving the border half its width inside should fix the problem.

**Comment by Daniferrito** [comment]
Forgot to attach the image 
![TokenDrawIssues](https://user-images.githubusercontent.com/2537742/65272861-32d88d80-db20-11e9-809a-de4b1f6ab8ab.png)

**Comment by Kruptein** [comment]
I've tinkered a bit with the code and I currently have this:

![image](https://user-images.githubusercontent.com/1814713/67201932-b5968600-f407-11e9-8dab-0c55c6b30c9a.png)

Which I'm gonna settle on for now
