### ISSUE TITLE
Add option to draw lines & multilines

### ISSUE THREAD

**Issue by Daniferrito** [Kruptein/PlanarAlly#174]
From #166 
2. The ability to create line-only walls is missing
3. Adding walls around complex shaped-rooms is cumbersome, as many squares need to be added to fill every single outside bend.

Sugested solution would be to add a multi-line tool, like the polygon shape. The option for simple lines does not need an extra tool, just a multi-line with a single segment.

The line shapes would need to have bigger bounding bow when selecting/right clicking it, as clicking a single-pixel line (tested with the polygon tool)

**Comment by Kruptein** [comment]
So the same system as the polygon tool, whereby a click adds a point and a right click finishes the shape (without closing though)?

**Comment by Daniferrito** [comment]
Plus escape or changing tools also finishing the shape (plus adding that to polygon too).
It is confusing for some users, as per #158

**Comment by Kruptein** [comment]
I absolutely agree that it's confusing, ideally some visual cue should appear somewhere that says [press right click to complete your shape] or something.

Pressing escape is also a needed QoL addition indeed.

I'm wondering if we actually need to add a new tool, or rather add a toggle option to the polygon tool to automatically close the path (for polygons) or not (for normal multilines).

**Comment by Kruptein** [comment]
This is tackled in PR #182
