### ISSUE TITLE
Spell Effect Area of Effect measuring/templates

### ISSUE THREAD

**Issue by jgrasty25** [Kruptein/PlanarAlly#195]
It would be nice to have the ability figure out who/what spell effects can hit using common area of effect shapes and sizes. I.e. 30 foot cone, 20 foot circle, 5 foot 45 degree arc, etc. 

If that can tap into the same code as the lighting system, it can also be used to see if obstacles block an effect from hitting a target as well. 

If this sound reasonable. I would like to see if I can help implement it.

**Comment by Kruptein** [comment]
It would be nice indeed, the only thing I'm currently struggling with is how the UI would work.  That said, the code should definitely be able to tap into the knowledge the lighting system has about walls etc.

I'll have to think about some sort of UI views (e.g. an edit mode and a play mode) to prevent more and more UI elements to appear of which only a part is actually used during game play and another part during the DM prep.
