### ISSUE TITLE
Ability to save tokens for reuse or as templates

### ISSUE THREAD

**Issue by jgrasty25** [Kruptein/PlanarAlly#196]
It would be nice to be able to duplicate tokens with tracker, tags and other data already on them to re use and/or duplicate them.

I would like to help implement this as well if its a feature within the scope of the project.

**Comment by Kruptein** [comment]
The ability to copy a token and all its stats and later paste it somewhere (be it in the same map or a completely different session) already exists.

This is however login session dependent and is only limited to one copy at a time, so I can see the usecase to have some clipboard with commonly pasted tokens.

Help is definitely appreciated and feel free to ask any questions if things are unclear.

To implement this feature you'll have to think about how this data should be saved in the database and it should be represented in the web UI.

**Comment by Kruptein** [comment]
This has been implemented with the templating system in 0.23 I believe.
