### ISSUE TITLE
Tokens lag behind compared to the grid when panning around

### ISSUE THREAD

**Issue by AntiSC2** [Kruptein/PlanarAlly#21]
When panning around the map, tokens get misaligned with the grid until you stop panning. Here is a [gif to show what I mean](https://gfycat.com/HandyLeafyHaddock).

Browser: Firefox 60.0

**Comment by Kruptein** [comment]
Hey this is indeed a known problem.

I'm not entirely sure yet how I'm gonna fix it but it's on my to do list!

**Comment by AntiSC2** [comment]
Can confirm that 0d99d5ed88766441726def0d694b0299603f6021 fixes the issue so I'm closing the issue.
