### ISSUE TITLE
Add additional files to make this easily deployable to Heroku

### ISSUE THREAD

**Issue by ZachMyers3** [Kruptein/PlanarAlly#210]
The server aspect of this project lends itself extremely well to Heroku, if a [Procfile](https://devcenter.heroku.com/articles/procfile) were to be appropriately assembled it could potentially have one click deployment, making it more accessible to new users.

[This](https://elements.heroku.com/buttons/sseg/heroku-aiohttp-template) is a template to work off of for aiohttp.

**Comment by Kruptein** [comment]
Interesting, I'll definitely take a look at it :)

**Comment by ZachMyers3** [comment]
Since this already has a Dockerfile and builds to docker it seems like creating a [heroku.yml](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml) in conjunction with an [app.json](https://devcenter.heroku.com/articles/app-json-schema) file would allow for deployment to heroku with the click of a button.

**Comment by ZachMyers3** [comment]
I've got this nearly working but am running into some drawbacks.

Currently to deploy you have to build the client, and .gitignore explicitly removes those files. 

Heroku doesn't have the capability to run preamble scripts like that, and can only serve the files already in the repository. If the pre-built files were to be inside ```server``` on deploy I can get it working without issue. What are your thoughts on lifting this? I see currently on the master branch that these files are available.

**Comment by Kruptein** [comment]
I would rather not include them again in the repository.  They provide little value and only add to the repository size with the addition of often hitting merge conflicts.

What I can do is creating a zip with all js artifacts upon release.  Can heroku do some basic curl/wget call and unzipping or is that also out of its posibilities? Otherwise I'll ahve to create a dedicated planarally-heroku image.

**Comment by ZachMyers3** [comment]
Unfortunately it can't. As far as deployment goes to Heroku it can install the needed packages for a given language base (node or python but not both) and then run a simple execution and expose that to the web. 

Would there be a possibility to a Heroku branch that held these, that was coupled with master that held these files within the directory?

**Comment by Kruptein** [comment]
But doesn't heroku just use the dockerfile? It already builds the js files and moves them to the server folder.

**Comment by ZachMyers3** [comment]
I thought at first that docker deploy wasn't working but I discovered the issue.

If we're able to the the environment variable PORT and assign it to the server port heroku deployment should work. If we're able to expose the docker server depending on the PORT environment variable I think it'd work.

**Comment by Kruptein** [comment]
It's a bit annoying that they just ignore EXPOSE and provide no way to map it like docker itself does.

Either we create a separate heroku image, with a custom server_config, or we need to add a -p flag to the server and change the dockerfile to use that if the $PORT env variable is set.

The former requires an extra docker image with very small changes which seems a bit dumb, but the latter is very unfuture-proof in that another service might use a different env variable and then we're back at square one.

**Comment by ZachMyers3** [comment]
The latter seems like the better of the two options. 

I agree, it's an unfortunate reality. I hacked the planarserver code to just default to PORT if it was there to see if it would work, but a flag doesn't seem *too* terrible.

At the end of the day this is entirely optional, but I think one click deployment could really help with adoption for some people.

**Comment by Kruptein** [comment]
I can see the benefits, so adding a port flag is fine for me.

I was wondering whether you know how heroku works regarding the filesystem and more specifically the save files.  Is it actually persistent so that one can start a deployment and later come back to it?  Would it be possible to upgrade to a new version of PA?

**Comment by ZachMyers3** [comment]
I looked into this and on deployment the instance is destroyed and reconstructed.

Heroku's best suggestion (that I could find) to alleviate persistent data is to use Amazon S3

**Comment by Kruptein** [comment]
Yeah that's suddenly not so noob-friendly anymore, if you're going to have to configure things in s3. (Nor is their any support for a remote save file either currently).

We can do the heroku stuff as a quick way for people to test things, but with a big warning that nothing is saved.

**Comment by ZachMyers3** [comment]
There's another issue for an import/export function

Having a nice community member (like DnDBox does currently) host it for public use accomplishes about the same thing that this would.

I wouldn't be against closing this and picking it up when it becomes more feasible.

**Comment by Kruptein** [comment]
True, that said I should add some clear version info on the client side, so you know what you can expect.  I for example don't know how up to date the dndbox server is.

**Comment by ZachMyers3** [comment]
Added in #226
