### ISSUE TITLE
Zoom focusses around mousepointer, not screen center.

### ISSUE THREAD

**Issue by LDeeJay1969** [Kruptein/PlanarAlly#212]
When zooming, the focus point is the current mouse cursor. That means you always have to point at a location to zoom. If you want to use this on touch based devices it can be an issue and if you want to assign hotkeys (like + and -) you don't have a pointer location. 

Wouldn't it be better to zoom in at the center of the screen (=view port) instead of the mouse pointer?

**Comment by Kruptein** [comment]
You can choose to zoom to the center using the zoom tool in the topright.  On touch devices you would want to zoom using a pinch motion (i.e. 2 fingers). So you do have a location to zoom in/out.

**Comment by LDeeJay1969** [comment]
Ok. Didn't notice the difference between the two yet |-)
Another one for the documentation... :-)

**Comment by Kruptein** [comment]
It's actually one of the rare things that is covered in the docs ;)
https://www.planarally.io/docs/tools/zoom/
