### ISSUE TITLE
Display Version Info on Client 

### ISSUE THREAD

**Issue by ZachMyers3** [Kruptein/PlanarAlly#216]
A nice QoL improvement to see how in/out of date your server is.

**Comment by ZachMyers3** [comment]
Could this be pulled from ```packages.json```?

I see the package has a version tag, it'd just need to be changed on version upgrades. This is only accounting for the client version though. How would we approach getting the server version, and API endpoint?

```json
// packages.json
{
  "name": "planarally-client",
  "version": "0.18.2",
  "description": "A companion tool for when you travel into the planes.",
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "npm run clean && vue-cli-service build --no-clean --modern",
    "lint": "vue-cli-service lint",
    "clean": "rimraf ../server/static/js/ && rimraf ../server/static/css/"
  }
}
```

**Comment by Kruptein** [comment]
client has it in it's package.json and package-lock, server has it in the VERSION file.

Although it could change in the future, you can assume for now that client and server are always on the same versions.

**Comment by ZachMyers3** [comment]
Would the best bet be to implement an API endpoint for the server to pull into the client? I'm not too fond of the idea of pulling from the server directory from the client.

**Comment by Kruptein** [comment]
Sure, I believe you could also parse it from the package json itself, but that involves some potential security issues, so just having a server api endpoint is absolutely fine.
