### ISSUE TITLE
Server error: Unable to find 'templates\\index.html'

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#218]
Hello,

I did the following:
1. clone the dev branch
2. ran "pip install -r requirements.txt", 
3. fired up the server via python planarserver.py (both dev and normal)
4. tried to connect using chrome and 'http://localhost:8000/'

I get the error message on the server cmd line window "FileNotFoundError: [WinError 3] The system cannot find the path specified: 'templates\\index.html'

I tried to switch to the master repo and copy down the index.html I found in that repo but all I get is a blank screen.

Any suggestions?

**Comment by Kruptein** [comment]
Yes, I changed some things around and now you have to build the js files themselves if you don't run the binary.

I can foresee some people with enough python knowledge but no js knowledge running into some issues with this, so what I suggest is that I'll always attach a zip with the js artifacts to the releases.

For the non-master git checkouts though, you'll need to take care of this yourself. Check the [CONTRIBUTING](https://github.com/Kruptein/PlanarAlly/blob/dev/CONTRIBUTING.md) document.  I'll make sure to create some more clear installation documents as well :)
