### ISSUE TITLE
Hot key to quickly send selected tokens to a layer

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#219]
Having a tinker, I thought it'd be amazing to be able to send tokens to a new layer with a hotkey press. Possibly the numeric keys could be used in combination with something to send to a particular numeric layer. Even just one up/one down would be super sweet.

**Comment by Kruptein** [comment]
PageUp/Down is a toggle to switch between floors.  So maybe something related with a modifier key for shapes ?

**Comment by AJAnderson** [comment]
Yeah that would work!

**Comment by Kruptein** [comment]
I've addressed this issue in PR #234. I did however just notice that you asked for a keybinding to move between layers, whereas I had interpreted it as a keybinding to move between floors.

Was your intent to ask about floors or layers? :)

**Comment by AJAnderson** [comment]
It was to move between floors 😊

**Comment by Kruptein** [comment]
Consider it implemented in dev then ;) (See the PR for the specific keybindings)
