### ISSUE TITLE
Adding a new floor resets grid size

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#221]
As per subject, adding a new floor resets the grid size to default.

To re-create (with current most recent dev):
Adjust the grid size to a different pixel count (I used 300)
Add a new floor

Grid is instantly re-rendered to default.

This makes me think, sometimes assests have a different dpi/ft relationship. Perhaps the grid should be an entity that's maintained on a floor by floor basis. 

Related to this, one could create a setting which is something like "zoom to x number of ft horizontal". I'm thinking specifically of the situation in which you're on a TV playing with miniatures resting on top. You would want to be able to flick between floors with different art assets (with potentially different DPIs) and have the effective size stay consistent i.e. always render the same number of grid squares across the screen.

**Comment by LDeeJay1969** [comment]
And on the topic of floors... you can delete the last floor (0). That still leaves objects undeleted (mainly aura's).

**Comment by Kruptein** [comment]
> And on the topic of floors... you can delete the last floor (0). That still leaves objects undeleted (mainly aura's).

Can you make a separate issue for this! To keep this ticket on topic.

Regarding AJ's message:
The bug with adding a new floor obviously needs to be resolved, that said I think for now I want to keep all floors on the exact same grid settings. Which should for now be enough to satisfy a similar experience across floors (correct me if I'm wrong).

**Comment by AJAnderson** [comment]
A simpler version of the functionality I'm after would be too be able to
save a certain zoom level. I forgot the assets themselves can be scaled.

**Comment by Kruptein** [comment]
Would do you exactly mean with 'saving a zoom level'?  Do you mean to lock the zoomlevel so that the zoom tools are basically disabled?

**Comment by AJAnderson** [comment]
More like being able to return exactly to a previous zoom level

**Comment by LDeeJay1969** [comment]
Maybe hotkey the numbers 0-9 to jump to that specific zoom-level and keep track of which floor has which zoom-level (make them persistent)?

**Comment by Kruptein** [comment]
Whoops my bad, this is not resolved.
