### ISSUE TITLE
Promote grid to a button on main UI. Make snap to grid a check box behaviour on tools

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#222]
I might have missed this, but it would be good if the grid could be quickly flicked on and off.

related, it would be good if snapping could be quickly turned on and off on a per tool basis.

**Comment by Kruptein** [comment]
Can you perhaps give some concrete examples where you want to frequently toggle the grid on/off ? This is something that I very rarely need in my games so it never has crossed my mind to make it part of the core ui.

A keybinding is definitely possible as well.

Snapping can be disabled by pressing the alt modifier.  In the near future I want to allow users to choose for themselves whether the default mode is snapping mode. (with alt always doing the opposite).

**Comment by AJAnderson** [comment]
The way I was working was using the grid for reference sometimes for sizing then turning it off for actual play. It's a bit of a weird use and I can see not really prioritizing anything around that.
