### ISSUE TITLE
Maybe make settings etc pop ups rather than fold outs?

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#223]
Definitely a personal preference thing but I find the fold outs to be a bit annoying. Is this something you're passionately for?

**Comment by LDeeJay1969** [comment]
A pop-up would not be helpful if you're designing, unless you pop-up on the side... which is what's happening at the moment. What I found annoying was the overlapping of the menus and bars. So I'm tweaking the interface to not do that anymore. Almost done, just finishing the radial. Once done, a hotkey can be added to unfold these....

![pa-menu](https://user-images.githubusercontent.com/24498457/75438023-210cd900-594f-11ea-8a63-044523f1e0f3.gif)

**Comment by Kruptein** [comment]
I'm not hard set on the folding bars, but I do want to limit UI clutter (i.e. the amount of actionable elements in default mode).

I think most elements in the folding bars are things that require low interactivity.  I do admit that there is plenty of room to improve the folding bars their UI.  Some of the elements (e.g. DM options) already opens a popup as it became too cluttered in the side bar and I think this is a direction that will be continued further for the other elements to some extent.

The locations bar (on top) is one I'm definitely going to rework relatively soon.  The main bar (left) is something I need to think about how I want to redesign it.
