### ISSUE TITLE
Grid not respected from DM to client.

### ISSUE THREAD

**Issue by AJAnderson** [Kruptein/PlanarAlly#224]
Have a custom grid set at 300 pixels (300 dpi image). When viewing in player view, the grid size is default, as a result lighting values are all wrong.

**Comment by LDeeJay1969** [comment]
That being said: grid is not stored at all. Setting a value as DM and refreshing the page, resets it back to 50.

**Comment by Kruptein** [comment]
This works fine on the latest release and broke with the introduction of floors.

Expect a fix by tomorrow/Wednesday.
