### ISSUE TITLE
Being able to add a number label to tokens 

### ISSUE THREAD

**Issue by adunis** [Kruptein/PlanarAlly#235]
I'm in need of a feature that IMHO it's very necessary. When dealing with a large number of tokens using the same image, even if you name token with a different number it becomes too hard to differentiate between Goblin 1, 2, 3 etc. 

I suggest being able to add a 'label' to a token that is overlayed over the token image. 

I made a quick sketch of  how it could look 

<img width="494" alt="NumberedGoblins" src="https://user-images.githubusercontent.com/47754845/76576541-a9988700-64c2-11ea-9b58-8462d1d4ad31.png">

**Comment by Kruptein** [comment]
This should be relatively easy to add.  I do have some questions in regards to desired behaviour.

* Would this be something you explicitly enable for a certain token or rather be opt out per token? Or even have this as a user setting?
* Do you expect some sort of auto-numbering?  If so
   * Do you expect this to be limited to copies of existing tokens on the board?  (e.g. say you have a particular monster token which you assign '1' and you copy/paste the token, should it automatically receive 2 as its number?)
   * Do you expect the numbering to be across all tokens instead? Green monster 1, Blue monster 2, Green monster 3 ...
    * What if I remove a token with number 2 when there is 1,2,3 and I create a new token, should it become 4 or 2 ?

**Comment by adunis** [comment]
> Do you expect this to be limited to copies of existing tokens on the board? (e.g. say you have a particular monster token which you assign '1' and you copy/paste the token, should it automatically receive 2 as its number?)

Yes, this feature would speed up setting up a combat. 

> Do you expect the numbering to be across all tokens instead? Green monster 1, Blue monster 2, Green monster 3 ..

No, only to the tokens I want labelled with a number. Either by manually editing each token, or by copy-pasting an already labelled token. I except having a single non-labelled token on the map, surrounded by multiple copies of a single token with different number labels. 

> What if I remove a token with number 2 when there is 1,2,3 and I create a new token, should it become 4 or 2 

When I copy one of those tokens (1 or 2 or 3) and paste it, I except the new token copy to be labelled as a 4. When I drag and drop the token from the asset menu, I except the new token to not be labelled.

**Comment by Kruptein** [comment]
Alright that's clear, I'll see what I can do this weekend :)

**Comment by Kruptein** [comment]
Some more questions:

* Do you want the badges to appear automatically as soon as you create a duplicate token with optionally a general user setting to hide badges or do you see a use case where you have for example badges for a group of duplicate orcs but not for a group of duplicate trolls.
* Skipping the gaps (e.g. badges 1 to 4 and removing 3 will not re-add 3 if a new token is pasted) is trivial with my current approach. Would it however be bad if in the case of shapes 1 to 4 and removing the 4 the next shape would get 4 again ?

**Comment by adunis** [comment]
> Do you want the badges to appear automatically as soon as you create a duplicate token with optionally a general user setting to hide badges or do you see a use case where you have for example badges for a group of duplicate orcs but not for a group of duplicate trolls.

I have created Tokens which weren't meant to represent 'enemies' but also objects, for example the components of a puzzle with which the players can interact. 

I would prefer if I had to check an option called 'Use Badges' on a Token in order for those to appear, instead of checking an option called 'Hide Badges'. 

>Would it however be bad if in the case of shapes 1 to 4 and removing the 4 the next shape would get 4 again ?

No, it's ok. 

It's only important to avoid changing the badge values of those tokens that the players can already see in order to avoid confusion.

**Comment by Kruptein** [comment]
Got most things working now in a separate branch, just need to add something to handle a corner case on shape delete and then I think I can merge it to dev

**Comment by Kruptein** [comment]
I believe it now works as requested in dev.
