### ISSUE TITLE
External acces problem on windows python

### ISSUE THREAD

**Issue by Dhy19971** [Kruptein/PlanarAlly#240]
HI, by accessing the PlanarAlly server via reverse proxy .. I used a domain to access externally .. I can log in correctly but then when I go to load a save it signals me to the choice of the save to be loaded .. locally processed

Thank you.

**Comment by Kruptein** [comment]
Hey, sorry I'm not fully following the problem.  What exactly do you mean with "load a save it signals me to the choice of the save to be loaded" ?

**Comment by Dhy19971** [comment]
Sorry for my English.

I wanted to use my own domain to reach the server outside my local network.

I was able to reach the server.

I can log in and create a new session.

When I try to join the session I can't get into it. The page for choosing the active sessions is reloaded.

I would just like to understand how to connect my domain to use the server through it.

I believe my problem is in the .cfg file

**Comment by Kruptein** [comment]
Ok, I think this might be related to #70 , Is your domain you try to forward a top level domain or a subpath ?  (e.g.  http://dhy19971/  vs http://dhy19971/planarally/)

**Comment by Dhy19971** [comment]
I forward it to my domain http://dnd.ex.com

when I log in to the domain I get this address back

http://dnd.ex.club/auth/login

**Comment by Dhy19971** [comment]
you can try at dnd.m2a.club

**Comment by Kruptein** [comment]
Hey so I just checked (created user test) and can confirm what you see.  The reason is that the websocket is seemingly blocked/badly processed.

Do you use something like nginx/apache to proxy the requests ?  You'll need to set up the /socket.io/ location proxy correctly.

I can give you an example nginx conf if needed.

**Comment by Dhy19971** [comment]
yes, i use nginx  as reverse proxy.

Thanks for your help.

**Comment by Kruptein** [comment]
This is a part of my nginx config, I've stripped as much as I think is irrelvant for you, I've changed my actual domain name with `<DOMAIN>` and the /static location path is also a dummy path.

You'll probably want to tweak this a bit as I use a socket instead of a port to configure PA.

```nginx
  server {
    listen *:443;
    client_max_body_size 4G;
    ssl on;
    ssl_certificate /etc/letsencrypt/live/<DOMAIN>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<DOMAIN>/privkey.pem; # managed by Certbot

    server_name <DOMAIN>;

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://aiohttp;
    }

    location /socket.io/ {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_pass http://aiohttp/socket.io/;
    }

    location /static {
      root /path/to/planarally/server/;
    }

}

  upstream aiohttp {
    server unix:/tmp/pa_1.sock fail_timeout=0;
  }
```

I'm not an expert in nginx either, so if you find something that works better for you to pass the websockets do let me know! :)

**Comment by Dhy19971** [comment]
I use a raspberry come backwards .. to make your code work I should manage the server on the raspberry and then give it the path .. I use it on a windows pc to run the server .. sorry but I'm a little cumbersome in these things .. I just approached it ..

Usually to avoid the problem I had with your server I always used a configuration on the server itself .. which I don't know how to do here.

**Comment by Dhy19971** [comment]
i use this 
server {
        listen 80;
        server_name dnd.m2a.club;
        location / {
        proxy_pass http://192.168.178.72:8000;
        }
}

**Comment by Dhy19971** [comment]
server {
        listen 80;
        server_name dnd.m2a.club;

        client_max_body_size 4G;

        location / {

              proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_redirect off;
         proxy_buffering off;
           proxy_pass http://192.168.178.72:8000;
        }
}


this apparently works .. thanks for your help .. i have no interest in the ssl on this server ..

**Comment by Kruptein** [comment]
Hey nice to hear you got it working! Yeah the ssl was just included because I use it, there is no mandatory need for it :).

I assume I can close this issue then? If it's not resolved feel free to reopen.

**Comment by Dhy19971** [comment]
Unfortunately, a second problem has arisen.

Activities do not charge me any.

It makes me select the element to be loaded, I wait a little but nothing happens even when I reload the page.

Every time I reload the web page requires me to log in .. which does not happen locally.

Some idea?
