### ISSUE TITLE
bug(Shapes) Change border colour for assets

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#242]
Currently the border colour for assets is transparent black.  When combined with badges this produces  a suboptimal effect.  Given that the border colour is ignored for rendering purposes it is thus suggested by @adunis to use opaque white instead.

**Comment by Kruptein** [comment]
@adunis it is currently fixed in PR #244 for all new assets dragged on the map.

Older shapes will still have their strokeColour set to black transparent.  Is this fine or do you want me to fix all shapes retroactively ?

**Comment by adunis** [comment]
Thank you for these fixes, it works perfectly now. 


> Older shapes will still have their strokeColour set to black transparent. Is this fine or do you want me to fix all shapes retroactively ?

No, personally I don't need it.
