### ISSUE TITLE
In chrome, the notification doesn't display on incorrect login. 

### ISSUE THREAD

**Issue by CalebKoch** [Kruptein/PlanarAlly#247]
One of my players reported to me that they were hitting the login button, but it wasn't doing anything. 
After doing some testing, we realized the issue is that the password was incorrect, but the page doesn't give adequate information when that is the issue. After trying in FireFox, I do see that I get an Error: Unauthorized, however that was not displaying in Chrome.

**Comment by Kruptein** [comment]
Hm, interesting as I do use a chromium based browser myself (not chrome itself though) and don't seem to have this problem.

Can that player reproduce it every time or was it resolved since restarting the browser for example ?

**Comment by CalebKoch** [comment]
After he asked about it, I was able to reproduce it myself, so same browser on two different machines. And for me it persists after having closed the browser.

I just tested on Brave and Opera, and am seeing the same issue on both of them. 

The server is using the docker image, if that helps at all.

**Comment by Kruptein** [comment]
Hm, I've tried some other browsers, but have been unable to reproduce it.  Next up is trying with the docker image to see if that somehow causes the bug.

**Comment by CalebKoch** [comment]
After looking into this some more, it seems to be an issue with my setup, not PlanarAlly. The reverse proxy I use is upgrading the connections to HTTP/2, which doesn't support text along with the status code. 

If you would like, I'd be willing to make a change to read the error messages from the body of the response, rather than the status text. Otherwise, I think this issue can be closed.

**Comment by Kruptein** [comment]
Ah good to know, thanks for investigating it further! Feel free to make a PR for it as well.

I'll keep the issue open until the status codes are fixed as it seems to be an actual bug then.
