### ISSUE TITLE
I cannot make heads nor tails of PlanarAlly

### ISSUE THREAD

**Issue by csells** [Kruptein/PlanarAlly#249]
The screenshots on your blog show that PA provides exactly the functionality that I'm looking for, but I cannot figure out how to do anything except create new sessions and upload assets. How do I add an asset to the grid? How do I add avatars to drag around on the grid? How do I access fog of war? Those are really all the features I'm looking for, but I have no idea how to access them and the tutorial seems to stop right before talking about how to access those features. Sorry to spam your issue list, but I could find no other way to ask my question. Thanks!

**Comment by Kruptein** [comment]
Hey, no problem to post here!

It's my bad that the tutorial docs are not complete yet.  Have you tried interacting with the topleft cogwheel when you are in a session ? It should have a submenu that lists your assets which you can drag on the grid and it also has a button to open DM settings like fog of war

**Comment by csells** [comment]
I am able to access the topleft cogwheel in my session and I am able to list my assets. I clicked and clicked and clicked on my asset and never once thought to drag and drop. Perhaps just a simple click would help new folks get started?

**Comment by csells** [comment]
I'm afraid I don't know how to add an avatar or use fog of war, either.

**Comment by Kruptein** [comment]
Regarding the fog, there is a documentation part about [lighting and vision](https://www.planarally.io/docs/dm/light-shadows/) that hopefully helps you out.

I'm not entirely sure what you mean with the avatars ?

**Comment by csells** [comment]
By avatar, I mean being able to bring in graphical representations of my players and monsters, e.g. https://www.pinterest.com/davidkeennc/top-down-characters

For FOW, I'm simple hoping to be able to import a map, place the avatars, cover the whole thing in FOW and then as my players move their avatars around, selectively review parts of the map that they can now see.

Does PA do either of those?

**Comment by Kruptein** [comment]
Yes most definitely, I'll see if I can get some documentation ready tomorrow that shows some of the basic intro steps for a DM.

**Comment by csells** [comment]
That would be really great. Thank you.

**Comment by Kruptein** [comment]
So I added some starting info over [here](https://www.planarally.io/tutorial/in-game/first-session/). I hope this is enough to get you going!

**Comment by csells** [comment]
Thanks very much for the docs; I appreciate it!
