### ISSUE TITLE
Asset and cloud sharing

### ISSUE THREAD

**Issue by Dhy19971** [Kruptein/PlanarAlly#251]
It would be nice if the ability to share assets in the various sessions were implemented.

It would be very convenient if it were possible to use the assets loaded on google drive and nextcloud (or similar clouds).

As far as the guard is concerned, the assets could be beautiful far from being able to rotate and mirror them

It may be useful to upload folders and subfolders instead of just files.

Another idea could be that every player invited to the session can upload their own character token .. and obviously the DM must be able to see and use it

I'm new on github so if my comment here is inappropriate tell me as well!

**Comment by Kruptein** [comment]
So these are a bunch of different things.

Attaching something like google drive/nextcloud is something I could see added in the future, but this is relatively low priority in regards to my own development time.

Rotating/mirroring assets in-game is indeed something that is on the to-do list for the near future.

Uploading folders/subfolders is something I would like to add, but if I'm correct at the time of my original implementation, this was a limitation from the browser. I should check this again.

Letting players manage their own characters/tokens is also on my radar.

**Comment by Dhy19971** [comment]
okay .. yours seems like a great plan!
