### ISSUE TITLE
Add a way to edit sessions

### ISSUE THREAD

**Issue by KomaGR** [Kruptein/PlanarAlly#252]
I'm not sure if I missed something, but ways to manage sessions in the start-screen are needed.
Particularly:
 - Rename session
 - Delete session

One idea would be to have an edit and a trash icon button for each session. Another option would be placing the functionality inside the Account Settings.

**Comment by LDeeJay1969** [comment]
In the DM-panel of each session (as DM) you can delete the session. (Admin tab at the bottom). Renaming it is not possible (yet) as far as I know.

**Comment by KomaGR** [comment]
Okay, I missed that.
I know you can go back to the start by manipulating the url but maybe an _Exit Session_ is needed under _DM-Panel_, too.

**Comment by Kruptein** [comment]
There is a big exit button in the sidepanel menu :D

And indeed as LDeejay said you can delete sessions from the dm menu, but I do want to update the UI of the start screen and indeed provide things like a rename and delete from that window.

**Comment by KomaGR** [comment]
Well, that's embarassing. Though the fact that I looked for those things in the wrong places tells a story by itself.
