### ISSUE TITLE
Eliminate map level

### ISSUE THREAD

**Issue by Dhy19971** [Kruptein/PlanarAlly#253]
Hi,

I don't know if I'm wrong but there are no ways to avoid the level of the maps. thank you very much.

![dw](https://user-images.githubusercontent.com/54805023/77532735-c73bf800-6e95-11ea-89c6-3e3f2df0b837.PNG)

**Comment by Kruptein** [comment]
The sad truth is that you can't yet.

Reworking that bar is my prime target for the next release though!

**Comment by Kruptein** [comment]
Wait I'm not really sure if I'm following.  Are you talking about the map layer (in the lower left) or about the location bar as you attached?

**Comment by Dhy19971** [comment]
I was talking about the location bar .. okay I understand thanks !!
