### ISSUE TITLE
token authorization bug

### ISSUE THREAD

**Issue by Dhy19971** [Kruptein/PlanarAlly#255]
If I want to move a token that I am not authorized to use, I can do it with the keyboard arrows.

I think it's a bug.

**Comment by Kruptein** [comment]
It's a client-side bug indeed. The operation is declined by the server as it notices that the access rights are not correct so nobody else would see these wrongful moves.

The player self could spoil itself though.  I expect a fix in about 3 minutes on the dev branch and will probably create a hotfix for the 0.19 release later today or in the span of the following week as it does have some impact.
