### ISSUE TITLE
asset manager not loading in sidebar

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#256]
Unable to replicate this but I encountered an issue on the DnDBox version not sure if that one keep updates with the latest version or not. but I've ran into the asset manager not loading my saved assets on the sidebar. This seemed only to be with the version of chromium I'm using as i was unable to replicate it in Firefox-ESR

Chromium Version 80.0.3987.149 (Developer Build) built on Debian 10.3, running on Debian 10.3 (64-bit)  
Firefox-ESR 68.6.0esr  

Didn't spot another bug mentioning this

**Comment by Kruptein** [comment]
Given that you can't reproduce it I assume that you also have no idea whether there were any strange errors in the browser console?

Also just to make sure, currently if you add assets to the assetmanager, any open game session will not have the new assets. You'll need to reload the page for them to get added. This is something on my todo to fix as it is an annoyance.

**Comment by 10leej** [comment]
dndbox is on 0.19.2 which seems to be the latest version  
I do believe I didn't reload the page when I added the assets so maybe that's what was going on.
