### ISSUE TITLE
socketio CORS origins error

### ISSUE THREAD

**Issue by ASMfreaK** [Kruptein/PlanarAlly#257]
Thank you for this great tool.
PlanarAlly is installed on my instance before an NGINX proxy with ssl via the Dockerfile you provided in the repo. The proxy is set up using [this snippet](https://github.com/Kruptein/PlanarAlly/issues/240#issuecomment-601366479). Using it directly via the exposed port works great. 
Using it via NGINX results in error during session startup. The page flashes for a second and return to session select page.
Browser console complains about websocket connection and HTTP error 400.
Addition of the following line to `app.py` didn't yield anything useful.

```python
logging.basicConfig(level=logging.DEBUG)
```
After that I've googled up a lot about error 400 in socketio. It turns out that `python-socketio` checks origin of the request.
Applying the following patch made the error go away after container was rebuilt. 

```diff
diff --git a/server/app.py b/server/app.py
index 988ceab..41e0067 100644
--- a/server/app.py
+++ b/server/app.py
@@ -16,7 +16,7 @@ from utils import FILE_DIR
 
 # SETUP SERVER
 
-sio = socketio.AsyncServer(async_mode="aiohttp", engineio_logger=False)
+sio = socketio.AsyncServer(async_mode="aiohttp", engineio_logger=False, cors_allowed_origins=["https://some.https.server"])
 app = web.Application()
 app["AuthzPolicy"] = auth.AuthPolicy()
 aiohttp_security.setup(app, SessionIdentityPolicy(), app["AuthzPolicy"])
```

This is [the code](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L333) responsible for the error alongside the [documentation](https://python-socketio.readthedocs.io/en/latest/api.html#asyncserver-class) for the `cors_allowed_origins` parameter. I think this setting should be adjustable from the PlanarAlly server config.

**Comment by Kruptein** [comment]
Cool, thanks for looking into it! This should indeed be configurable from the server config :)

**Comment by Kruptein** [comment]
This is merged into dev
