### ISSUE TITLE
Lock tokens for players from editing

### ISSUE THREAD

**Issue by Price454** [Kruptein/PlanarAlly#259]
I have noticed that players can edit their own tokens.
This includes giving them auras (with potentially increased view values)
Is there any way to remove their ability to edit their tokens or to dissallow aura editing/creating.

**Comment by Kruptein** [comment]
At the moment, not yet, it's a valid concern though.  I'll add it to the list.

**Comment by edmael** [comment]
Not only the aura stuff, it would be nice if we can avoid players to edit their own token size.

**Comment by Kruptein** [comment]
This has been resolved in the newest version!

Ownership/access now makes a difference between vision access and edit access

**Comment by Price454** [comment]
I want to re-open this issue.
Seems that when I give a player Vision rights only they cannot move the tokens.

Giving them edit and vision allows them to fully modify (including size) the token again.

Playing on https://planarally.dndbox.com/
Server version: = docker:- (https://github.com/Kruptein/PlanarAlly/commit/dev)

**Comment by Kruptein** [comment]
Well yes that's the intention.  So you want specific movement permissions as well.  How unruly are your players :D

Could you open a new issue that's more on-topic: movement permission

**Comment by Kruptein** [comment]
Thing is that this will become complex very soon.  My players for example like to use the trackers to track their HP.  Would that also be an extra permission ?

I can see some merit for a movement permission, but I don't want to turn this into a permission hell

**Comment by Price454** [comment]
Oh I see.
Currently my use case is the following:
1. Players create their basic tokens
2. I (as DM) add the light and darkvision auras
3. Players move their own tokens through the map

But from playing I have noticed that the players often resize their tokens due to being to fast.
That is something I would like to be able to block, just the resizing of their tokens. This way they can move about freely (cant edit their aura) without accidentally miss-clicking and filling the entire screen with a token.

I will open a new issue for re-sizing blocking / movement permissions.

**Comment by Kruptein** [comment]
Oh I see, the resizing thing is something I want to address in general by having a "play" and "build" mode which you can swap between. in play mode you shouldnt be able to resize things because that makes not much sense.

**Comment by Price454** [comment]
That actually sounds like the perfect solution. In "play" mode however it would be good to still be able to delete stuff.
For example I use the multi-line tool over doors to create fog behind the door.
If players open it, i simply remove the line and the room shows itself.

**Comment by Kruptein** [comment]
Yeah I still need to figure out some of the details as I indeed want to limit the DM having to swap between the two modes during play time.

I've been playing with the idea of some DM tool in play mode that is like a key or something to open doors etc from within play mode without having to change to the fow layer in build mode and changing the visibility of the door.

again, this is just ideas currently, but is an active thing I'm looking into for the next release
