### ISSUE TITLE
Map tool fixes

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#264]
I have 3 issues with the map tool currently

* You have to insert the numbers before you select a region.  It would just make more sense to do this on mouse up
* Sometimes you screw up and suddenly the map is gigantic or super small.  The above would help with that if it had a cancel option
* Even though the size might be right after use, the location the map jumps to is wrong, it should stay where it was in regards to the first mousedown or something similar.

**Comment by 10leej** [comment]
Ill be honest. I have no idea what the maptool even does. As far as I can tell it doesn't do anything

**Comment by Kruptein** [comment]
haha, valid feedback.

You use it on a selected shape to resize it, so that the selected region will occupy X by Y grid cells as specified.  You can see it in action [here](https://www.planarally.io/tutorial/in-game/first-session/#fitting-a-map-to-the-grid)

**Comment by PalasX** [comment]
Map jump isnt a huge issue, since it can be moved after, and with the alt+move function you can keep it from aligning to the grid, which is useful for those maps that have half-tiles around the edges.

Maybe disable snap-to-grid by default for the map layer? or make it a dm option toggle?

**Comment by Kruptein** [comment]
It indeed isn't a huge issue, but it would be nice if it didn't happen either :)

All snapping can be diabled by pressing the alt modifier during your operation. (You can also invert this behaviour in the user settings, but that's not yet released).

**Comment by PalasX** [comment]
Can i suggest that after a map resize that the tool selection be forced back to "Select", to avoid the issues with accidental clicks or forgot to put it back on Select before trying to drag a token?

At least until we get an "undo" feature ;)

**Comment by Kruptein** [comment]
Sure, I've been on the bad end of accidentally resizing something again myself so I know the frustration it can cause.

Do you think deselecting the current shape would be enough? As the map tool only works on selected shapes.
