### ISSUE TITLE
[Question/Feature request] Revealable FOW

### ISSUE THREAD

**Issue by ASMfreaK** [Kruptein/PlanarAlly#268]
I want to remove a part of map already discovered by players from FOW.
Is it possible?

**Comment by Kruptein** [comment]
Yes, you can use the draw tool's "reveal" mode, to override any fow.

You can read up a bit more about how lighting/vision works [here](https://www.planarally.io/docs/dm/light-shadows/)

**Comment by ASMfreaK** [comment]
Thanks! I get it now
