### ISSUE TITLE
unable to upload asset

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#269]
Tried uploading some map assets, it would seem I can't upload assets larger than 4mb in size, I am able to upload small one fine (84kb).
Was working with schemen with this on stream

**Comment by Kruptein** [comment]
I have files >20mb in my own assets so it definitely is possible.  There is no proper progress bar / uploading process indicator or such, so maybe you just have to wait for a bit ?  I don't know if @schemen saw any errors in the server log.

**Comment by Kruptein** [comment]
Do you see any errors in your web console by any chance ? (press F12 and then navigate to console)

**Comment by schemen** [comment]
I see quite a bit of that:

`2020-04-03 07:45:21,079 - ERROR - Shape {'type_': 'assetrect', 'uuid': 'cae76d1e-c5f9-4ead-b4a1-03af5d6753b7', 'x': -3322.549628631679, 'y': 3293.850101282267, 'floor': 'ground', 'layer': 'tokens', 'draw_operator': 'source-over', 'movement_obstruction': False, 'vision_obstruction': False, 'auras': [], 'trackers': [], 'labels': [], 'owners': ['XXXX'], 'fill_colour': '#000', 'stroke_colour': 'white', 'name': 'Othi', 'name_visible': True, 'annotation': '', 'is_token': True, 'options': '[]', 'badge': 1, 'show_badge': False, 'width': 100, 'height': 100, 'src': '/static/assets/d64309488a3800f92c3fa58a8051452df93107ee'} does not have an expected layer configuration (shape.py:450)
`

That is not related to uploads though. 
@10leej The server location is in switzerland, maybe your upload together with streaming was a bit slow?

**Comment by 10leej** [comment]
`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

Could be the case

**Comment by Kruptein** [comment]
I did a quick google and some people are reporting that error could be due to one of your browser extensions.  Could you try it in incognito mode or something with less extensions perhaps ?

@schemen ok that's actually good to know, it's a log for an error I had once, but never saw again, good to know it's actually still there. It's not harmful though, the function that logs the error also has a small hotfix, but ideally it shouldn't happen at all

**Comment by 10leej** [comment]
no errors using chromium private window so yeah probably an extension there.
very well could be the distance (Ohio to switzerland). I'll have to setup my own server (probably bang my head on the wall for that too) and give that a shot. For now Im gonna give it the good ole "I'll sleep now and try again later" approach since it's 4am here

**Comment by schemen** [comment]
Ok so, I was just able to upload a 118mb map. Loading the map to the grid also worked.
I think a upload indicator would be great, because I had to reload the page to see it updated - not sure if this is related to the infrastructure having a bottleneck somewhere.

**Comment by 10leej** [comment]
something that tells me something is working would be fantastic ;)

**Comment by Kruptein** [comment]
It's on my growing list of todo's :D It already has a ticket #141 .
I assume I can close this ticket for now then, if not feel free to reopen it.
Have a good night sleep ;)
