### ISSUE TITLE
Add discord link

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#272]
I created a discord server to discuss some things and announce releases and such.  It could be a better place to ask some questions instead of opening issues on gh.

I should add a link to it somewhere in the readme of this repo so that it's visible on the homepage.
Maybe also somewhere in the actual program, but that might be a bit too obnoxious.  To be decided.

The link for those interested: https://discord.gg/mubGnTe

**Comment by edmael** [comment]
Maybe a "Info" button or token to be placed in the login screen might be nice.
You can include there your information, the github link and the discord link.

**Comment by 10leej** [comment]
This issue can be closed now that it's in the dev branch right?
