### ISSUE TITLE
rulers and pings stuck on screen

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#278]
Same issue as #125 not sure it's the same problem generated a nice huge planarallyserver.log spamming me with errors. Not a big issue they cleared on a refresh.  

`2020-04-05 04:25:53,133 - ERROR - Shape {'type_': 'assetrect', 'uuid': 'f12e7999-9d66-4e48-9598-6303ca7d95df', 'x': 22002.214571854063, 'y': 11359.695793001432, 'floor': 'ground', 'layer': 'tokens', 'draw_operator': 'source-over', 'movement_obstruction': False, 'vision_obstruction': False, 'auras': [], 'trackers': [], 'labels': [], 'owners': ['Orcef'], 'fill_colour': '#000', 'stroke_colour': 'white', 'name': 'Oskar Brawnvi', 'name_visible': True, 'annotation': '', 'is_token': False, 'options': '[]', 'badge': 1, 'show_badge': False, 'width': 50, 'height': 50, 'src': '/static/assets/a2e244f9899cabc0488c55f64e416c29f65cb67a'} does not have an expected layer configuration (shape.py:450)`  

`2020-04-05 04:22:36,307 - ERROR - Shape {'type_': 'polygon', 'uuid': 'c10ef74a-c185-4ae8-a385-9fbd3e706c05', 'x': 21596.65602743788, 'y': 11294.01607263134, 'floor': 'ground', 'layer': 'tokens', 'draw_operator': 'source-over', 'movement_obstruction': False, 'vision_obstruction': False, 'auras': [], 'trackers': [], 'labels': [], 'owners': ['Dunerunner'], 'fill_colour': 'rgba(0, 0, 0, 1)', 'stroke_colour': 'rgba(0, 0, 0, 1)', 'name': 'Unknown shape', 'name_visible': True, 'annotation': '', 'is_token': False, 'options': '[]', 'badge': 1, 'show_badge': False, 'vertices': [{'x': 21568.981483208092, 'y': 11283.766241435123}, {'x': 21577.181348165064, 'y': 11263.266579042689}], 'open_polygon': True, 'line_width': '2'} does not have an expected layer configuration (shape.py:450)`  

`2020-04-05 04:22:15,763 - WARNING - Attempt to update unknown shape by 10leej (shape.py:237)`  

and finally  
`2020-04-05 04:22:06,744 - ERROR - Shape {'type_': 'circle', 'uuid': '1014fa42-512b-4c2b-ba3d-869f296038aa', 'x': 21500, 'y': 11400, 'floor': 'ground', 'layer': 'tokens', 'draw_operator': 'source-over', 'movement_obstruction': False, 'vision_obstruction': False, 'auras': [], 'trackers': [], 'labels': [], 'owners': ['Dunerunner'], 'fill_colour': 'rgba(0, 0, 0, 1)', 'stroke_colour': 'rgba(255, 255, 255, 0)', 'name': 'Unknown shape', 'name_visible': True, 'annotation': '', 'is_token': False, 'options': '[]', 'badge': 1, 'show_badge': False, 'radius': 34.340411713406766} does not have an expected layer configuration (shape.py:450)`

**Comment by Kruptein** [comment]
The errors are related to another bug I'm trying to track and are safe to ignore, there is a fix in place for it but I want to find the root cause.

Regarding the stuck rulers/ping; Can you reproduce this easily? Is there a specific circumstance you notice that they are stuck?

**Comment by 10leej** [comment]
Honestly whenever a plauer would use the ruler or ping tol it would stick. The ruler most often left behind just the text

**Comment by Kruptein** [comment]
yeah thing is I just can't reproduce it here :D are there some specific steps that reproduce it ?

**Comment by 10leej** [comment]
Well let me break it down because I'm not sure how to replicate it so let me break down on how I was running it.
Well I was running on a low spec vps with planarally in the docker container via port 8080
players were coming in via internet not local network, I was running it via Chromium  
Just whenever a player would use the tool it would stick on my screen, not theirs.

**Comment by 10leej** [comment]
Got a [screenshot](https://imgur.com/HvldRza)

**Comment by Kruptein** [comment]
I believe you it's just that I don't know what triggers it nor can I reliably reproduce it myself

**Comment by ZachMyers3** [comment]
This happens on my box as well, anything I can do to help capture it?

**Comment by Kruptein** [comment]
Well, I have no idea what causes it. Is there anything in the dev console that appears at all? Is there a certain step of actions that reliably reproduce it?

Those are the things I'm looking for.

**Comment by 10leej** [comment]
Been trying to reproduce it for a while now but it only happens during my sessions. I'm only running one campaign on PA right now.
Tried making fake player accounts and to reproduce and everything. Don't want to take time off the session to dig through the web console and not really getting any different errors in the log from what I posted earlier.

**Comment by Kruptein** [comment]
Understandable that you don't want to start debugging things in the middle of a session, I wouldn't want to do that either.  I have it on my radar is all I can say for now.

**Comment by 10leej** [comment]
Thankfully all I have to do is just refresh the webpage and it clear, really just a minor annoyance more than anything.  
Could very well be the fault of the internet pipe going from remote server to browser. Maybe

**Comment by ASMfreaK** [comment]
I'm experiencing the same issue. Logs are spammed with:
```
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to move asset it does not own (__init__.py:483)
WARNING - someuser attempted to remove asset it does not own (__init__.py:245)
WARNING - someuser attempted to remove asset it does not own (__init__.py:245)
```

**Comment by Kruptein** [comment]
Ok cool, that gives me some more info to work with, thanks

**Comment by chisaipete** [comment]
I experienced the same issue during a session last night as well. Similar setup: Ubuntu Server 18.04 for the planar ally server, Chrome browser in Win10 for the DM client. Players didn’t see the ping artifacts, only me while connected as DM.  Refresh clears.

**Comment by Kruptein** [comment]
I think this hasn't been happening anymore.
