### ISSUE TITLE
Light and vision bound to original browser window size even when maximized

### ISSUE THREAD

**Issue by PalasX** [Kruptein/PlanarAlly#292]
Expected:
Token's light radius and vision extend to the range set in their asset properties, and show other placed assets if they are within LoS. This assumes fog of war is on and LoS setting enabled. This should happen regardless of the window size, providing the player can see the asset in the browser window.

What happens:
Dynamic lighting and token vision seem to have some sort of hard coded limit to the number of pixels away from 0,0/origin/topleft that are included in calculation. possible based on size of browser window pre-maximize?
In normal DM mode, this results in lights hitting a "corner". in fake-player mode, it means your token has no vision and no light exists past this boundary.

![image](https://user-images.githubusercontent.com/37154966/79035964-41a49180-7b91-11ea-90ae-4c90a965a72e.png)
![image](https://user-images.githubusercontent.com/37154966/79035968-4ec18080-7b91-11ea-97bd-ff2bd08dbdeb.png)
 Version 0.19.3 - Precompiled Windows binaries
Using Chrome. replicated on 16:9 monitors at 1080p and 4k.

**Comment by Kruptein** [comment]
Does this persist after you reload the page?

I've noticed myself that if I move my window to another screen some aspects (e.g. the lighting) still use the old resolution.

**Comment by PalasX** [comment]
Does not persist after closing the tab and re-opening page in a new tab, which is an easy work around.
