### ISSUE TITLE
scrollbar for long location names

### ISSUE THREAD

**Issue by jirsat** [Kruptein/PlanarAlly#293]
If the location name is long enough, scrollbar appears on location bar, even though there is enough space above and below text for name to be displayed fully. 
Encountered with Firefox and Chrome on Windows.

**Comment by 10leej** [comment]
how long of a name are you using? Im unable to replicate on 0.19.3

**Comment by jirsat** [comment]
Example: "Pevnost ledový pukléř"
I'm on 1920x1024 +1024x9xx screens. I'll try to replicate tommorow on laptop with Linux to see where is the problem.
Could be due to á,ř...

**Comment by Kruptein** [comment]
Fixing your current issue shouldn't be hard, but the location bar is in due need of a UI overhaul anyway

**Comment by chisaipete** [comment]
I experienced this on dev latest last night “Broken Handle Tavern” breaks with large line gaps and the location toolbar has a scroll bar. On the right edge.  I think you just need to make the browser window narrow enough to force the text to not fit in the location square.

**Comment by Kruptein** [comment]
The location bar has been reworked in the new version, so hopefully this issue is also covered. If not feel free to re-open.
