### ISSUE TITLE
Unable to build Docker Image on ARM

### ISSUE THREAD

**Issue by jirsat** [Kruptein/PlanarAlly#308]
I tried to build docker image from dev branch. It failed with status code 1 on step 17/19 while installing build dependencies for bcrypt.

> 
> ERROR: Command errored out with exit status 1: 
> 
> command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f_ou07r8/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f_ou07r8/cffi/setup.py'"'"';f=getat$           cwd: /tmp/pip-install-f_ou07r8/cffi/ 
> 
> unable to execute 'gcc': No such file or directory
> 
> No working compiler found, or bogus compiler options passed to standard "distutils" module.

OS:   Raspbian GNU/Linux 10 (buster) armv7l
Host   Raspberry Pi 4 Model B Rev 1.1
Kernel:   4.19.97-v7l+
Docker version 19.03.8, build afacb8b

**Comment by jirsat** [comment]
Adding build-essential libffi-dev helps with bcrypt, but error occurs while building cryptography and preserves even if openssl is installed

**Comment by jirsat** [comment]
Solved by #309

**Comment by Kruptein** [comment]
hm this did double the docker image size which is less ideal.
