### ISSUE TITLE
Firefox performance is noticeably worse compared to chromium

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#31]
Whereas panning is very smooth in chromium based browsers, it feels very jagged in firefox.

**Comment by Kruptein** [comment]
actually kinda everything seems to have much worse performance in ff

**Comment by Kruptein** [comment]
the FOW layer draw method is the culprit taking up to 2.5 seconds on FF whereas it never exceeds a second on chromium.

**Comment by Kruptein** [comment]
Some drastic improvements have been made on the dev branch.

There is however still a noticeable performance difference that seems to mostly stem from the es6 implementation in ff.  targeting es5 gives noticeably better performance in ff.

**Comment by Goury** [comment]
Current release feels very smooth in my 67th and 68th Firefoxes

**Comment by Kruptein** [comment]
Thanks for verifying, I personally feel like it has been running better as well.
