### ISSUE TITLE
Map resize does not replicate

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#311]
I'm using Planar-Ally 0.19.3 on a Linux basis (please ask specifics if you need them), accessing with Firefox 75.0. My players use different browsers, I think, but I know of Firefox being used, as well. I'll ask them for specifics, if you need them.

Map resize functions quite well, but would not replicate to my players. Thus, while my map is aligned with the grid, the one they see, is not.

**Comment by 10leej** [comment]
I don't have this problem and am unable to replicate the issue. I would naturally assume this could be an issue on the browser side.  
Try refreshing the page (players included), clearing browser cache, including rebooting the server instance/docker container.

**Comment by dthv** [comment]
Refreshing pages was tried multiple times by everyone, did not fix.
If it's an issue on the browser side, most likely on GM's side, because no one out of five players could see the adjusted map.

Does PA need any cookies etc. that could be prevented/hindered by strict privacy settings?

I will try clearing browser cache and server reboot asap and report back. Thanks for your fast reply!

**Comment by 10leej** [comment]
PA does not use or save cookies as far as I know. I do know that asset placements are saved in the /data/planar.sqlite file could be an error occurred there but outside of nuking and remaking it from scratch I'm not certain on a fix for that.

**Comment by Kruptein** [comment]
Is there anything in the web console of the DM (or the players) or in the server log that is popping up ?

**Comment by dthv** [comment]
I've just checked: Nope.
I'm not sure what you mean by "web console", though. Server log is empty (on this specific issue).

**Comment by Kruptein** [comment]
Somehow forgot about this issue sorry for that!, Has this problem persisted in other sessions?

**Comment by dthv** [comment]
Sort of. Resize actually does replicate if it's done while the players are not logged-in in the session. So, as work-around, I either prepare maps in advance (which is always better using a VTT, anyway) or ask the players to log-off for me to upload and resize a map. When resize is done _before_ the player downloads the map, it seems to work fine.

This sounds even more like an issue with browser cache, but when I tried, re-loading while clearing cache did not work.

> Has this problem persisted in other sessions?
Well, I did not open a whole new session to try out whether it persists only to a certain session. I will take some time in a few days and give it thorough testing. I will probably upgrade to 0.20.0, though, as the release-notes alone are GREAT. :)

**Comment by dthv** [comment]
Problem persists on 0.9.13 and 0.20.1, tested with both Firefox 76.0.1 and Chromium 81.0.4044.138 as both DM and player(s).

Interestingly, the resize isn't even saved. Thus, reloading as DM snaps the map back to its original size.

**Comment by Kruptein** [comment]
it's so weird :p

**Comment by chisaipete** [comment]
Sounds like the resize isn’t being updated in the database for some reason. I wonder why?

Is the communication from the client making it to the server? Is the breakdown when trying to update the database?

**Comment by dthv** [comment]
> Sounds like the resize isn’t being updated in the database for some reason.

I concur.

Yet, I have no idea how to answer your questions. :-/

**Comment by dthv** [comment]
Interestingly (and to my complete satisfaction), it does no longer occur in 0.21.0. Yay! :D

**Comment by hmqgg** [comment]
Reproducible after PR #451 `event-improvements`.

**Comment by hmqgg** [comment]
And the workaround is to rotate the map shape after resizing, then rotate back. (let the client update the shape to the server)

**Comment by Kruptein** [comment]
Unsure why I added this to the 0.24 milestone as it was already fixed at that time
