### ISSUE TITLE
Feature: Grid Unit Size supports floats

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#312]
We are using the metric system to measure distances. 5 ft equal 1.5 m, roughly. There are several workarounds I thought of, but making Grid Unit Size supporting floats would be the most convenient way to support this measurements.

While I'm not quite the guy for coding python or coding in general, I'd be willing to give it a try, if someone was so kind to point at the right files to search in for the relevant function(s). Thanks!

Unrelated: Great software, I instantly fell in love with it! :)

**Comment by Kruptein** [comment]
you can actually change to metric system.  In your grid settings you can change the 'size unit' to m :)

**Comment by dthv** [comment]
Yes, I know. But the unit has to be an integer. But this issue was not about "size unit", it was about "unit size". "unit size" only accepts integers. If one uses D&D's 5ft measurements but translated into the metric system, one field is 1.5 m square, as 1,5 m is approximately 5 ft.

This is not about "ft" or "m" in the display.
This is about the size of one single unit / field accepting float instead of int.

**Comment by Kruptein** [comment]
Ah my bad.

**Comment by dthv** [comment]
Well, I actually need to clarify (MY bad):
The float is actually accepted by the engine (I could swear it was not, a few days ago, but maybe that was just a layer-8 problem), but the input-field glows red as if it was erronous. Also, the output seems to be rounded. Maybe it could be rounded to nearest .5 if input was float?

**Comment by Kruptein** [comment]
I was just looking at this, but don't have the red outline myself:
![image](https://user-images.githubusercontent.com/1814713/82140216-6514c900-982e-11ea-8f96-68e795af5875.png)

The rounding you were talking about is that specifically the ruler? Because I confirm that.  If there are other places do let me know :)

**Comment by Kruptein** [comment]
I've merged the change to show 1 decimal point in the ruler to dev.

**Comment by dthv** [comment]
> I was just looking at this, but don't have the red outline myself:
![float-error](https://user-images.githubusercontent.com/11358285/82143034-29372f00-9841-11ea-9a1a-eb4382e0f290.png)
This is how it looks with me (still 0.19.3, though).

`user@host:~$  firefox --version`
`Mozilla Firefox 76.0.1`

> The rounding you were talking about is that specifically the ruler? Because I confirm that. If there are other places do let me know :)
Yeah, that's specifically the ruler. I did not encounter size-unit / unit-size anywhere else, yet.

**Comment by Kruptein** [comment]
Ah I see, can confirm that this happens on firefox. Should be an easy fix.
