### ISSUE TITLE
Touchscreen Support Missing

### ISSUE THREAD

**Issue by hakarune** [Kruptein/PlanarAlly#313]
I have 2 windows 10 tablets with touchscreens, 2 android tablets, an iPad and multiple android phones and touchscreen interaction is missing. 

When trying to use touch to move tokens, slide on screen, etc nothing responds correctly if at all. I'm unable to even touch tokens with a touchscreen meaning moving them is not possible. Being to have of of any of these tablets in the center of the table and be usable to players would greatly improve the use for playing. Even if the touch only allowed for token movement, as the DM I can force all players to the area I want in view or zoom to the character, so moving through the map with touch is not a high priority, but moving tokens I feel it a must have.

**Comment by Kruptein** [comment]
Hey, I don't have a touch device myself, which makes it slightly harder for me.  That said, someone did add some basic touch support in the last release, so I'm curious why it's not working.

To bring all players to a certain area you can as a DM right click an empty place and select "bring players".  Additionally players will be able in the next release to focus their own characters with the spacebar.

**Comment by ZachMyers3** [comment]
What release are you running on? Like Kruptein said I created touch events for all the canvas events and they're working fine on my Windows 10 touch device.

**Comment by hakarune** [comment]
> What release are you running on? Like Kruptein said I created touch events for all the canvas events and they're working fine on my Windows 10 touch device.

I just went to check the version I was running and it appears my rocket auto update has not been working. The image I'm running is over 30 days old and docker hub of saying there's been multiple new versions since I last updated. I will update it and see if the issue it's still present. Thank you for the quick response.

**Comment by ZachMyers3** [comment]
The touch integrations have been added in the last couple releases. If you update and still are having issues let me know.
