### ISSUE TITLE
Recent socketio/engineio versions don't work

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#315]
A user encountered the combination of:
```
python-engineio   3.12.1
python-socketio   4.5.1
```
To result in a broken server, producing `ValueError: Too many packets in payload` errors upon any interaction with a socket.io connection.

A first measure to stop this from happening is to fix the dependency file as mentioned in issue #314 .
A second step is investigating what is going on in these versions.

**Comment by ZachMyers3** [comment]
Just pulled the dev branch to try and reproduce this and I'm not having any luck. Here's my ```pip freeze```

```
aiohttp==3.6.2
aiohttp-jinja2==1.2.0     
aiohttp-security==0.4.0   
aiohttp-session==2.9.0    
async-timeout==3.0.1      
attrs==19.3.0
bcrypt==3.1.7
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2       
idna==2.9
idna-ssl==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
multidict==4.7.5
peewee==3.13.2
pkg-resources==0.0.0      
pycparser==2.20
python-engineio==3.12.1   
python-socketio==4.5.1    
six==1.14.0
typing-extensions==3.7.4.2
yarl==1.4.2
```

I just did a ```pip install -r requirements.txt``` and ran the server, created a room, and started building objects and haven't seen any error messages.

**Comment by Kruptein** [comment]
Interesting, I haven't tested it myself yet, but downgrading those two did solve the user on dc. I'll label it wontfix for now, but I do want to do a quick test myself later.

**Comment by ZachMyers3** [comment]
Here is the user's pip freeze, the only difference I see is the cryptography version. 

```$ venv/bin/pip list
Package           Version
----------------- -------
aiohttp           3.6.2
aiohttp-jinja2    1.2.0
aiohttp-security  0.4.0
aiohttp-session   2.9.0
async-timeout     3.0.1
attrs             19.3.0
bcrypt            3.1.7
cffi              1.14.0
chardet           3.0.4
cryptography      2.9.1
idna              2.9
idna-ssl          1.1.0
Jinja2            2.11.2
MarkupSafe        1.1.1
multidict         4.7.5
peewee            3.13.2
pip               20.0.2
pkg-resources     0.0.0
pycparser         2.20
python-engineio   3.12.1
python-socketio   4.5.1
setuptools        39.0.1
six               1.14.0
typing-extensions 3.7.4.2
yarl              1.4.2```

**Comment by Kruptein** [comment]
Yeah I doubt that would be the cause of this issue.

**Comment by chisaipete** [comment]
I'm that user! I was running 3.6.9 as well. I'll see if I can reproduce.

**Comment by jclds139** [comment]
I ran into a related problem. Since the `python-engineio` version isn't specified at all in `requirements.txt`, pip installs the latest version. Since the most recent version isn't compatible, can we specify `python-engineio<4.0.0` in the requirements so we get the last good version?

**Comment by Kruptein** [comment]
A quick fix can indeed be made in the requirements, I would like to see what is new in engineio 4.0 and maybe upgrade

**Comment by Kruptein** [comment]
I think I'm going to update the entire stack to the new socket.io version as it allegedly fixes one of the things that I've been noticing as well, frequent disconnects
