### ISSUE TITLE
Add invisibility to Tokens

### ISSUE THREAD

**Issue by chisaipete** [Kruptein/PlanarAlly#318]
**Is your feature request related to a problem? Please describe.**
A player would like to have an invisible familiar: private visibility to them (like auras).  They want to be able to move and manipulate their familiar token, but not reveal location to the players.

**Describe the solution you'd like**
A toggle for invisibility for tokens, similar to aura toggles.  There may also need to be an override or visual cue for the DM.

**Describe alternatives you've considered**

**Additional context**

**Comment by chisaipete** [comment]
I don't see the invisibility toggle/checkbox, running latest dev?

**Comment by Kruptein** [comment]
It should be there in the properties dialog right below the is token toggle

**Comment by chisaipete** [comment]
Oh, there it is, silly me.  I must have missed it all the times I looked ;)

**Comment by Kruptein** [comment]
so just to be clear for now it will be completely invisible to other players without edit access, but just be visible as a normal shape to those with edit access.  I'll probably want to add something UI wise to make it clear that a shape is invisible without having to check its properties.
