### ISSUE TITLE
Calculator in Initiative Tracker and Quick Edit Token Fields [FEAT]

### ISSUE THREAD

**Issue by chisaipete** [Kruptein/PlanarAlly#321]
**Is your feature request related to a problem? Please describe.**
When I was tracking HP for monsters using a Tracker field on their associated token, I would click and it would ask for a new value.  I’d have to pull up a calculator to input the value properly, it would be nice if the field would support basic calculations.

**Describe the solution you'd like**
When clicking on an input field for numbers/trackers it should support basic calculation processing: it presents with the current value (20) and to input taking 7 damage, the user simply can type (-7) and the tracker resolves to (13).

**Describe alternatives you've considered**
Alternatively, you can just use your brain or a calculator and then input the final value.

**Additional context**
YNAB.com (budgeting software) has this kind of inline calculator option which makes for a nice UX.

**Comment by Kruptein** [comment]
It actually supports things like `+5` or `-20`

**Comment by chisaipete** [comment]
Oh! Let's document that, it's great! I must not have actually tried it.
