### ISSUE TITLE
Set spawn location for players

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#343]
Discord conversation:

> 7:44 AM] LuggasDM: Just a short queston? Can I control where my players while spawn when they the location of their token is changed
> [7:44 AM] LuggasDM: Sometimes we have to seek for a while, espacially if one location has another scale than the otcher
> [7:44 AM] LuggasDM: *other
> [11:50 AM] 👻 Kruptein 👻: how would you envision this working
> [11:51 AM] 👻 Kruptein 👻: I believe currently they keep their x/y coords from the location they came from
> [11:51 AM] 👻 Kruptein 👻: I understand this is not the best method
> [11:51 AM] chisaipete: Like having a marker as a spawn relative position?
> [11:51 AM] 👻 Kruptein 👻: but I'm curious what you would suggest UI/UX wise
> [11:51 AM] 10leej: I like the idea of something like a "spawn marker" asset to dictate a location where players would appear.
> [11:52 AM] 👻 Kruptein 👻: alright seems plausible
> [11:52 AM] 10leej: I'll open an issue for it
> [11:53 AM] chisaipete: Like, a property on a marker, and then you can select a radius for spawn as well

**Comment by BlandSauce** [comment]
An addition to this, allowing for multiple spawn points on a map, and somehow asking the DM which one to use when transferring would be a nice extra.
And be sure to leave out that selection step if there is only one spawn point available.
