### ISSUE TITLE
[FEAT] Decouple "Move token"-/"Edit trackers"-permission from "Edit token"

### ISSUE THREAD

**Issue by Pattn** [Kruptein/PlanarAlly#353]
As a DM I'd like to prevent players from messing with the token configs, auras, etc. but still let them move the tokens. (ex. spoilers by sudden lighting aura in a dark map setting)

No combination of Edit/Vision config prevents malicious/accidental messing with tokens without removing token control from the player.

**Comment by Kruptein** [comment]
I'm not sure yet whether a specific permission for editing trackers/auras is something I want to do.  At that point there is not much point to not give full edit access in the first place.

**Comment by Kruptein** [comment]
This has been implemented for the movement part.  I'm going to close this for now as I think the latter part is currently not interesting.
