### ISSUE TITLE
[BUG] ??? How to Upgrade Docker Image And Keep Campaigns

### ISSUE THREAD

**Issue by freddyyeddy** [Kruptein/PlanarAlly#363]
**Describe the bug**
I See no facepalm or written out method of doing this kind of Upgrade an existing server. I have several hours into building a campaign and some of the permission/Player Control options hat have been recently rolled out would be ideal. 

TLDR: I cant figure out a way to update my docker image and keep my campaign data

**To Reproduce**
I am using a personal synology server to host my PA server. The docker package on here only allows me to update to latest version with the "Clear" Command.

Perhaps This is a case of Me not understanding What Im Doing More than an PA problem.

**Expected behavior**
Some Either Concise Way To Update Within PA itself Instead of Though Docker, Git Ect. Or Someone who know more than me to add to documentation what i need to do to achieve and update/upgrade of an existing docker PA server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Synology 
 - Browser None (Talking About Docker Image)
 - Version  Any Current Version

**Comment by Kruptein** [comment]
The idea is that you mount your save file and assets from the host file system in the docker image.

So something like `docker run -v /home/freddy/planar.sqlite:/planarally/data -v /home/freddy/assets:/planarally/static/assets ...`

I should add it to the documentation somewhere indeed.

**Comment by Kruptein** [comment]
It actually is documented I just notice: https://www.planarally.io/tutorial/setup/self-hosting/#docker-container
