### ISSUE TITLE
[FEAT] Toggle public visibility of Ruler tool

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#369]
Currently, the Ruler tool is publicly visible for all players.
Sometimes, at least as DM, I want to measure something that is not publicly visible, e.g. line of sight or distance from an invisible opponent the location of which would be revealed.

I would like to have a function that toggles visibility of the Ruler tool.

This could either be a feature for all players, i.e. a toggle to display the Ruler private/public.
Or it could be limited to the DM and maybe depend on whether the DM measures on the DM layer or on other layers.

I would prefer the toggle for all players, though.

**Comment by Kruptein** [comment]
I'll probably add this with the option for all players in mind with a simple toggle like the draw/map tool have options
