### ISSUE TITLE
[Question] Why does the client load the local jQuery in-game?

### ISSUE THREAD

**Issue by AntiSC2** [Kruptein/PlanarAlly#38]
In both login.jinja2 and rooms.jinja2 we have the following html to load jQuery:

`<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>`

If it fails to load from the CDN it goes on and loads the local file instead. But in the planarally.jinja2 it looks like this:

`<script src='/static/extern/js/jquery-3.3.1.min.js' integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="></script>`

It is not a problem necessarily but I just thought it was odd. Why not use the same method as in login.jinja2 and rooms.jinja2?

**Comment by Kruptein** [comment]
It used to be the same in-game. I've removed it there and apparently forgot to also remove it from the two other locations.

As to why I removed it: I personally felt that in those cases where you have no internet access, it took longer than I desired for the script to notice this and fallback to the local version.  As this is self hosted software, I also don't envision the server having to handle a lot of requests for this local js file so using a CDN might have been a premature optimisation on my end.

Does this make sense to you ?

**Comment by AntiSC2** [comment]
Well now that I think about it, because it is self hosted it does make more sense to use the local file. Also like you said, there is not going to be that much load on the server so it does make sense to only use the local file for now. Closing this issue then when the changes have been made.
