### ISSUE TITLE
[BUG] Change of name of object does not replicate into Initiative Tracker

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#385]
When the name of an object (non-Basic Token, non-Asset) is changed, this change is not replicated into the Initiative Tracker.

To reproduce, add a shape via the drawing tool (not a Basic Token, not an Asset) and add this shape to initiative. It is added with its name to the list. Now change the name in the object's properties. The change is not reflected in the item.

Expected Behaviour would be to change also the name of the token within the Initiative Tool when changing the name in the properties.

**Comment by Kruptein** [comment]
I can no longer reproduce this seemingly.  Might have been partly fixed in 0.23 with the edit dialog rework.

That said shape names don't properly sync so other clients don't see the changes, but that's not initiative specific

**Comment by Kruptein** [comment]
Ok no, I did manage to reproduce it under specific circumstances.
