### ISSUE TITLE
[BUG] Initiative Tool takes 'text' of Basic Token, not name

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#387]
When a Basic Token is added to the initiative list, the text displayed on the token is taken as a designator in the list and not the name as of the properties dialogue.

According to kruptein on the discord,

> the initiative should just take the name of the properties for everything including basic tokens.

**Comment by Kruptein** [comment]
This actually is already taken care of in the code.  If the name of the token is empty or 'Unknown shape' it will use the label instead.  In all other cases it will use the name itself.

This along with the just merged change that basic tokens will have their name by default set to their text fixes this.
