### ISSUE TITLE
Option to Draw object or on layer for FOW

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#42]
First off, love the project so far! I'll see if I can dockerize it nicely to use it with docker swarm :) 

What I want to suggest is a simplified FOW System for in-person sessions where we could use PA as virtual tabletop.

Streaming the players view (via chromecast probably) on a screen flat on the surface, the FOW System is cool but without tokens in game (more like physical minis) we can't use the dynamic light.

Is it possible to create a draw tool that allows to actually draw on the layer instead of creating shapes that enable seeing/blocking?
This drawing could also be used to create objects that are blocking light for example.

This would allow a DM to draw on the FOW layer, removing it or adding to it and thus making it possible to use it nicely for in person sessions :)

**Comment by Kruptein** [comment]
Hi, I'm not entirely sure if I understand the question right, but I believe that what you want already exists.

So you indeed have the dedicated fow layer, where by default everything drawn is both vision and movement blocking.  This can be changed per shape but is quite cumbersome.

So instead there is also the FOW tool, not to be confused with the fow layer.
This tool can be used from any layer, and has a toggle to show or hide a region you select regardless of any dynamic light going on.

Is this what you meant ?

Thanks for trying the tool!

**Comment by schemen** [comment]
Mh lemme try to explain it better :) 

I would love to have the FOW layer that is some sort of a mask that I can edit, like in photoshop. Edit the mask directly to what is visible or what isn't. For that, creating objects (squares and circles) to define what is visible and what isn't is a bit hard so I thought that it would be great if we could edit that layer mask directly with a brush.

https://github.com/apclary/dungeon-revealer this project implements something like that, sadly it always requires a refresh hence why I am very excited about this project and :) 

Btw, disabling LOS in the DM setting doesn't really chance anything funny enough! Maybe I am doing something wrong though.

**Comment by schemen** [comment]
Very sweet, yes indeed that is what I am looking for :) !

When I use the FOW tool to "hide" things again it gets hidden for the DM as well, by the way! A brush that simply edits the mask instead of creating objects would be really great!

This is a square object created by the FOW tool that has reveal off:
![image](https://user-images.githubusercontent.com/5279155/42219835-801fb236-7ecd-11e8-8437-2f1496277720.png)
It currently doesn't turn the opacity back on but creates a new object that blocks.

Am I understanding this correctly?

**Comment by Kruptein** [comment]
It's indeed a new object that obscures an area, (a token with a lightsource would pierce through it though).
If it also hides stuff for the DM than that's a bug :D.

The way I would use that tool, if I'm not using the dynamic lighting, is to have the DM option to fill the entire screen with fog on, and then use the reveal part of the fow tool to show things.  The downside is that it's only rectangular atm.

That said, I see merit in the masking stuff you propose and will try to implement it today/tomorrow but initially as a special separate mask layer, because combining the shapes and the mask will require a bit more tinkering.

**Comment by schemen** [comment]
Ah alright, sweet - no problem with that :) A simple FOW layer and the dynamic FOW layer

If dynamic light is wanted, you could create "objects" with the brush as well? Like, use the brush to create a bigger object

Btw, I have a setup running on docker swarm  fully dockerized. Still have a small issue with logging but I'll see to that.

**Comment by schemen** [comment]
Heyo! Good work so far! So onto the report :) 

- It seems that the hide function is still creating a object that has no opacity:
![image](https://user-images.githubusercontent.com/5279155/42333010-da7a6f84-8079-11e8-9ec1-2c18aa313896.png)

- When you zoom, the size and shape changes of the brushed area, meaning depending on how you zoom you reveal more or less

Enhancement:
- Any way to see the brush size preview?

Btw, I got it fully dockerized, you can check out a version running on a swarm cluster here: https://dnd.schemen.me
https://github.com/schemen/PlanarAlly/commits/master

**Comment by Kruptein** [comment]
Hi, 

- **It seems that the hide function is still creating a object that has no opacity**
       Yes this is for practical reasons regarding synchronization to players.  If it is just for yourself I could easily do a simple masking layer as we discussed earlier.  The problem arises when you want to synchronize your brush strokes to other players as then you would have to send the current complete canvas image data which is much more data.

  That said, I'm gonna look into other things that I probably overlooked to make things easier, I forgot to adjust the opacity of the hide brush which is the primary reason you noticed this method.  If I for the time being fix the opacity, is that ok for you while I look into something better?  or if you have suggestions to synchronize canvas brush strokes, feel free to give them.
- **When you zoom, the size and shape changes of the brushed area, meaning depending on how you zoom you reveal more or less**
    This is simply an oversight on my end, I'll fix it when I get home in ~1 hour
- **Any way to see the brush size preview?**
    I'll see how fast I can add it, but it definitely is a good idea.

Thanks for testing it!

**Comment by schemen** [comment]
Yeah, actually if you could add the added FOW Opacity to FOW objects as well maybe?

Lemme know when I can test more!

**Comment by Kruptein** [comment]
Ok I fixed the opacity on the brushes and made it so you always have an active brush tip to properly estimate size and effect of the brush.

I've also fixed the opacity on the FOW tool.
I've deliberately not added the opacity to the other fow objects drawn on the fow layer itself, because these are hidden by default if you switch to another layer and I wanted to properly show them on the FOW layer for this reason.  I could add some DM setting to finetune it to your needs.

**Comment by schemen** [comment]
Heh very nice thought. You still want light blocking objects to be visible, that makes sense :)

**Comment by schemen** [comment]
I just tested the latest code and it seems to bug out when you try to mix reveal and hide on the same part of the map, not really sure what to do :D

**Comment by Kruptein** [comment]
Can you provide a screenshot or something?

**Comment by schemen** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/5279155/42508909-8b659cfa-844a-11e8-9e99-3ba0585d417a.png)
![image](https://user-images.githubusercontent.com/5279155/42508938-97882a34-844a-11e8-97e1-daeeb4b3df97.png)

**Comment by schemen** [comment]
Mh, I simply draw over the same place with hiding/revealing brush

**Comment by Kruptein** [comment]
Do you have the DM setting "Fill entire screen with fog" enabled or not ?

**Comment by schemen** [comment]
This I do, yes

**Comment by Kruptein** [comment]
I fixed the issues, I've update the branch BUT be aware that in its current state it will not synchronize with other players, I'll make it properly sync tomorrow.  But if you have time you could already try it out and see if it behaves as you expect.

**Comment by Kruptein** [comment]
A bit later as planned, but I updated the brush branch with code that should now correctly work across multiple clients.  Note that I've tested this in a clean session, so I advise you to remove any of the shapes drawn with the brush tool earlier before updating your branch.

If you have important save data, be sure to backup before upgrading.

**Comment by schemen** [comment]
Sweet! I will test this out :) 

I currently do not have any save-data, I'll just delete the stuff :)

**Comment by schemen** [comment]
I can confirm that this is now working! :D
