### ISSUE TITLE
[FEAT] (i18n) Issue Warning if translation is outdated

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#420]
Many changes to the software make updates or changes of the language strings necessary. In order to not fall back to the 'standard' lang of the software, every translation has to follow these updates.
At the moment, with only two translations by two somewhat active users, this should be no problem. But, hopefully, there will be more languages. And, despite one hopes not, translators might get drawn away.

In case of translator-drop-out, a little "warning", combined with a request for help in translation would be nice. It could e.g. show up near the language selector in the Client Settings and say something like "The translation for the language you set is incomplete. Thus, you might encounter text in english (maybe a variable for "standard language"). If you want to improve this translation, go over to github…" or something.

In case the translation is actually up-to-date, there could instead be a display saying something like "Parts of the translation don't feel right? Go over to github…". Since not every developer is literate in every language, actively asking for help in this specific context a bit more proactively, seems appropriate to me.

To determine whether the translation is complete, or not, I think it's sufficient to simply compare the m-time of the language files: Since the translations follow the standard-language of the software, these files have to be newer to be possibly complete. On the contrary, if the standard language's file is newer, the translator(s) of the other languages obviously missed something.

This workflow should, of course, entail a simple "touch" to all other language files, if just a typo in the standard-language was corrected.

Another possibility would be a variable for m-time within the language's json-file to be updated on any non-trivial change of the language.

**Comment by hmqgg** [comment]
If a feature updates and it needs to change the wording, instead of still using the old keys but only changing the English translation silently, I think it's better to remove the old keys and add new translation keys.

But yes, we could set up a new CI and run `i18n:report` for each commit, and if there are missing keys, create an issue for that language.

**Comment by Kruptein** [comment]
I see the appeal of invalidating old keys for easier detection of missing translations, however it also means that when you update a key. suddenly all languages will show the english text until someone fixes it even if the original translated string may very well still be correct or close.

What about a #language channel on the dc server where changes to en.json are reported so that language owners can act on it?

**Comment by dthv** [comment]
> What about a #language channel on the dc server where changes to en.json are reported so that language owners can act on it?

That would, indeed, support translation. I'd very much like to see this!

However, it requires that there's a translator actively reading that chan. Again, now, this seems not to be a problem. But the more languages PA supports, the higher the probability that translators will drop out, eventually. In these cases, the proposed feature could communicate "hey, there's actually nobody working on the issue and maybe none of the devs can – why don't you step in as you obviously do speak the language?". So, at least in principle, I want to uphold the original feature proposal. Maybe limit it to only show up in stable releases, but not dev-builds?

**Comment by chisaipete** [comment]
What about adding a "translator" role to discord that can be pinged when changes are reported to the #language channel?

**Comment by Kruptein** [comment]
I think for now the #language channel seems to work fairly well ?

I'm going to close this for now, but feel free to react if you disagree

**Comment by hmqgg** [comment]
I guess it would work even better with a translation maintainers group to mention every time localization updates as @chisaipete mentioned.
