### ISSUE TITLE
[FEAT] Make Map Tool able to resize whole asset

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#424]
Virtually always, one has to resize maps to seamlessly fit under the grid. This has greatly improved by the last rework of the Map Tool, but not yet perfect. Especially on bigger maps, an offset of just one or two pixels can mean increasing inaccuracy of the fitting between map and grid towards the lower right corner of the map.

I know that there are thoughts and talks about a major rework of the asset import system (and am looking forward to that). But until then, I would like to propose a (probably?) much simpler quality-of-life improvement: Make the Map Tool able to resize a whole asset.

This could be a simple checkbox in the "drag an area you wish to resize"-dialogue that, being clicked, immediately leads to the x by y resize dialogue.

I considered the alternative that a dragged area bigger than the actual asset could automatically snap to the size of the asset. But that brings the disadvantage that this will only function with assets that have only "full" squares, i.e. no cut squares on the edges.

**Comment by chisaipete** [comment]
I was under the impression that the map tool creates a scaling factor that is applied to the whole asset.  I don't follow what issue you are seeing.  Sometimes images aren't made with a proper grid and no amount of scaling is going to fix it.

**Comment by dthv** [comment]
Indeed, the map tool scales the whole asset. But one has to exactly hit the grid as on the asset (which definetly *has* a proper grid, since it fits seamlessly if imported before the first use of the zoom tool) which, honestly, I almost *never* achieve to do.

It would be very much easier for me to just count the squares on my map and input "this whole map is x by y squares big" than to resize four or five times until it's "good enough" that the ruler will work and then disabling the PA grid so the offset won't interfere, visually.

**Comment by Kruptein** [comment]
You can readjust the selection you make before applying the map tool though.  Since the new iteration of the map tool I've had almost no cases where I had to redo something.

Also in general bigger areas will provide better approximation.

**Comment by dthv** [comment]
I know.
I'm probably just *very* clumsy, I suppose. :-/

**Comment by oeykmiih** [comment]
I second this, although the "Map" tool woks great, it would be easier insert maps and align them to the grid if somehow you could determine the length and width of a map in grid units
