### ISSUE TITLE
[BUG] CentOS 8 install fails.

### ISSUE THREAD

**Issue by theone85ca** [Kruptein/PlanarAlly#434]
I apologize, I'd check Discord or the link for support but I wasn't sure where that might be.

**Describe the bug**
Installing using the instructions at the link below seems to be successful, however after running the planarsever.py and attempting to load the site, the following error is generated and the site never loads.

I'm also not able to find the folder or files associated with this error. There is no /templates folder inside of the server folder.

`FileNotFoundError: [Errno 2] No such file or directory: 'templates/index.html'`

Instructions: https://www.planarally.io/tutorial/setup/self-hosting

**To Reproduce**
1. git clone the repo into a folder on a fresh CentOS8 install.
2. cd in to the server directory and run `pip3 install --user -r requirements.txt`
3. run `python3 planarserver.py`
4. Load the page from the servers public IP address
5. Observe the error on the server and receive an `ERR_EMPTY_RESPONSE` message in Chrome.

**Expected behavior**
PlanarAlly should load in the browser with no errors in the console.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: CentOS 8
 - Browser: Chrome
 - Python Version: 3.6.8

**Comment by dthv** [comment]
cf #218 – if you clone the repository, you first have to build the js files by yourself.

You can also use a binary file of the latest release.

**Comment by Kruptein** [comment]
Exactly what dthv said.  If you clone the repo you'll also need to build the client.  If you don't want to do that use one of the `-bin` release files which have the client prebuild
