### ISSUE TITLE
[BUG] dialog background is cut at the right side in Firefox and some other browsers

### ISSUE THREAD

**Issue by Goury** [Kruptein/PlanarAlly#435]
**Describe the bug**
Subj

**To Reproduce**
1. Open a token's properties in Firefox.
2. Look at it
3. Background is missing on the right side

**Expected behavior**
To have background for the entire dialog

**Screenshots**
![Снимок экрана от 2020-06-18 12-43-45](https://user-images.githubusercontent.com/1081221/85005432-7456a180-b161-11ea-9b63-f7656e3a94f3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 on client, Ubuntu 16.04 on server
 - Firefox 68-77
 - 0.21.0

**Additional context**
*additional context was removed by Kruptein's request*

**Comment by dthv** [comment]
I can confirm this. This did not happen until 0.20.0 (i.e. not in 0.19.0) and, thus, could be related to the overhaul of shape ownership.

**Comment by Goury** [comment]
I remember this bug since 0.17.
Just found few minutes to fix it finally.

**Comment by Kruptein** [comment]
I don't have this on my ff either (ff 77).

**Comment by Kruptein** [comment]
This seems to be an issue specific to firefox on ubuntu.  Both the firefox on my windows and the firefox on my archlinux machines render completely correct.  I also have confirmation that it renders perfeclty fine on macOS on firefox.

Is there anything you have in your settings that affects styling, different fonts or the like.  there is some reason why your ff or ff on ubuntu derivatives render differently and I'm less inclined to just throw over the styling of all other places before first figuring out if some other issue is at hand here.  Can you figure out what special styling ubuntu does that might be the source of rendering this differently.

Also I don't really appreciate the tone of the additional context statement. It's not like I'm doing this on purpose.  I test myself regularly on firefox, I have friends that use firefox as their main driver that both DM and play.

**Comment by Goury** [comment]
GTK theme for inputs, most likely.
But why limit max-width anyway?
I don't see anything bad in being able to resize this dialog.

**Comment by Kruptein** [comment]
Because long usernames then impact the width of the entire dialog.

This is an ubuntu/gtk problem.  I'll find out myself what kind of extra styling they do that shouldn't happen.

**Comment by Goury** [comment]
Should limit .owner and select max width and also .owner max height and also make it wrap words in this case.

Limiting entire dialog width just because some elements may be too long is wrong and leads to problems like this.  
Today it's GTK adding extra paddings here and there, tomorrow it may be something else.  
The point is, there's no default size for any HTML element and this is by design.  
You shouldn't expect elements to be the same size everywhere and you shouldn't use hacky styles to tighten pixels.

**Comment by Kruptein** [comment]
Then submit a PR that does those fixes instead of just changing the max-width to a bigger number to fix a problem only on your system.

**Comment by dthv** [comment]
Actually, if it's a GTK problem, it's not *buntu specific, but tied to specific DEs. My xfce4 seems to have been patched when I wasn't gaming. :) Still confirm for LXDE, though.

**Comment by Goury** [comment]
I'll submit it as soon as I have it done.  
So far I've done it this way.  
I don't insist on this being the best way.  
I don't insist on including it into upstream.  
I've just shared it because I don't mind sharing and also because someone may find it useful.

**Comment by Kruptein** [comment]
let's agree to disagree here.

I do agree that the max-width is not ideal and that some systems may have *some* extra padding, but this is not just some extra pixels, I can reduce that max-width by 70 pixels and it still renders correctly.  That's not "some" pixels.

It's a planarally problem but it is in my opinion equally a bug due to the os/de combo.  It's been confirmed to work on i3 arch, gnome 3 arch, xfce ubuntu, lxde debian, windows and macOS.  The places where it does not work so far is your setup of which I don't know the DE and a lxde lubuntu setup. and If you start your post with a cry out that I almost seem to ignore firefox on purpose it just adds to the insult when I have yet to be able to reproduce it myself.

But I do not want to continue this discussion, I'll gladly accept a PR that cleans up the css.
