### ISSUE TITLE
[FEAT] Be able to create server messages on login screen

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#453]
**Is your feature request related to a problem? Please describe.**
Yes, my server has somewhere around 300 active accounts and I'd like to not inconvenience users with a reboot because I patched my kernel

**Describe the solution you'd like**
On the login screen just have an area where the server admin can place a message thats able to be seen by all users.

**Describe alternatives you've considered**
email lists

**Additional context**
![Screenshot from 2020-07-06 16-27-55](https://user-images.githubusercontent.com/2258333/86638704-cabb4100-bfa5-11ea-8da9-a58e1bf76d5c.png)

**Comment by dthv** [comment]
If this is for important, but seldom notifications, one could also think of a popup, like the changelog popping up after update.
If this is for a regular motd, it should indeed be integrated into the UI like in your mock-up.

But for both alternatives, there is the question how to change this message. If it's not a simple `motd.txt`/`notification.txt` within server root-dir but instead saved into the database, the questions of auth/access and UI arise.

**Comment by dthv** [comment]
Just a few issues that are related:
* In #217 there are tool-tips also on the log-in page. This might either be stuff to draw from or to avoid conflict with
* #197 is all about permissions and roles which are needed for…
* …changing the message(s) within an UI, maybe from within an admin panel, which is discussed in #137 
* Finally, it would probably be nice if the message(s) would support markdown for styling, which was already discussed in #320 for annotations.

:smiley:

**Comment by Kruptein** [comment]
I intend to tackle this when I redesign the login / landing page.  With a dedicated server motd style area that would be written in markdown.

Initially with just a file on the server, but when permissions etc are properly set up also configurable in the client itself

**Comment by 10leej** [comment]
Good to learn, any idea where the file is gonna be stored yet so I can plan out docker volumes (and the corresponding doc)?

**Comment by dthv** [comment]
Simply make it ~/server/motd.md ?

**Comment by Kruptein** [comment]
I'm looking at a toast/notification bar for these style of messages instead of an motd.

The core idea is to be able to inform users of issues or upcoming maintenance. You don't want this info to only be available to users that visit the login screen.  So with a toast it can be shown on any screen to make sure players already in-game are also aware.

**Comment by 10leej** [comment]
That sounds like a good idea.
