### ISSUE TITLE
[BUG] simple math with trackers doesn't work

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#454]
When using trackers on shapes/tokens/assets, one should be able to do simple math-operations by, e.g., typing `-5` on a selected tracker. This does not work
* on my Xubuntu 18.04.4 LTS with
  * neither Firefox 78.0.1
  * nor Chromium 83.0.4103.61
* My Lubuntu 18.04.4 with
  * neither Firefox 78.0.1
  * nor Chromium 83.0.4103.61

To reproduce,
* create shape
* open shape properties
* add a tracker by
  * set a name
  * set a first numeric value (e.g. `4`)
  * set a second numeric value (e.g. `500`)
* click into the first numeric value (cursor will appear behind the `4`
* type `+5`
* hit enter (nothing will happen)
* click anywhere else (`4+5` will be changed to `4`)

Expected behaviour would be to show `9`.

Am I doing something wrong?

**Comment by dthv** [comment]
I tested also on Debian with LXDE, doesn't work.
Am I doing it wrong?!

**Comment by Kruptein** [comment]
it's in the small popup on the right side that you can do this by clicking on the value, not in the actual edit dialog

**Comment by dthv** [comment]
Oh right. Thanks. :) Indeed, it works. :)
