### ISSUE TITLE
[BUG] Blank screen on first time access

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#456]
**Describe the bug**
When accessing Planar Ally it takes me to "https://planarally.10leej.com/auth/login?redirect=%2Fdashboard and a blank screen using the backround. This is happening without browser extensions as well.

**To Reproduce**
1. Go planarally.10leej.com'
2. See error

**Expected behavior**
Blank screen as showin in attached image, fixes on a refresh. I attached a screenshot of the console too

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser Mozilla Firefox
 - Version 78.0.1
![Screenshot from 2020-07-14 12-39-12](https://user-images.githubusercontent.com/2258333/87453092-053d6300-c5d0-11ea-8eda-0c580c615bf9.png)
![Screenshot from 2020-07-14 12-46-48](https://user-images.githubusercontent.com/2258333/87453192-2d2cc680-c5d0-11ea-863b-43442b28f7cc.png)

**Comment by Kruptein** [comment]
I'm going to assume this has been fixed by now?

**Comment by 10leej** [comment]
I haven't encountered it in a while, so I would assume it's fixed.
