### ISSUE TITLE
[FEAT]Clarify New Account Creation

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#457]
**Is your feature request related to a problem? Please describe.**
User Experience request rather than expecting someone to type in a username and password then click the + button I find that they typically just click the + button first time and get the shown error message.

**Describe the solution you'd like**
Have the plus button pull up a new page asking for a user name, password (with a confirmation field) and an email address so we can hook that into a possible future two factor authentication/account verification/password reset messages/server admin contact forms.

**Describe alternatives you've considered**

![Screenshot from 2020-07-14 12-40-58](https://user-images.githubusercontent.com/2258333/87453358-5f3e2880-c5d0-11ea-92da-d8f324616dc0.png)

**Comment by dthv** [comment]
> Have the plus button pull up a new page asking for a user name, password

Maybe focussing the first empty field with a tooltip "please enter username/password to register new account" would suffice?

> (with a confirmation field)
Well, that's actually a *very* good point for opening a new page.

**Comment by 10leej** [comment]
> Well, that's actually a very good point for opening a new page.

Really the trend is common enough that UX guidelines basically say you should make a seperate page for account creation

**Comment by Kruptein** [comment]
I personally like the simplistic approach, but I understand if you don't like it.

For now it's going to stay until I redesign the login/landing page.  Which I hope to work on in either 0.23 or 0.24.
