### ISSUE TITLE
[FEAT]Add a scroll bar to locations view

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#459]
**Is your feature request related to a problem? Please describe.**
So i'm just getting ahead in some prep and made a lot of locations. I can see this being frustrating for say someone who doesn't have a 21:9 screen like myself

**Describe the solution you'd like**
Put a scrollbar on the locations

**Describe alternatives you've considered**
Could change the scaling but a simple scrollbar will probably just work better

**Additional context**
![Screenshot from 2020-07-17 22-16-28](https://user-images.githubusercontent.com/2258333/87842598-7ce2ea80-c87b-11ea-9d2f-2f5d2400000d.png)
![Screenshot from 2020-07-17 22-16-32](https://user-images.githubusercontent.com/2258333/87842620-a8fe6b80-c87b-11ea-83be-4007122dcc0a.png)

**Comment by Kruptein** [comment]
There is a scrollbar :p, the red bar under the locations acts as a scrollbar.

**Comment by 10leej** [comment]
Hmm, change the color to make it more obvious then?
