### ISSUE TITLE
[FEAT] Align grid 

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#523]
**Describe the solution you'd like**
Create a tool that allows to align the map to the grid or the grid to the map. 

For example, this will spawn a 5x5 grid that you align to the background image, you can shape this grid and once its good, this will set the scale of the grid for the entire map.

**Comment by Kruptein** [comment]
How does this differ from the map tool ?

**Comment by schemen** [comment]
Oh dang! I have not seen this... Sorry about that, I will close this issue!
