### ISSUE TITLE
Logo for PlanarAlly

### ISSUE THREAD

**Issue by AntiSC2** [Kruptein/PlanarAlly#54]
This is not a priority but it would be nice to have a logo for this project, obviously the problem is finding a person to actually design it. But it would be nice to have at some point and would also help when marketing this project.

**Comment by Kruptein** [comment]
Yes, I'm sadly not great in the graphical department, but this is definitely something I would like to have :)

**Comment by WolfgangAxel** [comment]
@Kruptein I'm not a graphical person myself, but when I read this issue's title, I had a very clear image of a logo pop into my head. If you like it, you're free to use it for this project! Justt let me know and I'll send you/PR the SVG :grin: And if you don't like it, no worries- this took all of like 20 minutes to throw together in Inkscape.

![planaralley](https://user-images.githubusercontent.com/15570802/46245798-72f7ab00-c3b9-11e8-96a6-f298c1048017.png)

(As a side note, I love self-hosted, open-source projects like these. I'll likely try to run an instance of it myself! Thanks for working on it, and keep up the good work!!)

**Comment by Kruptein** [comment]
I initially wanted to have something that highlights the 'travel between planes' aspect or rather the aspect that you travel between different places (not necessarily planes in the dnd sense).
So I initially had something like some kind of portal with different terrains at both sides in my head, but that quickly becomes too busy I think for a logo.

A friend of mine did make a quick draft himself over [here](https://cdn.discordapp.com/attachments/126829418114056192/588777684427997189/unknown.png) which is better than anything I currently have, but I do look forward to anything you would be able to make (if you find the time).

**Comment by hakarune** [comment]
So I did a quick make based off the 8 planar realms. I really wasn't sure where to put the text though...
![Planarally Icon](https://user-images.githubusercontent.com/2251942/63936344-73a72000-ca14-11e9-8e47-e7edc9c41cb6.png)

**Comment by Kruptein** [comment]
Hey, sorry for responding so late.  I'm gonna be honest, I really like that you took your time but I'm not so fond of the colour palette or the font.  The general direction with the planes is nice though.

I've started talking to a colleague from work who does our design stuff and I'm gonna see what that gives, as I feel like it's a bit more easier for me to iterate over something with someone in person.

**Comment by Kruptein** [comment]
We're ~5 months further and I've got something I'll be using for now that is not too fancy but informs users somewhat of the kind of software PA is:

![Logo_PlanarAlly_V1](https://user-images.githubusercontent.com/1814713/74552336-48c66f00-4f55-11ea-8dc2-b62dd07c02bc.png)

**Comment by LDeeJay1969** [comment]
That looks very nice. Maybe combining this with the realm symbols? Will this be the front page logo or an icon? Just asking for the amount of detail you might be able to put in....

**Comment by Kruptein** [comment]
I'm gonna keep it simple for now and just use this as the main logo/icon.  With much room for improvement in the future.  I would just like to have something to at least be able to use :D
