### ISSUE TITLE
[BUG] Ship fonts instead of using Google Fonts

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#565]
One of my players suggested to ship fonts with PA instead of use Google Fonts (for privacy concerns). I second.

They specifically referred to *OpenSans*. This font is [licensed under Apache 2.0](https://fonts.google.com/specimen/Open+Sans#license). In case this is a problem with PA's MIT-licensing, I recommend to check whether the SIL OFL is more compatible (it is e.g. used by the [Liberation Font family](https://github.com/liberationfonts/liberation-fonts)).

**Comment by Kruptein** [comment]
Why would the apache 2.0 license of the font be a problem with the MIT license PA has.

the APL 2 license allows commercial/private use, free modifications etc, the only thing it requires is that an APL2 license is included in the repository specifically for the font, not for the entire repository.

**Comment by Kruptein** [comment]
The prime distinction between MIT and APL2 is that APL2 requires explicit notice of changes, otherwise they are roughly similar.

**Comment by dthv** [comment]
I don't know whether there are license problems (or even possible license problems). Hence the question. Licensing problems were the only thing I imagined to be a con against shipping fonts with PA instead of using Google Fonts. So I asked whether that was the case.

Or am I missing something? :)

**Comment by Kruptein** [comment]
Oh sorry, I misread that part, I thought you meant it was a problem with the PA license, but you were just asking me to double check, my bad.

**Comment by dthv** [comment]
Never mind. I know nothing about FLOSS licensing but: 'Be careful with integrating code that is licensed differently.' and did not want you to run into a trap set up by me carelessly. :wink:

**Comment by Kruptein** [comment]
Hey it's a good mindset to be wary about those things!, this change is not a lot of work so expect it done tomorrow
