### ISSUE TITLE
[FEAT] Option to disable scroll-to-zoom

### ISSUE THREAD

**Issue by rtanen** [Kruptein/PlanarAlly#578]
**Is your feature request related to a problem? Please describe.**
I often make scrolling gestures when attempting to pan around the page, or just accidentally. This triggers PlanarAlly to dramatically re-scale the map, which is laggy and not what I want.

**Describe the solution you'd like**
I want there to be a Client Options setting to disable scroll-to-zoom. When scroll-to-zoom is disabled, making a scroll gesture shouldn't do anything.

**Describe alternatives you've considered**
It would be neat if future releases also offered the option to make scrolling gestures to pan in any mode.

**Comment by dthv** [comment]
Second.

> It would be neat if future releases also offered the option to make scrolling gestures to pan in any mode.

As in: use the mouse-wheel to pan instead of zoom?

**Comment by rtanen** [comment]
As in: use anything that does both horizontal and vertical scrolling (such as two-finger gestures) to pan instead of zoom. I hadn't considered the mouse-wheel case, sorry.

**Comment by Kruptein** [comment]
that makes more sense, so it's touch input specific ? I was also confused how one would like to pan when scrolling your mousewheel :D

**Comment by dthv** [comment]
There is an open issues on touch gestures in #313 and one specifically on two-finger-gestures in #325.
