### ISSUE TITLE
[BUG] cors_allowed_origins makes all sessions inaccessible

### ISSUE THREAD

**Issue by raffitz** [Kruptein/PlanarAlly#579]
**Describe the bug**

If the variable `cors_allowed_origins` is set in the config file (`server_config.cfg`), it is impossible to access or modify sessions at all, regardless of host.

In my case, in which the server is only accessible through a reverse proxy due to my network topology, this makes the server entirely inaccessible to my players.

With the variable set, if I access planarally whether directly through http://ADDRESS:8000/ or through my reverse proxy (https://planarally.DOMAIN.TLD/), I am shown the login page. I can sign up and/or login apparently fine.

The console running python does not show a connection message (contrary to expected behaviour).

If I try to access or create a new session, I am bounced back to the dashboard.

When that happens, the console running python does not show an error message, and the javascript console of the client shows:
```
Firefox can’t establish a connection to the server at ws://ADDRESS:8000/socket.io/?user=raffitz&room=demo&EIO=3&transport=websocket. websocket.js:124:12
Could not connect to game session. events.ts:35:12
```

If I sign out of the dashboard, the console running python does not show a disconnection message (contrary to expected behaviour).

**To Reproduce**
1. Download the release archive `planarally-bin-0.23.1.tar.gz`
2. Uncompress the archive `tar -xf planarally-bin-0.23.1.tar.gz`
3. Go to server folder `cd server`
4. Install requirements `pip install $(cat requirements.txt)`
5. Edit file `server_config.cfg`, uncomment line 19 to read `cors_allowed_origins = ['*']`
6. Start the server `python planarally.py`
7. Access the login page, and sign up into an account (or if it is not a fresh instance of the server, login to an existing account, I've tried both, and both show the same behaviour). When the dashboard is shown, create a new session if none exists. Try and access any session, new or pre-existing.

**Expected behavior**
The client leaves the dashboard, enters the game session, and can participate as usual in the game. The python console shows connection messages on sign ins, and disconnection messages on sign outs.

**Desktop (please complete the following information):**
 - Server OS: Arch Linux
 - Client OS: Arch Linux
 - Browser: Firefox
 - Version: 83.0

**Comment by Kruptein** [comment]
What happens if you use `cors_allowed_origins = *` instead?

**Comment by raffitz** [comment]
With `cors_allowed_origins = *`, access via local network works fine, I can access the session, connection and disconnection messages appear as expected. Access via reverse proxy fails, but this time it shows an error on `stdout`:

```
Error handling request
Traceback (most recent call last):
  File "/home/raffitz/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/raffitz/.local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/raffitz/.local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/raffitz/.local/lib/python3.8/site-packages/aiohttp_session/__init__.py", line 159, in factory
    raise RuntimeError(
RuntimeError: Expect response, not <class 'list'>
```

This is effectively the same behaviour as the default behaviour without an explicit `cors_allowed_origins` line in the server config.

**Comment by Kruptein** [comment]
> If I try to access or create a new session, I am bounced back to the dashboard.

This line in particular is a clear tell that It's very likely that your reverse proxy is not properly forwarding websocket connections, can you show your configuration?

**Comment by raffitz** [comment]
Huh. Yep. I followed [this](https://www.tutorialspoint.com/how-to-configure-nginx-as-reverse-proxy-for-websocket) to correct it. I was missing the _Upgrade_ and _Connection_ headers. Thank you!
