### ISSUE TITLE
[FEAT] Multiple assets associated with one token

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#580]
Right now a token is associated with one specific asset. If you at some point design new art for your character or have some sort of shape shifting behaviour, it would be preferred to not have to copy all stats over to a new token with the new asset.

Adding a section to the edit dialog menu to add/remove assets and having an option to select the active asset would improve this greatly

**Comment by dthv** [comment]
In case it makes sense in light of the current code (which I did not check tbh), maybe this can be used to get rid of *basic tokens* as third type next to the `asset` and `shape` types?

**Comment by Kruptein** [comment]
This actually is a duplicate of #163
