### ISSUE TITLE
Look into vue.js for dialog UI

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#59]
Current UI code is pretty ugly having to link all the events and build all the UI.

The vue framework seems interesting as it can be introduced gradually.

**Comment by AntiSC2** [comment]
Personally I think vue.js would be a good replacement and that it would be best if we could phase out jQuery more and more. Lots of features were added in ecmascript 5 & 6 that makes jQuery a bit redundant and from what I have read, jQuery has lower performance.

**Comment by Kruptein** [comment]
I agree with that sentiment, the main reason I currently keep it is because I make use of some of the jquery UI stuff like the popup dialogs and the zoom slider which require jquery itself.  If I get around to replacing those with something else I can phase out jquery completely.

Performance wise, sure jquery might be slower, but it won't be the bottleneck given that the most important timing aspects have to do with the fog calculations.

**Comment by AntiSC2** [comment]
Oh yeah, did not mean that jQuery was a bottleneck but any performance gain for the same functionality is a good win in my book

**Comment by Kruptein** [comment]
A lot of the UI has in the meanwhile already been converted to Vue, see the `vue` branch for the progress.
