### ISSUE TITLE
[FEAT] Hide locations from bar, archive/organise locations

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#599]
During a party's adventures, the location bar can grow full to overflow. And although some locations are meant for only one session or two, you'll never know when there will be a need to come back. On the other hand, there's probably only a few locations that are regularly visited.

Thus, it would be very nice if it was possible to clean the location bar of all clutter and have just those locations present that will (most likely) be needed in a certain session.

One way to do it would be to hide locations from the Location bar, leaving only a button (maybe decorated with `&` alike to the `+`-button to create new?). Pressing the button would pop up a list of 'hidden' locations that can be clicked/dragged back to the location bar for use.

Another way might integrate into the import/export functionality that has been discussed. Yet, even with the "save location to file"-option present, the abovementioned functionality would be nice indeed. :)

**Comment by Kruptein** [comment]
The core concept of this issue has been released in 0.25.0.

I'm going to close this ticket for now, but the idea of saving locations to files is definitely still on my mind.
