### ISSUE TITLE
[FEAT] Token Level Vision

### ISSUE THREAD

**Issue by ekerstens** [Kruptein/PlanarAlly#625]
**Is your feature request related to a problem? Please describe.**
It would be great to have a way to differentiate between a communal light source and token level light/vision. When running the game I use one user to control all the players and another to control the DM side of things. I then share my screen for the player user. During combat, the vision lock feature is great; however, I emulate dark vision using auras which means they are visible to any other tokens in line of sight. 

**Describe the solution you'd like**
An additional toggle for auras that indicates the aura is a vision type, rather than a light source. 

**Describe alternatives you've considered**
Toggling off my "Dark vision" aura from tokens when they're not up in iniative, which is tedious.

**Comment by Kruptein** [comment]
Sorry if I don't understand you correctly, but there are 2 toggles for the aura right.
the eye icon which decides whether other players can see the tracker/aura
and the lightbulb icon which decides whether it is a vision/light source.

So for a torch I have both toggled on, for darkvision I only have the lightbulb toggled on.

**Comment by ekerstens** [comment]
As I understand it (could be wrong) the eye icon is at a user level; my thought is more around a token level.  I've got one user managing all the PC tokens and then share my screen with my players. So far as I can tell, I have to give that user vision access to all the PC tokens. But then, the private/public toggle has no effect even when showing vision from only a single token.

**Comment by Kruptein** [comment]
I see; Have you tried the vision tool (it's in the toolbar along select/pan etc). I think that might be what you are looking for.

It only shows up if the player controls multiple tokens and allows you to toggle which tokens their vision you would like to see

**Comment by Kruptein** [comment]
It does assume that you use the eye to signal private/public intent

**Comment by ekerstens** [comment]
The vision tool is great! However, it is still showing the "light" of the other tokens dark vision. Let me share some screenshots that maybe can help clarify. 

So suppose we have two PCs and a wall. With both PCs showing in the vision drop down, we see
![image](https://user-images.githubusercontent.com/49325583/103305643-804cd700-49c0-11eb-877b-5959e4f101a7.png)

Then, I toggle off the second PC. I have "Only show lights in LoS" toggled, so part of PC 2's vision is cutoff. 
![image](https://user-images.githubusercontent.com/49325583/103305659-8c389900-49c0-11eb-96f2-8d69010ffb08.png)

However, PC 1 can't actually see the area around PC 2! I would expect it to look like this:
![image](https://user-images.githubusercontent.com/49325583/103305753-ce61da80-49c0-11eb-96c2-93b4bd165753.png)

**Comment by Kruptein** [comment]
I see, yeah it actually isn't taking the eye into account, thanks that makes sense.

**Comment by ekerstens** [comment]
Spun up a dev environment and the changes mostly work as expected. When I give a specific user access to a token, then the vision works correctly. However, the previous behavior is still exhibited if I instead grant default vision access on the tokens.

**Comment by Kruptein** [comment]
Right, my bad
