### ISSUE TITLE
[FEAT] Show Annotation without sharing vison

### ISSUE THREAD

**Issue by PalasX** [Kruptein/PlanarAlly#635]
**Is your feature request related to a problem? Please describe.**
I use Basic Token as "room descriptions" that players can hover over and read the annotation as a description of a room. The problem is that, even with no light/aura, it ALWAYS shows this basic token and anything it can see, since i have to share EDIT permission in order for the annotation to show, and that implies sharing vision, and shows other light sources and tokens that my "room description" token can "see".

**Describe the solution you'd like**
Allow a boolean "Show annotation" for tokens, that when true, will show the mouseOver annotation.

**Describe alternatives you've considered**
I don't know how else to get the annotation to show up.

**Additional context**

![image](https://user-images.githubusercontent.com/37154966/104985647-70348000-59df-11eb-8ff6-dccf986c51b0.png)

**Comment by Kruptein** [comment]
Shouldn't be too hard to add :)
