### ISSUE TITLE
Configurable "relative path" for reverse-proxy usage: websockets not working?

### ISSUE THREAD

**Issue by Epicanis** [Kruptein/PlanarAlly#647]
I'd like to make my instance of PlanarAlly reachable behind my existing nginx reverse-proxy setup, where I have SSL configured and working and other services accessible through it.

Having it proxy connections to "https://(server)/planarally" to http://(internal server):8000 gets me the initial connection, but that results in pointers to various files in "/static/*" which of course are unreachable in this configuration.

Would it be easy to add a "URL Prefix" configuration option of some sort for reverse-proxy setups like this, so that PlanarAlly would insert the "/planarally" (or other path) to the URLs sent to the clients? (Might require two options, if one wants to leave the API server only accessible internally while keeping the main PlanarAlly interface available through the reverse-proxy).

(This *feels* like it ought to be easy, but then *everything* seems easy to someone who doesn't actually have to do it...)

**Comment by Kruptein** [comment]
I know it's not well documented, but this should be possible with `export PA_BASEPATH="/planarally"`

**Comment by Epicanis** [comment]
Ah, thank you, that gets it almost working for me (once I realized what I needed to do to get the reverse-proxy synced up).
I am now able to connect through the reverse-proxy and login. Still having a problem getting the websocket connection to proxy, but at this point I think it's more likely to be my nginx configuration than a bug/feature. Moving the discussion to Discord, will add a comment with working config info for the next person who comes along wanting to do what I'm doing once I get it figured out.

**Comment by Kruptein** [comment]
Just want to check-in if your problem is resolved ?

**Comment by Epicanis** [comment]
Not yet, though I still assume I'm just misconfiguring. Having rebuilt the new version with PA_BASEPATH set, I find when I connect to it through the proxy it tries to give me URLs with the basepath doubled for the most of the links (from the client?)

`<link rel="stylesheet" type="text/css" href="/planarally/static/extern/css/directory.css"><link rel="shortcut icon" type="image/png" href="/planarally/static/favicon.png"><link href="/planarally/planarally/static/css/app.16fa8238.css" rel="preload" as="style"><link href="/planarally/planarally/static/css/chunk-vendors.cc0fcb6e.css" rel="preload" as="style"><link href="/planarally/planarally/static/js/app.7e3cad79.js" rel="modulepreload" as="script"><link href="/planarally/planarally/static/js/chunk-vendors.0811b93f.js" rel="modulepreload" as="script"><link href="/planarally/planarally/static/css/chunk-vendors.cc0fcb6e.css" rel="stylesheet"><link href="/planarally/planarally/static/css/app.16fa8238.css" rel="stylesheet">`

**Comment by Kruptein** [comment]
Hm Ok, I'll see if I can find some time to try it out myself to be sure how it works again and maybe immediately take the time to document it properly :D

**Comment by Kruptein** [comment]
Ok I did some testing of my own and have found the problem you're having.

So I was wrong about having to set the environment variable for the client, that is only required when running the client in dev mode, so sorry about that, you'll need to either throw away your own client build and use the one you originally had, or rebuild it yourself with the env variable unset.

(technically you can get it to run with the client variable set as well, but then you'll need to modify a line of the server code)

Then that puts you in your original situation, the websocket. I figured out in my local case that I had to add the subpath to my nginx socket io rule, i.e. I now have the following config:

```nginx
    location /subpath/ {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://subaiohttp;
    }

    location /subpath/socket.io/ {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_pass http://subaiohttp/subpath/socket.io/;
    }

    location /subpath/static {
      alias /home/darragh/dev/planarally2/server/static;
    }
```

It's that last line in the socket.io location that I needed to add '/subpath/'.  I'm not sure yet if I deem this a bug in the server or not. So for now I might leave it like that, but I might change the server in the future to make it that you don't have to do that change manually.

**Comment by Epicanis** [comment]
After confusing the heck out of myself and making this harder than it should have been, the new documentation at https://www.planarally.io/server/advanced/subpath/ actually does seem to work, with the one exception that the cors_allowed_origins line in server_config.cfg apparently actually needs to read:
`cors_allowed_origins = *`
rather than 
`cors_allowed_origins = ['*'] `
as implied in the server_config.cfg comments

Working now for me, obviously a "bug" in my attempt to configure and not a problem with the software!
