### ISSUE TITLE
[BUG] Multiple floors with the same name causes errors

### ISSUE THREAD

**Issue by CalebKoch** [Kruptein/PlanarAlly#653]
**Describe the bug**
When I create a second floor with a name that already exists, I can move to the new floor floor correctly, but trying to change the floor causes errors in the console, and changes don't get synced to other clients, or persist across refreshes. 

**To Reproduce**
1. Click on the floor indicator in the bottom right. 
2. Select "Add new floor"
3. give the floor a name that is already used by a different floor, for example "ground" on a new location
4. Switch to the newly created floor
5a. Try to create a basic token - Can click the submit button, but the prompt stays on the screen.
5b. Try to add an asset - Asset doesn't show up, until you change your scroll. 
5c. Try to draw a shape using the draw tool. - Drawing shows up, but can't be selected, and disapears on refresh.

In all cases, an error is displayed in the Browser console:
Error: setVisionSources got an unknown floor

**Expected behavior**
Either, the "Add new floor" would not allow creating a new floor with a name that matches an existing floor (seems like that check already exists for renaming a floor), or when editing assets on the new floor it allows them to be changed and moved as normal.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 85.0

**Additional context**
Not a big issue, since you can just rename the floor, and not a normal use case, but it caused some puzzleing behavior while I was setting up 7 floors of "stairs (cont)"

**Comment by Kruptein** [comment]
This is going to be an issue where some checks are done based on the name of the floor instead of the id, my bad.

**Comment by Kruptein** [comment]
For now I'm indeed going to 'easy' fix it as to prevent floor creation with a name that is already in use. It would take a bit more work for it to work properly with duplicate names and for now I don't think that's worth the effort.
