### ISSUE TITLE
Add undo mechanism

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#66]
^title

**Comment by KomaGR** [comment]
Is someone working on this?

**Comment by Kruptein** [comment]
Not yet, I just released a new version and am looking at what I'm going to focus on for the next release, so I might pick this up

**Comment by Kruptein** [comment]
@KomaGR what kind of actions would be a must for you?

Movement and removal are obvious, but is there another thing you would expect to be there in a first iteration?

**Comment by KomaGR** [comment]
Thanks for asking. I will also list some movement and removal cases explicitly, even though you acklowedged them. Here's a list about what I think the user should be able to _undo_. I use the word object to refer to both tokens and shapes.

1. Dragging an object.
2. Moving an object with the arrow keys.
3. Rotating an object.
4. Resizing an object.
5. Moving an object to another layer.
6. Moving an object to another floor.
7. All of the above for groups of objects.
8. Drawing/creating an object on any layer.
9. Resizing an object with the map tool.

I have purposely left out interaction between locations as that may be best left for future improvements.

**Comment by Kruptein** [comment]
Do you expect this to only be available to the DM or also to the players?
if the latter, how do you see the DM flow, only dm actions or also player actions or both ?

**Comment by Kruptein** [comment]
after some discussion with some close friends I've decided that indeed players and DM should all be able to undo their own actions and nothing more.

The added complexity of allowing the DM to undo player actions is just not worth it and also possibly very confusing.

**Comment by dthv** [comment]
> The added complexity of allowing the DM to undo player actions is just not worth it and also possibly very confusing.

I completely agree. `Undo` would be a nice feature, but please don't allow to undo the actions of others. :slightly_smiling_face:

**Comment by KomaGR** [comment]
I agree that supporting undo for player actions might be confusing and even  hinder the dm while live playing.
