### ISSUE TITLE
[FEAT] Adding Text as a shape

### ISSUE THREAD

**Issue by adunis** [Kruptein/PlanarAlly#671]
The feature requested is the possibility of adding Text as a shape (for example being able to add the text ' This is a trap ' ) and being able to change its size.

Being able to format the text would be a plus.

**Comment by dthv** [comment]
To support reducing clutter, it should be possible to add annotations to the text so that there's only a primer/summary on the map with additional info on mouse-over.

**Comment by Kruptein** [comment]
It's currently pretty basic (i.e. text + font size) so any special formatting or font type etc is for later, but I wanted to get something out to at least have something
