### ISSUE TITLE
[FEAT] Server Side Asset Management

### ISSUE THREAD

**Issue by Airforc** [Kruptein/PlanarAlly#673]
All campaign assets are stored in /static/assets, this is hard to manage space usage by campaign on systems with limited space.

Request: PA to store campaignA assets in /static/assets/campaignA and campaignB assets in /static/assets/campaignB

**Comment by Kruptein** [comment]
Apparently I never reacted to this, my apologies.

They are not separated per campaign exactly to save space.
If a certain asset is used in multiple campaigns, it will only be stored on disk once. In your proposal this same asset would have to exist multiple times.

What I should add instead is limits on how many data a user can upload/have.
