### ISSUE TITLE
[FEAT] Update Invitation URL to not be internal ip address

### ISSUE THREAD

**Issue by mischievous** [Kruptein/PlanarAlly#676]
Hello,

I was trying to update the source code for Invitation URL to replace the hostname:port with something I have defined in a config file.  Right now it's HTTP:xxx.xxx.xxx.xxx:port/* and I want to replace the xxx with a public ip address.  

Where would I look in the source code for this?

**Comment by Kruptein** [comment]
https://github.com/Kruptein/PlanarAlly/blob/dev/client/src/game/ui/settings/dm/AdminSettings.vue#L36-L38

So as you can see it just uses dumb logic to fetch the current host the DM is on.  The invitation logic itself just reasons about the `/invitation` endpoint, so it's just a presentation bug.

**Comment by mischievous** [comment]
Thank you.  I can work with that I hope.  I am all over the python... The typescript is new and looks painful like JavaScript is.

**Comment by Kruptein** [comment]
:D 

one of these days I should write an ARCHITECTURE.md doc to give some better information on how everything is structured

**Comment by mischievous** [comment]
I was searching all the *py and *.ts files.  Did not know about the *.vue files.   Well I will let you know if/when I get it done.

**Comment by Kruptein** [comment]
thanks, and feel free to ask me if you're confused/stuck, either here or on the discord server :)

**Comment by mischievous** [comment]
Discord server?  I could not find it... Where is it?

**Comment by Kruptein** [comment]
There is a little discord icon under the logo on the main page ;D http://discord.gg/mubGnTe
