### ISSUE TITLE
[FEAT] support "Universal VTT" files / *.dd2vtt

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#677]
Like probably some others, I use [Dungeondraft](https://dungeondraft.net) to draw most of my maps. And while I see ways to get the great improvement of #641 to get to work, native support of its Virtual Tabletop Export format (`*.dd2vtt` – *Universal Virtual Tabletop* format) would be even better.

Sadly, while it's called the 'Universal VTT' format, it does a) seem to be a proprietary format introduced by *Dungeondraft* and b) not be documented, anywhere. Yet, it should be do-able to reverse-engineer core-functions. Or one tries to ask 'Metasploot' as the indie-programmer goes with, e.g. on [the official Dungeondraft reddit](https://www.reddit.com/r/dungeondraft/)

From what I've learned with a rather quick research yesterday, the file is basically a JSON with an attached PNG; drawing seems to work with coordinates (I've only tested with a basic rectangle, I should also do with diagonal walls and circles/curves), as does placement of assets. For a start, basic functionality (drawing of walls, ignoring doors etc) would probably be enough to reduce preparation time in PA by a vast amount.

There are modules for importing `*.dd2vtt` [to Foundry VTT](https://github.com/moo-man/FVTT-DD-Import) and [Roll20](https://github.com/shdwjk/Roll20API/tree/master/UniversalVTTImporter) that one could have look in regarding the format's structure; also, native support was introduced [to MapTool in its 1.7.0 version](https://github.com/RPTools/maptool/releases/tag/1.7.0).

Bonus: With native support, PA could maybe be listed on the Dungeondraft page. Y'know, PR. :)

**Comment by Kruptein** [comment]
Sure I'll give it a look when I'm off work. Could you perhaps give me an example file so that in case I need to ask questions we're talking about the same input

**Comment by dthv** [comment]
Sure. Take this for a start. It should include most basic forms you'd need (and some you'd probably won't). In case you need a dungeon that's closer to what we would expect from users to import, let me know.

[map-export-sample.dd2vtt.tar.gz](https://github.com/Kruptein/PlanarAlly/files/5987497/map-export-sample.dd2vtt.tar.gz)

**Comment by Kruptein** [comment]
So looking at that file, is "line_of_sight" the set of walls ? and what is "portals" ?

**Comment by dthv** [comment]
> "line_of_sight" the set of walls

Yes. I probably should have baked several simple forms instead of one complex one entailing everything. I shall do so, immediately.

> and what is "portals" ?

Doors and Windows. I think "bounds" are the "edges of the walls entailing the door" (for lack of a better explanation); the "closed" bool would equal "block vision/movement" in PA.

Lights are completely missing, which is also a mistake on my side.

**Comment by Kruptein** [comment]
Don't feel rushed, I'll take a proper look tomorrow in combination with the image, was just curious looking at the json

**Comment by dthv** [comment]
Don't worry.
[map-export-samples.tar.gz](https://github.com/Kruptein/PlanarAlly/files/5992328/map-export-samples.tar.gz) includes the following self-explicatory named contents (ordered by assumed complexity)
* rectangle
* rectangle with doors and lights
* triangle
* circle
* ellipse
* complex
* cave with opening and light

Further Explanation:
* Dungeondraft uses three basic forms to build rooms: rectangle, ellipse (can also be circle, if dragged accordingly) and polygon. `map-export-sample_complex.dd2vtt` will combine these methods to build a more complex room.
* Note that with `"portals"` there is already information on where to place doors and(!) whether doors do block vision, or not.
  I think it's safe to assume that doors that block light/vision also block movement, while doors that don't, don't. :slightly_smiling_face: 
* Caves are drawn free-handed. They can be 'blast open' by a sort of erase-tool (that seems to work not too far from PA's new erase tool, I suppose), but am not sure.
* Lights offered by Dungeondraft are probably not compatible to lights offered by PA, so maybe this could be omitted either in total or at first.

**Comment by Kruptein** [comment]
Alright looking at the files with the images, looks pretty straightforward to add.

I was afraid the ellipse was going to require some extra work because I don't support drawing ellipses manually yet, but ddraft actually just approximates the circle and ellipse with a polygon, which is perfect for me as I need polygons as well.

I'll assume every closed portal is both vision and movement blocking.  Open portals, you seem to suggest to have both non-blocking.  Is there some form to differentiate a door from a window ? Right now it seems that windows will need a manual toggle in PA as they will be either interpreted as a door or an open door with how I currently se the portals working.

the environment-ambient light is something I don't support at the moment no, the normal lights I can create. They have a (x,y) position and a range + colours so I can definitely incorporate that.
Only the intensity field is unclear, but for now I'm going to assume that 1 is full brightness.
Is the shadows option something similar to what I have in 'is light source' ?

**Comment by Kruptein** [comment]
Another question, what do you expect once you drop such a shape on the board.

a) the image is shown and the vision/light things are automatically set up without an option to alter them
b) same as a, but the walls appear on the fow layer for example allowing you to move them

Somewhat linked to (b),  do you expect to be able to retrieve the original dd2vtt file again, or are you fine with it being converted to something PA internal once you upload it to the asset manager or drop it on the board ?

**Comment by dthv** [comment]
> looks pretty straightforward to add

Wheee! :D

**Expectations first:**
On dropping a `*.dd2vtt` file, I'd expect the PNG appear on the `map` layer and walls (and "portals", more on that below) appearing on the `fow` layer. Lights *could* be ignored as the lights are baked into the PNG while PA's support of lights is probably a bit better than (unmodded) Dungeondraft. In case lights are not ignored, yes, I'd expect them to be automatically set up as (invisible?) shapes on the `map` layer emitting lights.

Bonus, if all the generated shapes are put into a common group and are locked to move together if one is moved (should be able to be split up, though).

> I'll assume every closed portal is both vision and movement blocking. Open portals, you seem to suggest to have both non-blocking.

Depends on how portals are drawn. Maybe this should be discussed further to get a 'best practice' approach, either in the discussions section or on discord. What I do is drawing red lines on the `fow` layer (walls are black) and change blocking behaviour when players open/close the doors. Thus, my expectation right now would be to have "portals" drawn as entities separate from the walls polygons that are visually highlighted on `fow`. With that in mind, "open" doors could exist on `fow` but set to not block vision/movement, while "closed" doors would. Accordingly, with regards to windows, I'd expect them to always block movement but only block vision when "closed".

> Only the intensity field is unclear, but for now I'm going to assume that 1 is full brightness.

I think it's a bit more complicated than that and have to look again later. I'm almost sure that brightness/intensity can go up to at least four or five. Best representation within PA would be the light colour's opacity, I think. Safe to ignore for a start, if you ask me.

> Is the shadows option something similar to what I have in 'is light source' ?

Err, no, this is for any shape drawn within PA to either cast a small shadow or not. Think of CSS's `text-shadow`. Again, safe to ignore, if you ask me.

>  do you expect to be able to retrieve the original dd2vtt file again, or are you fine with it being converted to something PA internal once you upload it to the asset manager or drop it on the board

At least with Dungeondraft, the `*.dd2vtt` format seems to be export-only and is generated by the `export`-function that normally bakes PNG and the like. The programme does have an own distinct savefile format that is most likely independent of this here. Thus, I'd say re-using a `*.dd2vtt` modified by PA is out of expectation. I would not expect PA to keep it, but simply use it as a way to import and translate into its own format(s). I'm fine with conversion to something PA internal and would expect everybody else to be, as well.

(That being said, I actually don't know what *Dungeonfrog*, a web-based map-drawing tool I did not check out (yet) that I have heard to have adopted the `*.dd2vtt` format as well, does with it. But for now, I'd say: import-only.)
