### ISSUE TITLE
[FEAT] macOS Keybindings (Command instead of Control)

### ISSUE THREAD

**Issue by ashgti** [Kruptein/PlanarAlly#678]
**Is your feature request related to a problem? Please describe.**

Support macOS keybindings (e.g. cmd+c and cmd+v instead of ctrl+c and ctrl+v). 

**Describe the solution you'd like**

For clients on macOS, support for using cmd instead of ctrl. Existing Ctrl based key bindings work on macOS but they're not the standard commands.

**Comment by Kruptein** [comment]
Someone recently mentioned this to me as well on discord I think, or I just can't find the ticket anymore. Expect a fix for this in the next release.
