### ISSUE TITLE
Delete key does not work properly on Mac

### ISSUE THREAD

**Issue by thorlucas** [Kruptein/PlanarAlly#69]
On a MacBook, deleting tokens only works when I press control+delete, rather than just delete.

**Comment by joshroth21** [comment]
Looks like event.key returns as "Backspace" (not "Delete" or "Del") on a MacBook. Adding it as an option in `../ts_src/games/events/keyboard.ts` seems to fix it.

**Comment by Kruptein** [comment]
Ah that would be an easy fix, thanks for figuring that out Josh.
