### ISSUE TITLE
[FEAT] Defeated indicator for tokens

### ISSUE THREAD

**Issue by sevzero** [Kruptein/PlanarAlly#690]
**Is your feature request related to a problem? Please describe.**
Currently there's no simple way to indicate when a token has been defeated. At the moment in my games I either move them to the DM layer or drag an asset over them to show this. This works but either hides the token from players making it difficult to interact with them after the combat or can be time consuming to add an asset over the top of the tokens.

**Describe the solution you'd like**
It would be nice if there was a toggle which visually shows when a token has been defeated. I think a red cross through it would work well but there are probably other ways to show this as well. I can't think of a perfect way to toggle this for tokens but the best I can come up with would be a setting in the token properties and a keyboard shortcut to set it.

**Comment by Kruptein** [comment]
In my games I rotate the shape upside down to indicate this :D 

But in all seriousness, some solution for this would be nice. A red cross is visually very obvious, but might draw the attention away maybe? Something like graying out a token might also be possible although I don't know if that's any better.
Another option is some sort of indicator in either one of the corners or in the middle of it that is less flashy as a red cross.

I'll ask around what my players would like to see as some feedback.

**Comment by sevzero** [comment]
Ha I love the upside down workaround, I'll have to steal that for my games until there's another solution. I had the same thought about graying out the token too but thought it might have issues on tokens that are grey to begin with. As you say, people will have different ideas about the best way to show this so definitely worth asking around.

**Comment by sevzero** [comment]
Merged in #692
