### ISSUE TITLE
[FEAT] Copy a location to a new session/room

### ISSUE THREAD

**Issue by CalebKoch** [Kruptein/PlanarAlly#697]
**Is your feature request related to a problem? Please describe.**
I am DMing 2 groups through the same Adventure Path, and so I am setting up a lot of maps multiple times. I would like to be able to create the map once in the first session that gets there, and then have an option to copy this into the other groups session, and have the map, walls, lights, and tokens created there. 

**Describe the solution you'd like**
Have a section of the Location Settings Pop-up that lists all of the sessions that you are an owner of, where clicking one of those sessions, will copy the location, floors, tokens, and drawn items from the selected location into a new location on the selected section.

**Describe alternatives you've considered**
I've considered recreating the map manually, which works, but takes a significant amount of time, since the maps can be large, with difficult to model walls.

**Comment by CalebKoch** [comment]
2 points I think need a little discussion on how they will work:
1. If a player is in both sessions, and has access to a token, should that access move across? I would expect Default and the DM's access to copy over, but not sure on others.
2. Should the Location Setting list of sessions be in a new tab, or fall under Admin.

I've got some work started on this, but wanted to open this issue to get some discussion on these points.

**Comment by Kruptein** [comment]
I know your feeling.

just for clarity's sake. Suppose you have a campaign running let's say curse of strahd.

and a couple of sessions in you start another CoS campaign and want to copy the start location.  You would be fine with it copying literally everything in that location then right?

Depending on how clean your map is, you might need to cleanup some things, closing doors that have been opened, removing tokens from players not associated with the new campaign, etc etc

All things considered this will be much less effort ofcourse compared to having to draw the walls etc from scratch, but just making sure if that's what you envision

**Comment by CalebKoch** [comment]
Yup was definitely expecting that if I had opened doors and had tokens that had been defeated, those steps would need to be undone.

**Comment by Kruptein** [comment]
> 1. If a player is in both sessions, and has access to a token, should that access move across? I would expect Default and the DM's access to copy over, but not sure on others.

Though call honestly, chances are pretty high that a person is going to play a different character I would say, but in that case you just remove the old token, so I don't think it would be bad to have the access copy over ?

> 2. Should the Location Setting list of sessions be in a new tab, or fall under Admin.

No particular preference yet, but it would be best if it was some button or other call to action that initiates a modal to choose from, so that we only need to fetch the session + location information when this modal is opened and not when the DM settings are opened for example

> Yup was definitely expecting that if I had opened doors and had tokens that had been defeated, those steps would need to be undone.

Ok cool, seems good to me!
