### ISSUE TITLE
Email/username is case sensitive

### ISSUE THREAD

**Issue by jcc10** [Kruptein/PlanarAlly#71]
I can understand why this might be intentional, but this can cause some real issues since most people don't treat usernames as case sensitive.

**Comment by Kruptein** [comment]
It's something I actually dislike as well, it's on my list of to-do things for the next release!

**Comment by Kruptein** [comment]
It should now properly ignore case for both login and ownership checks in game

**Comment by jcc10** [comment]
Ok, it seems to be doing that now.
