### ISSUE TITLE
[BUG] Client Options vs Client Settings

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#714]
This is just a minor one: The sidebar has a button called `Client Options` which opens a modal titled `Client Settings`.
This should be harmonised (esp. since the documentation, at the moment, introduces a third variant called `In-game Settings`).

**Comment by dthv** [comment]
I'd prefer 'settings' over 'options', btw, as not everything is optional, but some things have to be set. :) (also, and this is the actual reason: docs say 'settings' , too. :wink: )

**Comment by Kruptein** [comment]
Settings is fine for me too :p
