### ISSUE TITLE
[FEAT] edit display of simple tokens & drawn text

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#715]
Simple tokens and text drawn on the game board by the *draw* tool have one thing in common: After being set, their display on the game board is fixed and cannot be altered.

I would like to see a text input named `display` (or something like that) in the objects' properties modal that contains the text the objects shall display. It will only be needed for simple tokens and drawn text; for every other object, drawn text can be set, grouped and locked to them.

I considered asking to simply link the object's name to the display, but especially for simple tokens, it would be nice to be able to set a long name as the tokens name and a short version thereof as its display.

**Comment by Kruptein** [comment]
so just to be clear, you would like something like:

name: blabla
display: otherblabla

where otherblabla is for example the actual drawn text of the draw tool that can be changed by modifying the display value.
Whereas name is used for things like initiative listing and the selection info at the right side

right?

**Comment by dthv** [comment]
Yes, but no. :)

Currently we have, *on creation*:
* name: blabla
* display: blabla

*On change* of name it is:
* name: otherblabla
* display: blabla

Because display is not editable and does not change with name.

I want to keep name/display distinct, yet be able to change *both*. :slightly_smiling_face:

**Comment by Kruptein** [comment]
I think we're on the same page then!
