### ISSUE TITLE
[BUG] Auras not showing correctly. 

### ISSUE THREAD

**Issue by ekerstens** [Kruptein/PlanarAlly#720]
**Describe the bug**
Auras are only showing when `lighting source` is selected. 

**To Reproduce**
1. Create a token
2. Set `is a token`
![image](https://user-images.githubusercontent.com/49325583/112083846-06526700-8b45-11eb-8e5d-e762fcd5857a.png)
3. Add FOW to map
4. Full access by default
![image](https://user-images.githubusercontent.com/49325583/112083885-1b2efa80-8b45-11eb-9dba-1e31b0451936.png)
5. Add Aura as a Light Source (shows correctly)
![image](https://user-images.githubusercontent.com/49325583/112083766-defb9a00-8b44-11eb-8bb0-11efcaa3a4d7.png)
6. Uncheck `Light Source` and the aura disappears, where I would expect to see it as a vision source
![image](https://user-images.githubusercontent.com/49325583/112083855-0ce0de80-8b45-11eb-8975-b7fa49ffbd7c.png)

**Expected behavior**
I expect to be able to use auras as a form of vision that can be toggled on/off during play using the vision menu. 

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser chrome
 - Version 89.0.4389.90 (Official Build) (x86_64)

**Additional context**
None.

**Comment by ekerstens** [comment]
Reread the docs, with the changes and realized that what I need is a private light source. I see now that non-light source auras are used for effects which surround someone, and can be visualized through the addition of color.

**Comment by Kruptein** [comment]
yeah maybe `Vision source` would be a better name
