### ISSUE TITLE
[BUG] Auras create black void when FOG is turned off. 

### ISSUE THREAD

**Issue by ekerstens** [Kruptein/PlanarAlly#738]
**Describe the bug**
I have a single set of tokens for my party that I move between locations. Some of the tokens have darkvision, enabled a private light source. When vision is enabled for any token on the map, these auras create black voids on the map, where normally they would do the opposite if FOW was turned on. 

**To Reproduce**
1. Create a location with FOW turned off. 
2. Add a token with an aura configured as a light source. 
3. A black void appears around the token. See the screenshots for an example. 

**Expected behavior**
Expect that light sources would have no effect in a region with FOW turned off. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49325583/115622204-63f4e300-a2ac-11eb-9b83-e5614fad73a1.png)
![image](https://user-images.githubusercontent.com/49325583/115622236-6f480e80-a2ac-11eb-98f0-858fe259b03f.png)
![image](https://user-images.githubusercontent.com/49325583/115622275-7bcc6700-a2ac-11eb-95cd-8b1eab2dc449.png)
![image](https://user-images.githubusercontent.com/49325583/115622297-81c24800-a2ac-11eb-95a1-9f9ea874812e.png)
![image](https://user-images.githubusercontent.com/49325583/115622310-871f9280-a2ac-11eb-9e79-bd8c23371ad6.png)

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Browser: chrome
- Version 90.0.4430.72 (Official Build) (x86_64)

**Additional context**
None

**Comment by dthv** [comment]
This is actually a known bug. See, e.g., [this discussion](https://github.com/Kruptein/PlanarAlly/discussions/628). That being said, it has not been officially issued. :slightly_smiling_face:

**Comment by Kruptein** [comment]
At long last I finally fixed this in #962
