### ISSUE TITLE
[BUG] Account Settings show blank page

### ISSUE THREAD

**Issue by ptolstoi** [Kruptein/PlanarAlly#747]
**Describe the bug**
After the Vue3 Update the account settings show a blank page.

**To Reproduce**
1. Login as a user
2. Click on "Settings"
3. See blank page, console warning: `No match found for location with path "/settings"`

**Expected behavior**
See the account settings

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox/Chrome/Safari/...

**Additional context**
I had a quick look into the source code, the route as well as the files for the account settings are complete gone.

**Comment by Kruptein** [comment]
Good catch, somehow missed this while porting
