### ISSUE TITLE
Cannot move inititive window in Firefox

### ISSUE THREAD

**Issue by W8BSD** [Kruptein/PlanarAlly#75]
While the initiative window can be moved easily in Chrome, in Firefox it doesn't seem to be movable.

Running Firefox 61.0.2 (64-bit) on FreeBSD.

**Comment by W8BSD** [comment]
Same issue with the Edit Asset window.

**Comment by Kruptein** [comment]
The drag feature for modals and dialogs indeed seems to be broken on
Firefox on all platforms
