### ISSUE TITLE
[BUG] Initiative Tracker sometimes doesn't order correctly

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#765]
**Describe the bug**
Changing initiative value sometimes doesn't change the listing order automagically

**To Reproduce**
1. Add tokens to initiative
2. Set value for iniative
3. Error may or may not occur, no console output
4. Workaround is to remove token from initiative and readd

**Expected behavior**

**Screenshots**
![1621116919](https://user-images.githubusercontent.com/2258333/118379608-9216cb80-b5a9-11eb-84ba-1afce9ae201c.png)
![1621116932](https://user-images.githubusercontent.com/2258333/118379611-9511bc00-b5a9-11eb-9748-92950cbdc599.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Firefox 88 and Chromium 90.0.4430.212
- Current PA Docker build

**Additional context**
Unable to reliably replicate I would assume it's mostly caused by latency. Needs further investigation.

**Comment by 10leej** [comment]
Could be related to #566 and same behavior in complaint 3 of #350 seems this is a duplicate issue.

**Comment by Kruptein** [comment]
This is addressed in the initiative rework that hit dev last week
