### ISSUE TITLE
[BUG] grid size accepts values <=0

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#776]
The grid size input accepts values below or equal to zero, creating funky behaviour, until reasonable grid size is restored and location is re-accessed. User inputs <= 0 should be defaulted to 1. :slightly_smiling_face:

**Comment by Kruptein** [comment]
I cannot reproduce this. The code hardchecks on values >= 1.

If the input field contains a non-valid number it will not be used, the input will still show it until one switches tabs though.

![image](https://user-images.githubusercontent.com/1814713/120439487-dc0df880-c382-11eb-85a2-e9011d7c0cbf.png)

**Comment by dthv** [comment]
Sorry, I was very imprecise.

I'm talking about `unit size` (in feet, meters, or unicorns) *not* grid size in pixel. I cannot even argue this to be confusing as it's worded pretty clear, imho. :facepalm:

Anyway, as of 0.26.1 used with Firefox 88.0.1 (64bit) on Linux, I can input values <= 0. Please don't ask why I tried in the first place. :wink:

**Comment by Kruptein** [comment]
I see, that indeed has no boundary check
