### ISSUE TITLE
[FEAT] allow ruler not show measuring

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#777]
Not all systems use strict measurements on their maps. Some, e.g., use abstractions like zones. While grid *size* itself is necessary for all kinds of vision related things, the exact measurements may be indifferent to the game system played and purely for the math in the background. Thus, it can be confusing to be shown numbers when using a ruler (e.g. to check line of sight or something like that).

I'd like to propose a button to disable the ruler showing measurements as a grid setting (in both general and location-specific settings).

Comment: The feature to not show any measurements (e.g. to simply count squares/hexes) is already implemented by allowing users to leave grid's "size unit" empty.

**Comment by Kruptein** [comment]
You propose a specific setting associated with the campagin/location.
What about a toggle on the ruler tool itself, like the 'show public' toggle?

**Comment by dthv** [comment]
That's actually better, since sometimes players need to measure for e.g. lights.
