### ISSUE TITLE
[BUG] Markdown  not being process properly in annotations. 

### ISSUE THREAD

**Issue by develroo** [Kruptein/PlanarAlly#793]
The markdown syntax for BOLD, SUPER and SUB script are not being interpreted. 

You can test this by adding an annotation to a token and using the BOLD syntax as given by the [VUE Markdown Guide](https://ej2.syncfusion.com/vue/documentation/rich-text-editor/markdown/#markdown)

Other markdown syntax from that list do work including the symbols

![bug](https://i.imgur.com/5XJxbOe.png)

PlanarAlly version 0.27.0 from the Git docker build. Viewed in Firefox 89.02 Linux

**Comment by Kruptein** [comment]
This is I think already fixed on develop.

I did a fix for the annotation tool no longer rendering html and while that doesn't seem to be related to the bold tags, my own live server running on develop does render bold text correctly surrounded by `**`

If this isn't fixed after next release feel free to re-open the ticket

**Comment by develroo** [comment]
So if  I pull the git changes switch to dev track and rebuild the docker image it should be fixed? I am guessing I just by default pulled the master branch so?

**Comment by Kruptein** [comment]
Well it depends on how comfortable you are with running development stuff :D

the master branch is used for proper production releases, they should be as stable as it gets.
the develop branch is used for active development changes, ideally it should also be pretty stable, but some mishaps can happen from time to time.

**Comment by develroo** [comment]
Fairy nuff. ;)
