### ISSUE TITLE
[BUG] Aura/LOS lights do not rotate with tokens. 

### ISSUE THREAD

**Issue by develroo** [Kruptein/PlanarAlly#795]
Create a token. Add an aura to it. Give it an angle of spread. It will point by default up.

![Default behaviour](https://i.imgur.com/dL5nFMg.png)

Try to rotate the token the LOS light does not move with tokens direction. 

![Error in light](https://i.imgur.com/j2IV8ht.png)

Really, the light should act like a torch and shine where the token is facing. 

Additionally rotation of tokens should be the default as well as movement for player, especially when it comes to mobile clients which dont' have TAB or a keyboard.

**Comment by Kruptein** [comment]
Which browser/platform are you using btw?

The Aura UI is meant to be:

![image](https://user-images.githubusercontent.com/1814713/128186581-bed72ff4-4150-4bde-81eb-cf9564c12cf7.png)

but the name input is for some reason not properly aligned for you

**Comment by develroo** [comment]
Ahh I see you fixed that. Good job. But that angle wheel needs looking at too it is far too fiddly to get 90 180 270 angles, which is what I need to use for torches to light areas.

Cheers.

**Comment by Kruptein** [comment]
Could you make a separate ticket for that!
