### ISSUE TITLE
Question(PlanarAlly 0.27.0)-  RUNNING IN NON SSL CONTEXT  (planarserver.p y:61)

### ISSUE THREAD

**Issue by kagangtuya-star** [Kruptein/PlanarAlly#801]
I installed the program on my own windows server, but it couldn't run after I opened it.And then there's this error.

`fatal: not a git repository (or any of the parent directories): .git  
2021-07-20 02:21:43,993 - WARNING -  RUNNING IN NON SSL CONTEXT  (planarserver.py:61)  
======== Starting Webserver on http://0.0.0.0:8000/ ========  
API Server disabled  
(Press CTRL+C to quit)`  
![搜狗截图20210720023420](https://user-images.githubusercontent.com/73411104/126210481-eab2513d-4284-4f8b-b8fd-43fca76861f1.png)
What should I do to make it work？thanks

**Comment by Kruptein** [comment]
Visit http://0.0.0.0:8000 in your browser

**Comment by kagangtuya-star** [comment]
I tried several times, but it still didn't seem to work
`This page is not working properly. 
0.0.0.0.0 did not send any data.
ERR_ EMPTY_ RESPONSE`

**Comment by Kruptein** [comment]
You're using 5 0's it should only be 4, you can also try `http://localhost:8000` instead
