### ISSUE TITLE
[FEAT] Improvement on Toolbar

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#807]
**Is your feature request related to a problem? Please describe.**
Not clear enough on build/play mode, the bold text does not stand out enough for high resolution displays at 100% scaling
![1627820798](https://user-images.githubusercontent.com/2258333/127770945-81f8f4b8-6a80-4c60-b549-a6f6064674ab.png)
![1627820803](https://user-images.githubusercontent.com/2258333/127770947-bcec3d55-6c31-44a3-950e-1f540335dd26.png)

**Describe the solution you'd like**
increase the boldness or use an alternative color for the blue/teal box

**Describe alternatives you've considered**
maybe a toggle switch or a border around the UI?
![1627821059](https://user-images.githubusercontent.com/2258333/127770939-a7f7f125-0998-4402-b067-81efbfb7af5d.png)

**Comment by develroo** [comment]
Yeah, I just suggested it should be inverted when  activated. Much easier to achieve and see

![Build](https://i.imgur.com/YRknDFA.png)

![Play](https://i.imgur.com/1bx1V5l.png)

**Comment by 10leej** [comment]
is it available in a container yet or do I need to build it?

**Comment by 10leej** [comment]
pulled kruptein/planarally:dev

no changes, don't have time to build from source right now.
![1628094794](https://user-images.githubusercontent.com/2258333/128219511-a6dd881d-3855-4100-9393-471d1d1d7e8d.png)

**Comment by develroo** [comment]
> is it available in a container yet or do I need to build it?

Yes you need to build the container yourself. 

`git clone https://github.com/Kruptein/PlanarAlly`

`git checkout dev. `

`docker build -t planarally:dev .`

FWIW the update is worth it. MUCH clearer. 

![Build](https://i.imgur.com/iVJYLOd.png)
![Play](https://i.imgur.com/7LMZsbm.png)

**Comment by Kruptein** [comment]
> pulled kruptein/planarally:dev

Right, I still need to setup a github action to do the docker build&push to dockerhub as they no longer do it automatically themselves
