### ISSUE TITLE
Reconsider save format

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#81]
Currently the python server structure is simply stored on disk and reloaded when started.

I would like to reconsider this and maybe look at either databases (e.g. sqlite) or storing json files.

**Comment by Kruptein** [comment]
I'm particularly interested in trying peewee out as an orm, I've dabbled with sqlalchemy in the past and would like to see how peewee compares.

**Comment by schemen** [comment]
heya! I use peewee for my project m2em, I can totally recommend it for smaller sized projects that don't use that many transactions - where you can still switch to a fully fledged postgre as well :)

**Comment by Kruptein** [comment]
I've started work on this in two branches.  Due to the fact that the current/old save system basically writes python structures straight to disk, it requires the existence and API of these classes when written to also exist when loaded.  This means

**Comment by Kruptein** [comment]
The save rework is almost done, I only have to finish the initiative system and then a proper playtest and then it's good to go

**Comment by schemen** [comment]
@Kruptein Quick question regarding that. With hosting PA on dndbox.com also comes with some data =)

At the moment, the save file is 1GB large and the saved asset folder about 287m in relation to that. What is exactly saved? I haven't had a chance to look at the code :/

**Comment by Kruptein** [comment]
yes, that's exactly something that will, potentially, greatly improve with the save rework I'm doing.

Currently the save file uses dbm, there are multiple implementations and python will attempt to use the native implementation before the more 'dumb' implementation.  I've however found that on my 32bit linux home server, this native system is way worse and uses a lot of disk which the 'dumb' implementation doesn't.

Either way, I'm moving away from that system and will go to sqlite, which uses even less data than the 'dumb' implementation above.

I honestly have no idea why the native dbm implementation can use up to 1gb, but as said I hope to get rid of it soon :)

**Comment by Kruptein** [comment]
I just checked and noticed that my own save is also 900MB in the 'native' format, whereas the dumb format is 3MB and the sqlite is 2MB, so yeah expect great size reductions

**Comment by Kruptein** [comment]
I'm almost done, only the asset_manager is still left to do.

@schemen, @W8BSD or @AntiSC2  if any of you have time to try the changes out to see if anything behaves unexpectedly, that would be greatly appreciated.

To test it you'll have to do 2 things
1. pull the `feature/save-conversion` branch and run the update script from within the PlanarAlly folder `python ../scripts/convert/database.py <save_file>`
If save_file is not provided it will default to the default save file 'planar.save'
This will create and populate the planar.sqlite database with the provided save file.
After this step the original save file is no longer used.

2. pull the `feature/save-rework` branch.

now run the server and test it out :)

These steps should at no point change anything in the original save file, but for obvious reasons this should be tested in a test environment.

**Comment by Kruptein** [comment]
In the meanwhile the asset manager is also covered.  so I believe everything should now work with the database format

**Comment by schemen** [comment]
Any chances those two branches can be merged into dev for testing? Or is there any reason for it to be two branches?

**Comment by schemen** [comment]
Ah I see okay! As a suggestion I would propose that you would create a "0.9.1" release with the save-conversion branch  and a follow up branch to run planarally again. What do you think?

**Comment by Kruptein** [comment]
I'm not sure yet, I agree that having a 0.10 and 0.11 in quick succession seems strange, but on the otherhand having 0.9.1 and 0.10 makes it look rather unimportant.

Ultimately whichever choice is made, the most important thing is that the documentation for upgrading from the current system to the newest should be very clear to avoid any confusion.

**Comment by Kruptein** [comment]
Also according to semver, with versioning X.Y.Z, incrementing Z should only happen for bugfixes/patches, which this isn't so it has to have at least a minor bump.

So I'll stick with releasing 0.10 and 0.11

**Comment by Kruptein** [comment]
Release 0.10 and 0.11 have been created.

Sqlite is now the save format used on dev, make sure to do your upgrade as described in the releases.
