### ISSUE TITLE
[FEATURE] Impossible to set direction of auras to precise values.

### ISSUE THREAD

**Issue by develroo** [Kruptein/PlanarAlly#813]
Aura directions are controlled by a little spin wheel which you have to click and drag to move but it being so small makes those movements very imprecise.

While the idea is simple enough and perhaps if you are on a tablet or similar device you could pinch to zoom, on a desktop browser even with a mouse it is tricky to get the angles exact. 90, 180 , 270 etc 

Perhaps, if possible, we can have either a text field, similar to the angle for exact measurements or dots around the wheel which can correspond to exact angles. Maybe even both?

There should be enough room on that line as the Angle widget is already way  bigger than it needs to be. Perhaps also change the tile of that section  to `Angle/Direction`

![Panel](https://i.imgur.com/Myj98u2.png)

**Comment by Kruptein** [comment]
The redundant space seems to be a bug I need to fix for firefox, as it displays differently in chromium based browsers

![](https://user-images.githubusercontent.com/1814713/128186581-bed72ff4-4150-4bde-81eb-cf9564c12cf7.png)

**Comment by develroo** [comment]
Fairy nuff. But even on Chromium there is enough space for another drop down/ spin box.

**Comment by Kruptein** [comment]
Agreed, just something i noticed
