### ISSUE TITLE
[BUG] Token variant options do not seem to work anymore

### ISSUE THREAD

**Issue by ankorite** [Kruptein/PlanarAlly#817]
**Describe the bug**
Variant options in tokens do not seem to work anymore

**To Reproduce**
1. Go to properties on any token
2. Click on the plus to add a variant

**Expected behavior**
A window should open to create the variant token

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 92.0.4515.159 (Official Build) (64-bit)

**Additional context**
Server running in a Docker container on Debian. Version 0.28.0. Might have been introduced in 0.27.0 but I do not know.

**Comment by Kruptein** [comment]
You're correct in that they are disabled right now.

I wasn't aware there were people actually using it :smile:

While porting to the new frontend, the file picker modal wasn't ready yet. That is resolved now, but I had a feeling that the feature could sometimes completely brick a campaign, so I wanted to find some time to investigate it further before enabling it again.

Can I ask how extensively you've used it and if you noticed any issues with it ?

**Comment by ankorite** [comment]
I have a druid that uses it for his shape change ability. This way I can pre-setup his common shapes and sizes to have him change to mid game. Although doing it on the fly hasn't been too bad, the tracking and auras have to be set back up or copied over.

I did notice some weirdness with it but nothing I could consistently reproduce. Token duplication being the main one that comes to mind. There might have been one time it messed up the token entirely and had to be removed.

**Comment by TOUHOUCON** [comment]
My players often use multiple images as their other forms, so I really like this feature.
Of course, there have been many bugs  jajajaja.
If it can be fixed, I hope it can be done!

**Comment by Kruptein** [comment]
No worries, it will come back, and given that people use it, I'll try to focus on it :)

**Comment by Kruptein** [comment]
I just came back from holiday and hope to get some solid dev time in in the following weeks

**Comment by TOUHOUCON** [comment]
Thank you!

**Comment by Kruptein** [comment]
I've re-enabled the feature on the dev branch
