### ISSUE TITLE
[FEAT] Changing the light of Default of Access

### ISSUE THREAD

**Issue by TOUHOUCON** [Kruptein/PlanarAlly#822]
**Is your feature request related to a problem? Please describe.**
When I run games, I often need to use some conditions pictures from assets to keep track of everyone's conditions like Roll20.
Only default access can be saved in template, so I had to use default access to ensure that players would not often ask me "Why can't I move my token?" "Because you clicked on the condition image, please frame your token."
But that's not the funniest, when I put conditions pictures on enemies, they shine like stars in the night, lighthouses in the mist.
Because the default access can glow.

**Describe the solution you'd like**
Default of Access don't glow.

**Describe alternatives you've considered**
At least movement access?or a switch can set glow or not for Default of Access.

**Additional context**
Did I write in the wrong place ......

**Comment by Kruptein** [comment]
I might be misunderstanding you, but when you say "glow" do you mean the small circle that shows tokens?

This "glow" is _only_ present for shapes explicitly marked as "is token".  Condition icons have no benefit from being marked as "tokens". The term "token" has a very specific meaning in PA, see https://www.planarally.io/docs/terminology/ for more info.

**Comment by TOUHOUCON** [comment]
Yes, the small circle. Forgive me for using some pictures to explain my question, because I realize that this could be a bug.
<img width="845" alt="1" src="https://user-images.githubusercontent.com/49478304/134446103-b5cc5b28-587a-4f0f-b47f-d709f78f3014.png">
This picture is the normal case, there is no small circle.
<img width="796" alt="2" src="https://user-images.githubusercontent.com/49478304/134446111-51f69e87-f466-49f5-8fbd-60fc4b5fc8d2.png">
This picture shows the case with token marked, with small circles.
<img width="766" alt="3" src="https://user-images.githubusercontent.com/49478304/134446114-58893bd5-fd91-4e9f-9441-ced32f193c00.png">
This picture is not marked as a token, but still has small circles.Why？
<img width="814" alt="4" src="https://user-images.githubusercontent.com/49478304/134446541-2ec309de-2a60-448d-af59-3097a5d80479.png">
Because I gave it the default access.

**Comment by Kruptein** [comment]
Sorry for the late response, but this was indeed a bug
