### ISSUE TITLE
[FEAT] Config option to disable new user registration

### ISSUE THREAD

**Issue by zack-emmert** [Kruptein/PlanarAlly#843]
**Is your feature request related to a problem? Please describe.**
When running a small private VTT, I need it on the public internet so my players can connect, but I don't want any random stranger to be able to register for an account.

**Describe the solution you'd like**
A configuration option to disable registration on the login page, and a python script (since there's currently no admin UI) to make it easier for an admin to create new users

**Comment by Kruptein** [comment]
Implemented in #854
