### ISSUE TITLE
[BUG] Copy/Pasting Groups Affect Badge Count

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#849]
**Describe the bug**
Copying multiple assets then pasting them pauses the badge count, this was not the case in older versions (I think it changed somewhere around v 0.23 or so)

**To Reproduce**
1. Make a bunch of assets and enable the badge option in properties
2. Select them all
3. Copy
4. Paste

**Expected behavior**
Badge count continues counting up as if you copy pasted normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser Firefox 94
 - Version 0.29.0

**Additional context**

https://user-images.githubusercontent.com/2258333/140619433-275ea010-7bcf-43ed-8595-c950c35ac229.mp4

**Comment by Kruptein** [comment]
it must have been broken for a year now :P since the new group logic.
