### ISSUE TITLE
[BUG] font-face not including PA_BASEPATH

### ISSUE THREAD

**Issue by plasticbiker** [Kruptein/PlanarAlly#860]
In version 0.29.0, running in a container with the ```--env BASE_PATH=planarally```. All other components correctly use the base path, except for the font included in the stylesheet.

```podman run -d --name planarally -p 8000:8000 -v /opt/planarally/data/:/planarally/data:Z -v /opt/planarally/assets/:/planarally/static/assets/:Z --env PA_BASEPATH=/planarally kruptein/planarally```

See line 8 from the NGINX log below:
```
10.0.2.100 - - [05/Jan/2022:02:34:21 +0000] "GET /planarally/auth/login HTTP/1.1" 200 626 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:21 +0000] "GET /planarally/static/vite/index.10362ea7.js HTTP/1.1" 200 284433 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:21 +0000] "GET /planarally/static/vite/index.928935e3.css HTTP/1.1" 200 41487 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:21 +0000] "GET /planarally/static/vite/vendor.c27b71c9.js HTTP/1.1" 200 1538222 "https://***SOMESERVER***/planarally/static/vite/index.10362ea7.js" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/static/vite/vendor.c27b71c9.js HTTP/1.1" 200 1538222 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/api/auth HTTP/1.1" 200 31 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/api/version HTTP/1.1" 200 40 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /static/vite/OpenSans-Regular.037236ed.ttf HTTP/1.1" 401 179 "https://***SOMESERVER***/planarally/static/vite/index.928935e3.css" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/api/changelog HTTP/1.1" 200 2061 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/static/favicon.png HTTP/1.1" 200 15661 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/static/img/login_background.png HTTP/1.1" 200 54923 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/api/notifications HTTP/1.1" 200 2 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/static/img/carousel_floors.png HTTP/1.1" 200 423560 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:22 +0000] "GET /planarally/static/img/carousel_vision.png HTTP/1.1" 200 297281 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
10.0.2.100 - - [05/Jan/2022:02:34:23 +0000] "GET /planarally/static/favicon.png HTTP/1.1" 200 15661 "https://***SOMESERVER***/planarally/auth/login" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" "-"
```

**Comment by plasticbiker** [comment]
A quick hack was to add the following line at Line 20 of the Dockerfile

```
# Hack to fix font-family include issue
RUN sed -i 's/\/static\/vite\/OpenSans-Regular/.\/OpenSans-Regular/' /usr/src/server/static/vite/index*.css
```

**Comment by Kruptein** [comment]
Is that the only thing that doesn't work properly?
Because locally I seemingly have more issues with the basepath now that I'm playing with it again.

**Comment by plasticbiker** [comment]
From what I can tell, all of the other files include the basepath or use relative path references.  It might be a bug specific to the Font-Path directive in Vue Cli, but I don't have enough experience with the framework to be sure.

From what I can tell, the font-face directive should use relative paths, similar to how other files are referenced. I'll play around with the App.vue file, where the font-face directive is, and switch the font to a relative file reference. 

Since I don't know the framework, you might be able to make the change faster than my hacking/beating it into submission.

**Comment by Kruptein** [comment]
Yes I know what the issue is, I have a hacky workaround myself, a more proper solution would require me to redo the way these subpaths are handled which is more involved :P

But everything else looks fine then? Because I seem to have more issues than the font alone when using a modified basepath.

The root problem:
The font file is loaded with a relative path to the font file in my client assets, and vite will rewrite this correctly to use a different basepath if configured, _however_ the current implementation to handle different basepaths is mostly server-handled and the client basePath is not modified, causing the font file to always be compiled for a "normal" path.

The reason I didn't add the basepath info to the client so far is that it requires you to rebuild the client if you change the basepath, which I hoped to avoid.

**Comment by plasticbiker** [comment]
That makes sense. The little sed hack I added to the Dockerfile does appear to resolve the specific issue with the font and stylesheet.

I'm hosting another session tomorrow, so I'll keep an eye out for any other instances of invalid subpathing. Last game I hosted, I had NGINX catching /static/vite and sending it to the correct subpath. I'll check the NGIX log after my game tomorrow. Hopefully that will catch any stragglers.

The other thing that I did notice regarding subpathing was that the generated game invite links are missing the subpath. I was planning to poke at the code a bit to see if I could fix it this weekend.

**Comment by plasticbiker** [comment]
I had a thought about how to make the basepath more configurable. Could you compile the application with a keyword for a basepath, then use grep/sed to replace the keyword on first run of the container?

**Comment by Kruptein** [comment]
that's fine for a docker build, but not really feasible for standalone running

**Comment by Kruptein** [comment]
After some more bug reports related to subpaths, I've decided to change the subpath handling.

#870 will solve the font issue along with others, it has some implications in usage though!
