### ISSUE TITLE
[FEAT] ARM Docker build?

### ISSUE THREAD

**Issue by PalasX** [Kruptein/PlanarAlly#861]
I'm almost positive this is the wrong place to request this, but i wasn't really sure where else to post it. ARM docker image build for us Pi hosters?

Or add some info to the self-host documentation page for one that may already be built here?
https://www.planarally.io/server/setup/self-hosting/

There's a good chance there's a simple one-liner to build the image ourselves and i'm just too inexperienced with the docker build command to do it right :)

**Comment by chrispoupart** [comment]
I'm running this in a container on my Pi4 right now. I built it directly on my Raspberry Pi using the GitHub repo.

But it would really be great if this was just added to whatever automated build system is going on here.

I'm assuming that Docker is being used to build the containers, in which case you can configure a new build profile which will build multi-arch images by default: 

https://www.docker.com/blog/multi-arch-images/

**Comment by PalasX** [comment]
@chrispoupart is there a one-liner command to build the image for a pi4? i'm a complete and total noob at actually generating docker containers from scratch/repo. Much appreciated!

**Comment by Kruptein** [comment]
@chrispoupart the images are built here on github CI, [see here](https://github.com/Kruptein/PlanarAlly/blob/dev/.github/workflows/docker.yml).

If you have the time/knowledge to change it to support arm could you make a PR ?

**Comment by chrispoupart** [comment]
Sure. It'll give me a chance to dive into GitHub Actions a little more (I use GitLab CI most of the time).  I'll hopefully have something ready for you by this weekend or early next week.

**Comment by Kruptein** [comment]
Yeah no rush, take your time when you can.

I've used them all by now I think :P github/gitlab/bitbucket/azure/circle ci. PA uses a mixture of github and circle CI. Ultimately the core is kinda similar, although I do love circle CI's ssh-into the runner feature

**Comment by PalasX** [comment]
Awesome that there is now a build for ARM64, but as the 64bit version of RasPiOS only recently got released, i was hoping there might be a chance for an Arm7 container? Is it as simple as changing the compile target? If it's just me and a tiny handful of others trying to run containerized on a Raspberry Pi, dont even worry about it. I'm still chugging along on "bare metal" as it were :)

**Comment by chrispoupart** [comment]
Yeah, the scaffolding is there now for multi-arch builds. It should be as simple as updating the platforms to include `linux/armv7` in that list of build architectures.
