### ISSUE TITLE
[BUG] Upload folder to asset manager

### ISSUE THREAD

**Issue by Mahakam20000** [Kruptein/PlanarAlly#885]
**Describe the bug**
It is impossible to upload a folder (and eventually subfoder) dropping it in the asset manager. It stucks with the loading bar reporting "Uploading files 0 / 1"

**To Reproduce**
1. Open Asset Manager
2. Drag a folder from local PC and drop it into the asset manager
3. See the progress bar saying "Uploading files 0 / 1" and nothing appen

**Expected behavior**
Upload the folder and its subfolder or display an error

**Screenshots**
![image](https://user-images.githubusercontent.com/19763534/158880738-1fa9d346-9a4c-4106-b735-420a8aaa7836.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge
 - Version: latest

**Comment by Kruptein** [comment]
What do you mean with latest version, the latest official release or develop

**Comment by Mahakam20000** [comment]
Edge: Versione 99.0.1150.39 (Build ufficiale) (64 bit)
Firefox: 98.0.1 (64 bit)
Chrome: Versione 99.0.4844.51 (Build ufficiale) (a 64 bit)

**Comment by Kruptein** [comment]
No I meant PA version :p

**Comment by Kruptein** [comment]
either way, folder drop support is only available on the dev branch for now, will be part of the next release

**Comment by Mahakam20000** [comment]
Damnit XD
hype for the next release!
Official docker images of PA, btw.
