### ISSUE TITLE
[BUG] ReverseProxy Apache2 can not get it to work

### ISSUE THREAD

**Issue by codesnippy** [Kruptein/PlanarAlly#886]
**Describe the bug**
I am trying to get Planarally to run on my domain name http://planarally.example.com/ trough Apache2
The login part works but it won't show any assets. And when opening a game there is a red border around the screen.
The location menu is not shown at all. And the settings menu pnly shows marker / client settings and exit.

When I access the planarally instance on the local network directly it all works

**To Reproduce**
In Apache I use a sites config file with the following settings.

```conf
<VirtualHost *:80>
    ServerName planarally.example.com
    ProxyPreserveHost On
    ProxyRequests off
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
</VirtualHost>
```

**Expected behavior**
I was hoping to get the same functionality as on the local network.

**Desktop (please complete the following information):**
 - Debain Bulllseye
 - Firefox / Brave

Hope you can direct me in the right direction to get it working. Can not find any information in the documentation to get it running the correct way

**Comment by Kruptein** [comment]
Hosting on a subpath is covered in the docs [here](https://www.planarally.io/server/advanced/subpath/)

Your proxypass and proxypassreverse need some changing I believe

**Comment by Kruptein** [comment]
Oh woops sorry that's not a subpath

**Comment by Kruptein** [comment]
Yeah I was a bit too quick, subpaths are in general also not recommended so a subdomain is absolutely fine.

I've never used apache with PA, so I don't know all the specifics.
What I can say is that both the assets not appearing and the red border are due to the websockets (socket.io) not working properly.  So I would recommend to see if you can find any info on how to use socket.io with apache

**Comment by Kruptein** [comment]
I'll ask around to see if anybody on the discord has an apache setup

**Comment by codesnippy** [comment]
Thank you for the tip on the socket.io.

Got it working now. I used the follwoing in my sites config file.

```conf
<VirtualHost *:80>
    ServerName planarally.example.com
    ProxyPreserveHost On
    ProxyRequests off
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/

   RewriteEngine on
   RewriteCond %{HTTP:Upgrade} websocket [NC]
   RewriteCond %{HTTP:Connection} upgrade [NC]
   RewriteRule ^/?(.*) "ws://127.0.0.1:8000/$1" [P,L]

</VirtualHost>
```

**Comment by Kruptein** [comment]
Ah nice, yeah it would be good to add it to the docs :p
