### ISSUE TITLE
[BUG] Canvas is too wide for small windows 

### ISSUE THREAD

**Issue by Chridy** [Kruptein/PlanarAlly#898]
The canvas (id "babylon") is too wide for small screens, with a minimum width of 1806px. This causes a horizontal scrollbar to appear and prevents panning with the middle mouse button.

Adding "max-width: 100%" to #babylon fixes the issue and doesn't appear to cause any side effects (I've been doing this manually in the dev tools for several sessions and have not noticed anything break).

Tested on Chrome

**Comment by Kruptein** [comment]
This is already fixed on dev in [this commit](https://github.com/Kruptein/PlanarAlly/commit/1c18c86242dc6fd5e90cc49011e83bdf1b8ab89e)
