### ISSUE TITLE
Tokens appear as black dots when Fill Entire Canvas and Only Show Lights in LOS are both turned off

### ISSUE THREAD

**Issue by poltergeisha** [Kruptein/PlanarAlly#90]
![image](https://user-images.githubusercontent.com/8014948/47628820-8e172100-db05-11e8-8074-63290c066864.png)

**Comment by Kruptein** [comment]
I've noticed this as well recently, it will be one of the first things I look at when I'm done with my save rework.  Unless it's very important for you to have a fix asap.

**Comment by poltergeisha** [comment]
Meh, I just keep LOS turned on and that fixes it for now.

**Comment by Purzelkater** [comment]
Had the same effect here. As an easy workaround the DM had to "reveal" all tokens on the fow layer with the draw tool.

**Comment by Kruptein** [comment]
Can anyone confirm if this is still the case on the most recent master/dev branches ?
