### ISSUE TITLE
[BUG] Strange white & scroll bar

### ISSUE THREAD

**Issue by TOUHOUCON** [Kruptein/PlanarAlly#905]
**Describe the bug**
![BUG](https://user-images.githubusercontent.com/49478304/162555888-2f6d77f4-78d4-4342-99cd-216926c1d9f1.gif)

**To Reproduce**
Resize browser

**Desktop (please complete the following information):**
- WIN11
- chrome,edge,etc.
- the latest version

**Comment by Kruptein** [comment]
Thanks for the report, I _think_ this is fixed in the dev branch already, so should be included in the next release.
