### ISSUE TITLE
[FEAT] Map auto resize based on name

### ISSUE THREAD

**Issue by oeykmiih** [Kruptein/PlanarAlly#906]
**Is your feature request related to a problem? Please describe.**
When importing map, always have to resize them to the correct dimension.

**Describe the solution you'd like**
Get the grid size from the filename, I believe most of the maps people have the "\d\dx\d\d" for grid size in their name. (just how  OwlbearRodeo does it)

**Comment by Kruptein** [comment]
Ah cool, I wasn't aware that was a convention, that would indeed make things easier
