### ISSUE TITLE
Tokens appear as red dots to players who have access to them

### ISSUE THREAD

**Issue by poltergeisha** [Kruptein/PlanarAlly#91]
First of all, you're fricking amazing. We've entirely replaced Roll20 with Planar Ally and use it every week now.  I hope you can keep up the good work. ^_^  If you had a paypal I'd send some cash your way.

Anyway, here's what the bug looks like: 
![image](https://media.discordapp.net/attachments/336303025092296704/506317422421213184/planar_ally_red_dot.JPG)

It happens to all my players on only the token they can control.

**Comment by Kruptein** [comment]
Hmm this is one I haven't noticed myself yet.  On which branch are you ?

Does this happen to all kind of shapes? (draw tool, create basic token and assets)

**Comment by poltergeisha** [comment]
I'm using whichever branch dndbox.com is using.  Before that I was hosting the latest release and I experienced the bug on there as well.  It only seems to happen with tokens that are marked as being tokens, and it happens with create basic tokens as well.

**Comment by poltergeisha** [comment]
Also this is perhaps irrelevant but @schemen you're awesome too, thanks for hosting dndbox.  I was previously hosting planar ally myself using localtunnel but it was kind of a pain and dndbox has made my life much easier and is allowing some of the less tech-saavy GM's in my group to start using planar ally :)

**Comment by Kruptein** [comment]
Alright I'll investigate it.

Was there anything in the PA setup in particular that was annoying for you to host yourself?
It's definitely nice that dndbox exists, but I'm also always interested in any tips to further improve the hosting aspect as well ;)

**Comment by poltergeisha** [comment]
Eh, mostly the problem was with localtunnel, not planar ally.  Local tunnel allows you to set your own subdomain, so I tried to keep the same subdomain all the time so my players wouldn't be confused, but if there was a problem and I had to restart local tunnel it would be a while before I could get my subdomain back, so I'd have to give my players a new link.  This is especially onerous because we have planar ally embedded in a page which also has chat/radio, dice roller, and combat reference embedded in it.  Additionally, having to do anything with the command line basically scared away the other GM's in my group from using PA, Now that dndbox is an option, they're all of it. :)

**Comment by poltergeisha** [comment]
I will say that the number one thing that's confused my players is the sign in / invite rigmarole.  The fact that you have to go to the bare link and sign in before you click the invite link shouldn't be that hard to grasp but apparently it's very confusing :P

**Comment by Kruptein** [comment]
Fair enough, cool setup!

**Comment by Kruptein** [comment]
and indeed I aim to change the invite system to create a link immediately and guide you to the login/register page as well if you're not currently logged in, it's currently pretty barebones ;)
