### ISSUE TITLE
Add translation options

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#92]
Look into providing language selection for the UI.

Possibly using i18next

**Comment by Kruptein** [comment]
https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-vue-app-with-vue-i18n seems like a good resource to integrate i18n in PA.

It has an attractive set of features (pluralization, grouping, extending...)

**Comment by dthv** [comment]
Just scrolled by, accidentally: This can be closed? :smile:
