### ISSUE TITLE
Add toggle between ft and m

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#94]
Option to choose metric system instead of imperial system

**Comment by Purzelkater** [comment]
For others with the same "problem", I was able to fix this easily by editing  the planarally*.js file on the static/js directory. As you can see on the screenshot I have switched "ft" to "m" on the label and rounded the value to 1 decimal digit. Also I have added a color to the label.

![ft_to_m](https://user-images.githubusercontent.com/44810275/48192417-04a6f080-e348-11e8-85bf-4353515f5bcf.jpg)
