### ISSUE TITLE
[FEAT] Add Percentile dice rolls. 

### ISSUE THREAD

**Issue by develroo** [Kruptein/PlanarAlly#966]
This can be done in a few ways, I guess. 

One die could be a different colour from the other.

![2d10](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fa%2Fa6%2F2D10.jpg%2F1024px-2D10.jpg&f=1&nofb=1)

 You could have 2 dice of 10's and 1's 

![2d10-tens-ones](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fi.ebayimg.com%2Fimages%2Fi%2F122263216963-0-1%2Fs-l1000.jpg&f=1&nofb=1)

Or actually have a d100 die. (yeah, I have seen them in real life) 

![d100](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.L2bcD_HqaEQZoMcVJCOX2wHaI8%26pid%3DApi&f=1)

Not sure which is preferable, to be honest. Because I have used them all in my time playing RPGs.

**Comment by LDeeJay1969** [comment]
The d100 is a pita. I have one and it's horrible to roll due to size and surfaces. I prefer the 10 and 1, most clear results and roll pretty natural. No issues of which color is what.

**Comment by Kruptein** [comment]
I actually have a d10 with 10/20/30/... as a separate model.
I hadn't added it yet because unlike other combinations of dice the meaning of a percentile die + a d10 can differ per system or by preference. (e.g. 0 + 00 usually means 100).

Now there is not really a problem with adding custom logic for that case, my main concern however is, what should happen if someone rolls a percentile die + a d12 or, 2 percentile die, or any other combination of die that is not just 1 percentile + 1d10.

It can be argued that there shouldn't be a reason for such a roll to be made, but either I need to explicitly prohibit it in the UI or have some rule to process these rolls.

Does anybody know what other die rolling programs do in this case ? (be it virtual or textual)

**Comment by develroo** [comment]
Well most dice programs use expanding math braces. From the veteran 'rolldice' program
```

DICE STRING FORMAT
       The dice string uses the following format:

              {#x}{#}d[#|%]{*#}{+/-#}{s#}

       The  dice string doesn't have to be in the exact format outlined above, but this is the order I use.  It will try to parse any different string containing the same sections in the best way it can, and
       will throw out anything that isn't one of the sections below.

              {#}d[#|%]
                     The first number is the number of dice to roll, and the second number is the number of sides the dice have.  The numbers rolled on each die are then added up and  given  as  the  result.
                     Hence  3d6  means  "roll three six-sided dice, add them together and return the result".  If the first number is left out, then the number of dice defaults to 1.  If the second number is
                     not a number, but a percentage sign (%), then the number of sides becomes 100 (for a percentage roll).  If this is not included in the dice string, then the default is 1d6.

              {#x}   This number describes how many times to roll.  For example, if you want to roll 3 6-sided dice 6 times, you use the dice string 6x3d6.  This returns six numbers, corresponding to the six
                     different rolls.

              {*#}   This  number  describes  how  many times to multiply the result of each roll.  3d6*100 returns a number in the range of 300-1800, because 3-18 is the range for 3d6 and the result is then
                     multipled by 100.

              {+/-#} This number is the modifier to be added or subtracted, depending on the sign, from each roll.  1d4+1 results in a range from 2-5 (1-4 for the die, plus 1).  This step is handled  *after*
                     the multiplication modifier.

              {s#}   This number describes how many lowest dice rolls to drop.  This step is handled *before* the multiplication modifier.

       in the order show above.  For an extreme example, "3x4d6*5+1s2" would roll four six-sided dice, drop the lowest two, multiply the result by 5, add 1 to that, and repeat the process two more times, for
       a total of three results.

```


You can find the source code here if it helps :) 

http://deb.debian.org/debian/pool/main/r/rolldice/rolldice_1.16.orig.tar.gz

**Comment by develroo** [comment]
Actually misread he comment. It terms of how to present to  maybe you just need to copy teal

http://a.teall.info/dice/

Not the percentile dice is JUST the tens.  You have to add a d10 to it to make d100. Seems logical to me as it still give you a summation

**Comment by Kruptein** [comment]
That has very inconsistent behaviour imo. I rolled a d100 that landed on 00
and a d12 that landed on 10, it gave 0 + 10 = 10, but a d100 on 90 + d10 on
0 gave 90+
10=100.

**Comment by dthv** [comment]
Well, the two dice in combination are just a representation for a single d100, so, mechanically, a d% or d100 should be treated like a single die with 100 faces. Normal rules on summing up dice should apply, whatever they are.

Also, 00+0 should be treated like 100. I am not a aware of any game that does percentages from 0 to 99 instead of 1 to 100. In case of doubt, add a configuration option to treat 0+00 as zero instead of 100.

Just my two cents.

**Comment by develroo** [comment]
Well kinda sorta. a d10 is 1-10 a d100 is 00 -90  so it is a little odd but not really too strange.

**Comment by develroo** [comment]
Thinking about this some more, I think the problem is 0. In so much as are we to represent 0-100 or 1-100. Going back to the coloured die paradigm that inherently limited it to 11 -100 so 1-100 I feel is more 'natural' as any other dies we roll cannot roll a 0 either. As to the logic to represent it, the closest we can get to 1-100 is like the above model of `d10 = 1-10` and `d% =((10-100) -10)` 

You basically ignore 0.

**Comment by dthv** [comment]
Yes, the problem is 0. But, actually, you are either representing 0-99 or 1-100. 0-100 are not 100 but 101 possible outcomes of a roll.

**Comment by dthv** [comment]
> In so much as are we to represent 0-100 or 1-100.

> you are either representing 0-99 or 1-100. 0-100 are not 100 but 101 possible outcomes of a roll.

**Comment by develroo** [comment]
Where are you saying it is representing 101? The maximum d% can reach is 90 because you subtract 10 from it. a d10 can only represent 1-10. I am failing to see your grievance, sorry.

**Comment by Kruptein** [comment]
This is what I meant with, it all depends on which system and which preference.

The default rules, which you can change as you please, for dnd 5e is that a d100 represents 0-90 with the special interaction that 0 on a d100 AND 0 on a d10 represents 100.

This entire discussion you two are having is about 2 different ways to interpret things and that is the entire reason why I haven't included it yet.

The ultimate end solution is that this should be configurable by the user.

**Comment by dthv** [comment]
@develroo First quote above quotes you, second quote quotes me.

Either way,
> as d10 does not have a zero value, it means the percentile cannot have a zero value either
both d10/d% absolutely *can* have a zero value. It's even printed on most (=all) of them.

It depends on whether you want to display 0-99 or 1-100.

**0–99**: Simply add up the displayed values of d10 and d%, both zero-values counting as zero. `00` + `0` = zero, `10`+ `0` = ten, `10` + `2` = twelve.

**1–100**: Different ways. Either the above with the `00` + `0` = hundred exception. Or you treat `0` as ten, but keep treating `00` as zero. => `00` + `1` = one, `00` + `0` = ten, `90` + `0` = hundred. I have to admit that last one's a bit weird.

So, there are even *three* ways of interpreting the d10/d% combination. I'm sure there are more.

I concur that this should be configurable by users (and my apologies for the snarky comment that exactly this was the reason why I argued against a dice-tool in the first place. No offense intended.).

**Comment by develroo** [comment]
Well, I can't think of a system that employs 0-100, 0-99, maybe. So to my mind there are only 2 paradigms. 0-99 or 1-100. Both are pretty easy to calculate without needed to massively change how d10 is calculated. 

Either you take d10 as 1-10 or 0-9

d% will stay the same as ((10-100)-10)

As 0-9 you get 0-99. As 1-10 you get 1-100.

**Comment by dthv** [comment]
As I keep repeating: 0-100 is not possible on a "d100" as 0-100 are, in total, 101 possible values.

We keep arguing over something that's probably a typo on your side (yesterday, see quotes) that you clearly understood correctly and that I mis-interpreted as an error in thinking while it was an error in typing. My apologies.

**Comment by develroo** [comment]
> As I keep repeating: 0-100 is not possible on a "d100" as 0-100 are, in total, 101 possible values.
> 
> We keep arguing over something that's probably a typo on your side (yesterday, see quotes) that you clearly understood correctly and that I mis-interpreted as an error in thinking while it was an error in typing. My apologies.

That is my point 0-100 is not needed so we can ignore it. 0-99, perhaps, 1-100 certainly. I can't really see any use for any other percentile combinations myself.

**Comment by dthv** [comment]
So, we have at least three methods of how to represent both 0-99 and 1-100 on the "two-dice-d100". I'm not talking math here, because the dice tool gives users visual dice that have to be consistent with the summed up value, regardless whether we add up dice individually or just get one random number and display it with two dice.

Next problem includes operations (i.e. add/substract to/from other dice etc.). With our "two-dice-d100" this is easy, because we only have one value per "two-dice-d100", be it within 0-99 or 1-100. Yet, the next question is whether d% can be rolled individually (I'd argue yes, because it's possible that some rpg would work just like that. "why would you want to do this" is not a valid question) and, again, whether `00` is equal to zero or hundred.

This will end in a configuration hell of our own making. :sweat_smile:

**Comment by dthv** [comment]
My problem with "visually representing" is that presentation of dice needs to be consistent with presented number.
If a player is used to "`90`+`0` = hundred", they will be confused seeing `90` and `0` on the dice and `90 (ninety)` in the results.

Basically, I don't want users to misunderstand PA like the two of us keep misunderstanding each other.

> We either represent 0-99 or 1-100. Visually, they will both look exactly the same.

No. That's exactly the point here. Depending on your interpretation of the two dice, `90` and `0` can *either* mean ninety *or* hundred.

**Comment by develroo** [comment]
Well then it should be not hard to make that model work too. As I mentioned percentile die are not rolled singly they are rolled as a pair. That means the d10 in the percentile is already a different model As it is going to be visually different to a normal d10 anyway, and have 0 marked as 10. The d% die does not need to be changed. So you can either mark 0 as 10 or 0 as zero on the companion die depending on the flag you set.

**Comment by develroo** [comment]
So basically the model for the d10%  would look like this. 
![d10pc_uv](https://user-images.githubusercontent.com/7777993/174829031-9350edde-62ab-4f85-887d-cd4ecc903b43.png)


(I may have got the inversion wrong, but the principle is the same)

**Comment by develroo** [comment]
So the newest addition to the dice function gives a 10's die (00-90)  so giving effectively a percentile roll with 1d100 + 1d10 , though I am still unsure what a 0 00 roll means if it is 100 or zero ;) 

Either way, it will do, so I am closing this issue.
