### ISSUE TITLE
Move token to other location

### ISSUE THREAD

**Issue by Purzelkater** [Kruptein/PlanarAlly#97]
It would be nice, if tokens could be moved to other locations (maps/pages). This would it make easier to handle with player tokens. At to moment, every token has to be inserted on every location and all tracker and aura settings manually edited.

**Comment by Kruptein** [comment]
Interesting idea, I'll add it to my list of todo's :)

**Comment by Daniferrito** [comment]
It could e an option in the right click menu, just as moving tokens to another layer. I will probably take a look at this

**Comment by Kruptein** [comment]
Either that and/or something with dragging a token on a location.

I've plans to change the way the location bar at the top functions (as tbh it currently is rather ugly).

But by all means go ahead and add it to the context menu :)

**Comment by dthv** [comment]
Is a drag/drop option with the new top-bar planned?

**Comment by Kruptein** [comment]
there isn't but it shouldn't be too hard to implement.
