### ISSUE TITLE
[FEAT]Cut down on unnecessary white space in selection info

### ISSUE THREAD

**Issue by 10leej** [Kruptein/PlanarAlly#974]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Cut down on white space in the selection info, right margin definately, maybe 

**Describe alternatives you've considered**
Honestly reducing white space is really all thats needed here, I highlighted the two side we can trim on, the tracker value is that I'm calling the numbers track name is the string on the left

![Screenshot from 2022-06-18 13-25-00](https://user-images.githubusercontent.com/2258333/174449821-a1b06bfe-6eb0-4673-a41d-423eeb0d3b87.png)

We can save considerable white space to the right of the track value, maybe place the lock and properties icon next to each other horizontally to save vertical spacing if thats needed as well.
Then we can trim white space between the trackers name, and the value

**Comment by Kruptein** [comment]
This has been resolved by now.
