### ISSUE TITLE
DM und clients on different locations

### ISSUE THREAD

**Issue by Purzelkater** [Kruptein/PlanarAlly#98]
I don't know how difficult this would be, but it would be nice, if DM and clients could be on different locations (maps/pages) at the same time.
At the moment, if the DM switches to another location, als clients are switched too. So for the DM it's not possible to make changes on the location while the clients are on another location.
Roll20 has a player mark on the locations band so the DM can select wich location is actual shown for the clients and this is independently of the location where the DM is working on.

**Comment by Kruptein** [comment]
I wanted to add this from the very start, but somehow never managed to find time for it.

I also don't know exactly yet how I'm going to do it visually as I'm not sure if I'm allowed to blindly copy Roll20's method.

**Comment by dthv** [comment]
Implemented in 0.20.x?
