### ISSUE TITLE
[FEAT] Allow for uploading of entire folders

### ISSUE THREAD

**Issue by LinuxFTW** [Kruptein/PlanarAlly#988]
It would make life easier to add the ability to upload full folders rather than file by file. This may be a rough go for the public server though so concerns around that should be addressed and discussed.

I do intend on making an attempt at getting this to work, no promises.

**Comment by Kruptein** [comment]
This is actually already possible! You should be able to drop a folder in
the manager

**Comment by 10leej** [comment]
Drop and drop works, but on Linux the file picker (in my case it's zenity) will not recognize a folder, not sure if this is replicated on MS windows

**Comment by LinuxFTW** [comment]
It does in fact work as explained here. My apologies.
